
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr  7 2025 16:27:01 -03 (Apr  7 2025 19:27:01 UTC)

// Verification Directory fv/signal_32bits 

module signal_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire UNCONNECTED, addinc_add_7_30_n_0, addinc_add_7_30_n_1,
       addinc_add_7_30_n_2, addinc_add_7_30_n_3, addinc_add_7_30_n_4,
       addinc_add_7_30_n_5, addinc_add_7_30_n_6;
  wire addinc_add_7_30_n_7, addinc_add_7_30_n_9, addinc_add_7_30_n_12,
       addinc_add_7_30_n_14, addinc_add_7_30_n_15,
       addinc_add_7_30_n_16, addinc_add_7_30_n_17, addinc_add_7_30_n_18;
  wire addinc_add_7_30_n_19, addinc_add_7_30_n_21,
       addinc_add_7_30_n_24, addinc_add_7_30_n_26,
       addinc_add_7_30_n_27, addinc_add_7_30_n_28,
       addinc_add_7_30_n_29, addinc_add_7_30_n_30;
  wire addinc_add_7_30_n_39, addinc_add_7_30_n_44,
       addinc_add_7_30_n_48, addinc_add_7_30_n_49,
       addinc_add_7_30_n_57, addinc_add_7_30_n_68,
       addinc_add_7_30_n_71, addinc_add_7_30_n_74;
  wire addinc_add_7_30_n_81, addinc_add_7_30_n_90,
       addinc_add_7_30_n_93, addinc_add_7_30_n_94,
       addinc_add_7_30_n_95, addinc_add_7_30_n_96,
       addinc_add_7_30_n_98, addinc_add_7_30_n_99;
  wire addinc_add_7_30_n_100, addinc_add_7_30_n_101,
       addinc_add_7_30_n_102, addinc_add_7_30_n_103,
       addinc_add_7_30_n_104, addinc_add_7_30_n_105,
       addinc_add_7_30_n_106, addinc_add_7_30_n_107;
  wire addinc_add_7_30_n_108, addinc_add_7_30_n_109,
       addinc_add_7_30_n_110, addinc_add_7_30_n_111,
       addinc_add_7_30_n_112, addinc_add_7_30_n_113,
       addinc_add_7_30_n_114, addinc_add_7_30_n_116;
  wire addinc_add_7_30_n_117, addinc_add_7_30_n_118,
       addinc_add_7_30_n_119, addinc_add_7_30_n_120,
       addinc_add_7_30_n_121, addinc_add_7_30_n_122,
       addinc_add_7_30_n_124, addinc_add_7_30_n_125;
  wire addinc_add_7_30_n_127, addinc_add_7_30_n_128,
       addinc_add_7_30_n_129, addinc_add_7_30_n_132,
       addinc_add_7_30_n_133, addinc_add_7_30_n_134,
       addinc_add_7_30_n_135, addinc_add_7_30_n_140;
  wire addinc_add_7_30_n_141, addinc_add_7_30_n_142,
       addinc_add_7_30_n_143, addinc_add_7_30_n_144,
       addinc_add_7_30_n_145, addinc_add_7_30_n_148,
       addinc_add_7_30_n_149, addinc_add_7_30_n_150;
  wire addinc_add_7_30_n_151, addinc_add_7_30_n_152,
       addinc_add_7_30_n_153, addinc_add_7_30_n_155,
       addinc_add_7_30_n_156, addinc_add_7_30_n_158,
       addinc_add_7_30_n_159, addinc_add_7_30_n_160;
  wire addinc_add_7_30_n_162, addinc_add_7_30_n_163,
       addinc_add_7_30_n_165, addinc_add_7_30_n_166,
       addinc_add_7_30_n_168, addinc_add_7_30_n_169,
       addinc_add_7_30_n_171, addinc_add_7_30_n_172;
  wire addinc_add_7_30_n_173, addinc_add_7_30_n_174,
       addinc_add_7_30_n_175, addinc_add_7_30_n_177,
       addinc_add_7_30_n_179, addinc_add_7_30_n_182,
       addinc_add_7_30_n_183, addinc_add_7_30_n_187;
  wire addinc_add_7_30_n_189, addinc_add_7_30_n_191,
       addinc_add_7_30_n_192, addinc_add_7_30_n_195,
       addinc_add_7_30_n_196, addinc_add_7_30_n_197,
       addinc_add_7_30_n_198, addinc_add_7_30_n_199;
  wire addinc_add_7_30_n_200, addinc_add_7_30_n_201,
       addinc_add_7_30_n_202, addinc_add_7_30_n_203,
       addinc_add_7_30_n_204, addinc_add_7_30_n_205,
       addinc_add_7_30_n_206, addinc_add_7_30_n_207;
  wire addinc_add_7_30_n_211, addinc_add_7_30_n_212,
       addinc_add_7_30_n_213, addinc_add_7_30_n_215,
       addinc_add_7_30_n_216, addinc_add_7_30_n_217,
       addinc_add_7_30_n_219, addinc_add_7_30_n_224;
  wire addinc_add_7_30_n_225, addinc_add_7_30_n_226,
       addinc_add_7_30_n_227, addinc_add_7_30_n_229,
       addinc_add_7_30_n_230, addinc_add_7_30_n_233,
       addinc_add_7_30_n_237, addinc_add_7_30_n_240;
  wire addinc_add_7_30_n_242, addinc_add_7_30_n_244,
       addinc_add_7_30_n_245, addinc_add_7_30_n_246,
       addinc_add_7_30_n_247, addinc_add_7_30_n_248,
       addinc_add_7_30_n_251, addinc_add_7_30_n_252;
  wire addinc_add_7_30_n_253, addinc_add_7_30_n_257,
       addinc_add_7_30_n_258, addinc_add_7_30_n_261,
       addinc_add_7_30_n_262, addinc_add_7_30_n_264,
       addinc_add_7_30_n_265, addinc_add_7_30_n_268;
  wire addinc_add_7_30_n_269, addinc_add_7_30_n_270,
       addinc_add_7_30_n_271, addinc_add_7_30_n_272,
       addinc_add_7_30_n_275, addinc_add_7_30_n_276,
       addinc_add_7_30_n_277, addinc_add_7_30_n_278;
  wire addinc_add_7_30_n_283, addinc_add_7_30_n_285,
       addinc_add_7_30_n_289, addinc_add_7_30_n_297,
       addinc_add_7_30_n_302, addinc_add_7_30_n_303,
       addinc_add_7_30_n_304, addinc_add_7_30_n_305;
  wire addinc_add_7_30_n_306, addinc_add_7_30_n_309,
       addinc_add_7_30_n_315, addinc_add_7_30_n_316,
       addinc_add_7_30_n_317, addinc_add_7_30_n_318,
       addinc_add_7_30_n_319, addinc_add_7_30_n_320;
  wire addinc_add_7_30_n_324, addinc_add_7_30_n_325,
       addinc_add_7_30_n_327, addinc_add_7_30_n_328,
       addinc_add_7_30_n_329, addinc_add_7_30_n_330,
       addinc_add_7_30_n_331, addinc_add_7_30_n_332;
  wire addinc_add_7_30_n_333, addinc_add_7_30_n_334,
       addinc_add_7_30_n_335, addinc_add_7_30_n_336,
       addinc_add_7_30_n_337, addinc_add_7_30_n_340,
       addinc_add_7_30_n_341, addinc_add_7_30_n_342;
  wire addinc_add_7_30_n_343, addinc_add_7_30_n_346,
       addinc_add_7_30_n_347, addinc_add_7_30_n_348,
       addinc_add_7_30_n_349, addinc_add_7_30_n_351,
       addinc_add_7_30_n_352, n_2;
  wire n_13, n_14, n_15, n_18, n_20, n_23, n_26, n_27;
  wire n_30, n_32, n_33, n_40, n_42, n_47, n_50, n_55;
  wire n_70, n_72, n_73, n_74, n_440, n_441, n_444, n_445;
  wire n_448, n_450, n_451, n_452, n_455, n_456, n_460, n_461;
  wire n_463, n_464, n_465, n_470, n_480, n_481, n_485, n_488;
  wire n_491, n_492, n_496, n_499, n_500, n_502, n_512, n_525;
  wire n_526, n_527, n_529, n_531, n_542, n_543, n_544, n_545;
  wire n_547, n_548, n_549, n_555, n_591, n_592, n_593, n_598;
  wire n_601, n_603, n_607, n_608, n_609, n_610, n_612, n_615;
  wire n_616, n_617, n_618, n_619, n_620, n_623, n_625, n_626;
  wire n_627, n_629, n_635, n_638, n_639, n_641, n_646, n_647;
  wire n_648, n_650, n_652, n_656, n_658, n_659, n_662, n_664;
  wire n_665, n_666, n_710, n_711, n_712, n_713, n_714, n_717;
  wire n_718, n_721, n_722, n_727, n_728, n_730, n_732, n_733;
  wire n_734, n_735, n_736, n_737, n_739, n_741, n_742, n_743;
  wire n_744, n_745, n_746, n_747, n_748, n_750, n_751, n_757;
  wire n_758, n_759, n_760, n_763, n_764, n_825, n_831, n_832;
  wire n_834, n_837, n_843, n_844, n_846, n_849, n_853, n_855;
  wire n_858, n_859, n_861, n_862, n_864, n_865, n_866, n_867;
  wire n_868, n_869, n_870, n_871, n_872, n_873, n_874, n_875;
  wire n_876, n_877, n_878, n_879, n_880, n_881, n_882, n_883;
  wire n_884, n_885, n_886, n_887;
  sky130_fd_sc_hd__inv_2 g60(.A (n_30), .Y (n_74));
  sky130_fd_sc_hd__inv_2 g40(.A (n_47), .Y (n_73));
  sky130_fd_sc_hd__inv_2 g58(.A (n_40), .Y (n_72));
  sky130_fd_sc_hd__inv_2 g42(.A (n_26), .Y (n_70));
  sky130_fd_sc_hd__inv_2 g81(.A (B[24]), .Y (addinc_add_7_30_n_81));
  sky130_fd_sc_hd__clkinv_1 g56(.A (B[26]), .Y (n_55));
  sky130_fd_sc_hd__inv_4 g85(.A (B[12]), .Y (addinc_add_7_30_n_48));
  sky130_fd_sc_hd__clkbuf_1 g73(.A (B[4]), .X (n_50));
  sky130_fd_sc_hd__clkinv_1 g41(.A (A[22]), .Y (n_47));
  sky130_fd_sc_hd__clkbuf_1 g20(.A (A[4]), .X (n_42));
  sky130_fd_sc_hd__clkinv_2 g59(.A (B[23]), .Y (n_40));
  sky130_fd_sc_hd__inv_2 g23(.A (A[6]), .Y (addinc_add_7_30_n_39));
  sky130_fd_sc_hd__clkbuf_1 g74(.A (A[30]), .X (n_33));
  sky130_fd_sc_hd__clkinv_1 g48(.A (A[27]), .Y (n_32));
  sky130_fd_sc_hd__clkinv_1 g61(.A (B[22]), .Y (n_30));
  sky130_fd_sc_hd__clkbuf_1 g49(.A (A[28]), .X (n_27));
  sky130_fd_sc_hd__clkinv_2 g43(.A (A[23]), .Y (n_26));
  sky130_fd_sc_hd__clkbuf_1 g15(.A (A[0]), .X (n_23));
  sky130_fd_sc_hd__inv_2 g17(.A (A[1]), .Y (addinc_add_7_30_n_71));
  sky130_fd_sc_hd__clkbuf_1 g31(.A (B[30]), .X (n_20));
  sky130_fd_sc_hd__clkbuf_1 g45(.A (A[25]), .X (n_18));
  sky130_fd_sc_hd__clkbuf_1 g89(.A (B[28]), .X (addinc_add_7_30_n_68));
  sky130_fd_sc_hd__clkbuf_1 g44(.A (A[24]), .X (n_15));
  sky130_fd_sc_hd__clkbuf_1 g57(.A (B[25]), .X (n_14));
  sky130_fd_sc_hd__inv_2 g72(.A (B[7]), .Y (n_13));
  sky130_fd_sc_hd__inv_2 g37(.A (A[19]), .Y (addinc_add_7_30_n_44));
  sky130_fd_sc_hd__clkinv_1 g79(.A (B[27]), .Y (n_2));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1796__2398(.A1_N
       (addinc_add_7_30_n_201), .A2_N (n_746), .B1
       (addinc_add_7_30_n_201), .B2 (n_746), .X (S[24]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1797__5107(.A1_N
       (addinc_add_7_30_n_206), .A2_N (addinc_add_7_30_n_352), .B1
       (addinc_add_7_30_n_206), .B2 (addinc_add_7_30_n_352), .X
       (S[29]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1798__6260(.A1_N
       (addinc_add_7_30_n_205), .A2_N (addinc_add_7_30_n_343), .B1
       (addinc_add_7_30_n_205), .B2 (addinc_add_7_30_n_343), .X
       (S[28]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1799__4319(.A1_N (n_652),
       .A2_N (addinc_add_7_30_n_347), .B1 (n_652), .B2
       (addinc_add_7_30_n_347), .X (S[27]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1800__8428(.A1_N (n_870),
       .A2_N (addinc_add_7_30_n_351), .B1 (n_870), .B2
       (addinc_add_7_30_n_351), .X (S[26]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1801__5526(.A1_N
       (addinc_add_7_30_n_203), .A2_N (addinc_add_7_30_n_346), .B1
       (addinc_add_7_30_n_203), .B2 (addinc_add_7_30_n_346), .X
       (S[25]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1802__6783(.A1_N
       (addinc_add_7_30_n_197), .A2_N (addinc_add_7_30_n_349), .B1
       (addinc_add_7_30_n_197), .B2 (addinc_add_7_30_n_349), .X
       (S[31]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1803__3680(.A1_N
       (addinc_add_7_30_n_177), .A2_N (addinc_add_7_30_n_342), .B1
       (addinc_add_7_30_n_177), .B2 (addinc_add_7_30_n_342), .X
       (S[19]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1804__1617(.A1_N
       (addinc_add_7_30_n_165), .A2_N (n_607), .B1
       (addinc_add_7_30_n_165), .B2 (n_607), .X (S[22]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1805__2802(.A1_N (n_757),
       .A2_N (addinc_add_7_30_n_348), .B1 (n_757), .B2
       (addinc_add_7_30_n_348), .X (S[21]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1806__1705(.A1_N
       (addinc_add_7_30_n_172), .A2_N (addinc_add_7_30_n_21), .B1
       (addinc_add_7_30_n_172), .B2 (addinc_add_7_30_n_21), .X (S[20]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1807__5122(.A1_N
       (addinc_add_7_30_n_199), .A2_N (n_601), .B1
       (addinc_add_7_30_n_199), .B2 (n_601), .X (S[23]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1808__8246(.A1_N
       (addinc_add_7_30_n_174), .A2_N (n_882), .B1
       (addinc_add_7_30_n_174), .B2 (n_882), .X (S[18]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1809__7098(.A1_N
       (addinc_add_7_30_n_171), .A2_N (addinc_add_7_30_n_341), .B1
       (addinc_add_7_30_n_171), .B2 (addinc_add_7_30_n_341), .X
       (S[17]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1810__6131(.A1_N
       (addinc_add_7_30_n_163), .A2_N (addinc_add_7_30_n_340), .B1
       (addinc_add_7_30_n_163), .B2 (addinc_add_7_30_n_340), .X
       (S[30]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1811__1881(.A1_N
       (addinc_add_7_30_n_168), .A2_N (addinc_add_7_30_n_332), .B1
       (addinc_add_7_30_n_168), .B2 (addinc_add_7_30_n_332), .X
       (S[15]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1812__5115(.A1_N (n_664),
       .A2_N (addinc_add_7_30_n_336), .B1 (n_664), .B2
       (addinc_add_7_30_n_336), .X (S[14]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1813__7482(.A1_N
       (addinc_add_7_30_n_175), .A2_N (addinc_add_7_30_n_333), .B1
       (addinc_add_7_30_n_175), .B2 (addinc_add_7_30_n_333), .X
       (S[13]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1814__4733(.A1_N
       (addinc_add_7_30_n_173), .A2_N (addinc_add_7_30_n_337), .B1
       (addinc_add_7_30_n_173), .B2 (addinc_add_7_30_n_337), .X
       (S[12]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1815__6161(.A1_N (n_531),
       .A2_N (addinc_add_7_30_n_324), .B1 (n_531), .B2
       (addinc_add_7_30_n_324), .X (S[11]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1816__9315(.A1_N
       (addinc_add_7_30_n_166), .A2_N (addinc_add_7_30_n_335), .B1
       (addinc_add_7_30_n_166), .B2 (addinc_add_7_30_n_335), .X (S[9]));
  sky130_fd_sc_hd__a2bb2o_4 addinc_add_7_30_g1817__9945(.A1_N
       (addinc_add_7_30_n_169), .A2_N (addinc_add_7_30_n_334), .B1
       (addinc_add_7_30_n_169), .B2 (addinc_add_7_30_n_334), .X
       (S[10]));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1818__2883(.A
       (addinc_add_7_30_n_325), .B (n_743), .Y (addinc_add_7_30_n_352));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1819__2346(.A (n_876), .B
       (n_874), .Y (addinc_add_7_30_n_351));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1821__7410(.A
       (addinc_add_7_30_n_327), .B (n_742), .Y (addinc_add_7_30_n_349));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1822__6417(.A
       (addinc_add_7_30_n_320), .B (addinc_add_7_30_n_283), .Y
       (addinc_add_7_30_n_348));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1823__5477(.A
       (addinc_add_7_30_n_319), .B (n_744), .Y (addinc_add_7_30_n_347));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1824__2398(.A
       (addinc_add_7_30_n_316), .B (n_745), .Y (addinc_add_7_30_n_346));
  sky130_fd_sc_hd__mux2_2 addinc_add_7_30_g1826__6260(.A0 (n_619), .A1
       (n_481), .S (addinc_add_7_30_n_182), .X (S[16]));
  sky130_fd_sc_hd__a31o_4 addinc_add_7_30_g1827__4319(.A1 (n_480), .A2
       (addinc_add_7_30_n_246), .A3 (addinc_add_7_30_n_245), .B1
       (n_739), .X (Cout));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1830__5526(.A
       (addinc_add_7_30_n_317), .B (n_737), .Y (addinc_add_7_30_n_343));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1831__6783(.A
       (addinc_add_7_30_n_315), .B (addinc_add_7_30_n_268), .Y
       (addinc_add_7_30_n_342));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1833__3680(.A
       (addinc_add_7_30_n_330), .B (addinc_add_7_30_n_110), .Y
       (addinc_add_7_30_n_341));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1834__1617(.A
       (addinc_add_7_30_n_318), .B (n_741), .Y (addinc_add_7_30_n_340));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1835__2802(.A (n_617), .B
       (addinc_add_7_30_n_162), .Y (addinc_add_7_30_n_331));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1836__1705(.A (n_617), .B
       (addinc_add_7_30_n_112), .Y (addinc_add_7_30_n_330));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1837__5122(.A (n_617), .B
       (n_603), .Y (addinc_add_7_30_n_329));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1838__8246(.A (n_617), .B
       (addinc_add_7_30_n_245), .Y (addinc_add_7_30_n_328));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1839__7098(.A (n_619), .B
       (addinc_add_7_30_n_248), .C (addinc_add_7_30_n_245), .Y
       (addinc_add_7_30_n_327));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1841__1881(.A (n_617), .B
       (addinc_add_7_30_n_245), .C (addinc_add_7_30_n_253), .Y
       (addinc_add_7_30_n_325));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1842__5115(.A1 (n_491), .A2
       (addinc_add_7_30_n_302), .B1 (addinc_add_7_30_n_257), .Y
       (addinc_add_7_30_n_337));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1843__7482(.A (n_658), .B
       (n_656), .Y (addinc_add_7_30_n_336));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1844__4733(.A1
       (addinc_add_7_30_n_143), .A2 (addinc_add_7_30_n_302), .B1
       (addinc_add_7_30_n_105), .Y (addinc_add_7_30_n_335));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1845__6161(.A1
       (addinc_add_7_30_n_192), .A2 (addinc_add_7_30_n_303), .B1
       (n_859), .X (addinc_add_7_30_n_334));
  sky130_fd_sc_hd__o211ai_2 addinc_add_7_30_g1846__9315(.A1
       (addinc_add_7_30_n_93), .A2 (addinc_add_7_30_n_257), .B1
       (addinc_add_7_30_n_142), .C1 (addinc_add_7_30_n_309), .Y
       (addinc_add_7_30_n_333));
  sky130_fd_sc_hd__a31o_1 addinc_add_7_30_g1847__9945(.A1
       (addinc_add_7_30_n_303), .A2 (n_659), .A3 (n_492), .B1
       (addinc_add_7_30_n_276), .X (addinc_add_7_30_n_332));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1848__2883(.A1_N
       (addinc_add_7_30_n_198), .A2_N (addinc_add_7_30_n_304), .B1
       (addinc_add_7_30_n_198), .B2 (addinc_add_7_30_n_304), .X (S[6]));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1851__7410(.A (n_619), .B
       (n_603), .C (addinc_add_7_30_n_98), .Y (addinc_add_7_30_n_320));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1852__6417(.A (n_619), .B
       (addinc_add_7_30_n_245), .C (n_877), .Y (addinc_add_7_30_n_319));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1853__5477(.A (n_617), .B
       (addinc_add_7_30_n_245), .C (addinc_add_7_30_n_247), .Y
       (addinc_add_7_30_n_318));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1854__2398(.A (n_617), .B
       (addinc_add_7_30_n_245), .C (addinc_add_7_30_n_230), .Y
       (addinc_add_7_30_n_317));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1855__5107(.A (n_617), .B
       (addinc_add_7_30_n_245), .C (addinc_add_7_30_n_127), .Y
       (addinc_add_7_30_n_316));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1856__6260(.A (n_619), .B
       (addinc_add_7_30_n_162), .C (addinc_add_7_30_n_101), .Y
       (addinc_add_7_30_n_315));
  sky130_fd_sc_hd__mux2_2 addinc_add_7_30_g1857__4319(.A0
       (addinc_add_7_30_n_302), .A1 (addinc_add_7_30_n_303), .S
       (addinc_add_7_30_n_155), .X (S[8]));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1858__8428(.A1_N (n_547),
       .A2_N (addinc_add_7_30_n_297), .B1 (n_547), .B2
       (addinc_add_7_30_n_297), .X (S[7]));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1859__5526(.A1_N
       (addinc_add_7_30_n_16), .A2_N (addinc_add_7_30_n_306), .B1
       (addinc_add_7_30_n_16), .B2 (addinc_add_7_30_n_306), .X (S[5]));
  sky130_fd_sc_hd__a2bb2o_2 addinc_add_7_30_g1860__6783(.A1_N
       (addinc_add_7_30_n_207), .A2_N (addinc_add_7_30_n_305), .B1
       (addinc_add_7_30_n_207), .B2 (addinc_add_7_30_n_305), .X (S[3]));
  sky130_fd_sc_hd__a31o_1 addinc_add_7_30_g1861__3680(.A1
       (addinc_add_7_30_n_303), .A2 (addinc_add_7_30_n_192), .A3
       (addinc_add_7_30_n_90), .B1 (addinc_add_7_30_n_270), .X
       (addinc_add_7_30_n_324));
  sky130_fd_sc_hd__nand3b_1 addinc_add_7_30_g1863__2802(.A_N
       (addinc_add_7_30_n_93), .B (addinc_add_7_30_n_303), .C (n_492),
       .Y (addinc_add_7_30_n_309));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1866(.A
       (addinc_add_7_30_n_303), .Y (addinc_add_7_30_n_302));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1871__6131(.A1 (n_831), .A2
       (n_853), .B1 (addinc_add_7_30_n_118), .Y
       (addinc_add_7_30_n_306));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1872__1881(.A1
       (addinc_add_7_30_n_95), .A2 (addinc_add_7_30_n_17), .B1
       (addinc_add_7_30_n_108), .Y (addinc_add_7_30_n_305));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1873__5115(.A1 (n_855), .A2
       (addinc_add_7_30_n_189), .B1 (n_849), .X
       (addinc_add_7_30_n_304));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1874__7482(.A
       (addinc_add_7_30_n_289), .B (addinc_add_7_30_n_272), .Y
       (addinc_add_7_30_n_303));
  sky130_fd_sc_hd__a2bb2o_1 addinc_add_7_30_g1879__2883(.A1_N
       (addinc_add_7_30_n_200), .A2_N (addinc_add_7_30_n_17), .B1
       (addinc_add_7_30_n_200), .B2 (addinc_add_7_30_n_17), .X (S[2]));
  sky130_fd_sc_hd__mux2_2 addinc_add_7_30_g1881__1666(.A0 (n_853), .A1
       (n_855), .S (n_763), .X (S[4]));
  sky130_fd_sc_hd__a31o_1 addinc_add_7_30_g1882__7410(.A1 (n_855), .A2
       (addinc_add_7_30_n_189), .A3 (addinc_add_7_30_n_125), .B1
       (addinc_add_7_30_n_265), .X (addinc_add_7_30_n_297));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1884__6417(.A
       (addinc_add_7_30_n_229), .B (n_591), .Y (addinc_add_7_30_n_289));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1887__2398(.A1
       (addinc_add_7_30_n_102), .A2 (n_627), .B1
       (addinc_add_7_30_n_106), .Y (addinc_add_7_30_n_285));
  sky130_fd_sc_hd__a21boi_1 addinc_add_7_30_g1889__6260(.A1 (n_834),
       .A2 (addinc_add_7_30_n_98), .B1_N (n_727), .Y
       (addinc_add_7_30_n_283));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1896__3680(.A1
       (addinc_add_7_30_n_240), .A2 (n_627), .B1
       (addinc_add_7_30_n_264), .Y (addinc_add_7_30_n_278));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1897__1617(.A1 (n_834), .A2
       (n_598), .B1 (addinc_add_7_30_n_269), .Y
       (addinc_add_7_30_n_277));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1898__2802(.A1
       (addinc_add_7_30_n_258), .A2 (n_659), .B1 (n_666), .X
       (addinc_add_7_30_n_276));
  sky130_fd_sc_hd__o211ai_2 addinc_add_7_30_g1899__1705(.A1
       (addinc_add_7_30_n_237), .A2 (n_627), .B1
       (addinc_add_7_30_n_116), .C1 (addinc_add_7_30_n_244), .Y
       (addinc_add_7_30_n_275));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g1905(.A
       (addinc_add_7_30_n_271), .Y (addinc_add_7_30_n_272));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1906__6131(.A1 (n_859), .A2
       (addinc_add_7_30_n_90), .B1 (addinc_add_7_30_n_111), .X
       (addinc_add_7_30_n_270));
  sky130_fd_sc_hd__o21ai_0 addinc_add_7_30_g1907__1881(.A1
       (addinc_add_7_30_n_27), .A2 (n_730), .B1
       (addinc_add_7_30_n_149), .Y (addinc_add_7_30_n_269));
  sky130_fd_sc_hd__a21boi_1 addinc_add_7_30_g1908__5115(.A1
       (addinc_add_7_30_n_224), .A2 (addinc_add_7_30_n_101), .B1_N
       (n_884), .Y (addinc_add_7_30_n_268));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1911__6161(.A1 (n_849), .A2
       (addinc_add_7_30_n_125), .B1 (addinc_add_7_30_n_140), .X
       (addinc_add_7_30_n_265));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1912__9315(.A1
       (addinc_add_7_30_n_233), .A2 (addinc_add_7_30_n_196), .B1
       (addinc_add_7_30_n_216), .Y (addinc_add_7_30_n_264));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1913__9945(.A
       (addinc_add_7_30_n_252), .B (n_545), .Y (addinc_add_7_30_n_271));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g1918(.A
       (addinc_add_7_30_n_258), .Y (addinc_add_7_30_n_257));
  sky130_fd_sc_hd__nand3_2 addinc_add_7_30_g1923__7410(.A (n_751), .B
       (n_549), .C (n_750), .Y (addinc_add_7_30_n_262));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1924__6417(.A
       (addinc_add_7_30_n_251), .B (addinc_add_7_30_n_217), .Y
       (addinc_add_7_30_n_261));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1926__2398(.A
       (addinc_add_7_30_n_18), .B (addinc_add_7_30_n_26), .Y
       (addinc_add_7_30_n_258));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1928__5107(.A
       (addinc_add_7_30_n_30), .B (addinc_add_7_30_n_204), .Y
       (addinc_add_7_30_n_252));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1929__6260(.A
       (addinc_add_7_30_n_224), .B (addinc_add_7_30_n_15), .Y
       (addinc_add_7_30_n_251));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1931__8428(.A
       (addinc_add_7_30_n_102), .B (n_878), .Y (addinc_add_7_30_n_253));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1933__5526(.A
       (addinc_add_7_30_n_233), .B (addinc_add_7_30_n_1), .Y
       (addinc_add_7_30_n_244));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1935__3680(.A
       (addinc_add_7_30_n_237), .B (n_878), .Y (addinc_add_7_30_n_248));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1936__1617(.A (n_878), .B_N
       (addinc_add_7_30_n_195), .Y (addinc_add_7_30_n_247));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1937__2802(.A
       (addinc_add_7_30_n_240), .B (n_878), .Y (addinc_add_7_30_n_246));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g1938__1705(.A
       (addinc_add_7_30_n_242), .B (n_603), .X (addinc_add_7_30_n_245));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1945(.A (n_878), .Y
       (addinc_add_7_30_n_230));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1946__5122(.A
       (addinc_add_7_30_n_204), .B (addinc_add_7_30_n_189), .X
       (addinc_add_7_30_n_229));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1948__7098(.A (n_764), .B
       (addinc_add_7_30_n_191), .Y (addinc_add_7_30_n_227));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g1949__6131(.A (n_883), .B
       (addinc_add_7_30_n_202), .X (addinc_add_7_30_n_242));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1951__5115(.A
       (addinc_add_7_30_n_196), .B (addinc_add_7_30_n_195), .Y
       (addinc_add_7_30_n_240));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1954__6161(.A
       (addinc_add_7_30_n_195), .B (addinc_add_7_30_n_1), .Y
       (addinc_add_7_30_n_237));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1957__2883(.A1
       (addinc_add_7_30_n_106), .A2 (addinc_add_7_30_n_132), .B1
       (addinc_add_7_30_n_151), .Y (addinc_add_7_30_n_233));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g1963(.A
       (addinc_add_7_30_n_226), .Y (addinc_add_7_30_n_225));
  sky130_fd_sc_hd__o21a_1 addinc_add_7_30_g1969__5477(.A1 (n_884), .A2
       (addinc_add_7_30_n_24), .B1 (addinc_add_7_30_n_3), .X
       (addinc_add_7_30_n_217));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1971__2398(.A1
       (addinc_add_7_30_n_109), .A2 (addinc_add_7_30_n_116), .B1
       (addinc_add_7_30_n_120), .Y (addinc_add_7_30_n_216));
  sky130_fd_sc_hd__o21ai_0 addinc_add_7_30_g1972__5107(.A1
       (addinc_add_7_30_n_149), .A2 (addinc_add_7_30_n_133), .B1
       (addinc_add_7_30_n_153), .Y (addinc_add_7_30_n_215));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1974__4319(.A
       (addinc_add_7_30_n_128), .B (addinc_add_7_30_n_96), .C
       (addinc_add_7_30_n_134), .Y (addinc_add_7_30_n_213));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1975__8428(.A
       (addinc_add_7_30_n_128), .B (addinc_add_7_30_n_96), .C
       (addinc_add_7_30_n_28), .Y (addinc_add_7_30_n_212));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1976__5526(.A (n_544), .B
       (n_527), .Y (addinc_add_7_30_n_211));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1978__3680(.A
       (addinc_add_7_30_n_187), .B (addinc_add_7_30_n_5), .Y
       (addinc_add_7_30_n_226));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1979__1617(.A
       (addinc_add_7_30_n_158), .B (addinc_add_7_30_n_0), .Y
       (addinc_add_7_30_n_224));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1980__2802(.A
       (addinc_add_7_30_n_183), .B (addinc_add_7_30_n_122), .Y
       (addinc_add_7_30_n_30));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1982__5122(.A
       (addinc_add_7_30_n_159), .B (addinc_add_7_30_n_2), .Y
       (addinc_add_7_30_n_219));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1984(.A
       (addinc_add_7_30_n_191), .Y (addinc_add_7_30_n_192));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g1986(.A (n_764), .Y
       (addinc_add_7_30_n_189));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1987__8246(.A
       (addinc_add_7_30_n_129), .B (addinc_add_7_30_n_141), .Y
       (addinc_add_7_30_n_187));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1991__5115(.A
       (addinc_add_7_30_n_117), .B (addinc_add_7_30_n_103), .Y
       (addinc_add_7_30_n_183));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1995__6161(.A
       (addinc_add_7_30_n_4), .B (addinc_add_7_30_n_128), .Y
       (addinc_add_7_30_n_207));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1996__9315(.A_N
       (addinc_add_7_30_n_132), .B (addinc_add_7_30_n_151), .Y
       (addinc_add_7_30_n_206));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g1997__9945(.A
       (addinc_add_7_30_n_110), .B (addinc_add_7_30_n_112), .X
       (addinc_add_7_30_n_182));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1998__2883(.A_N
       (addinc_add_7_30_n_102), .B (addinc_add_7_30_n_106), .Y
       (addinc_add_7_30_n_205));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1999__2346(.A
       (addinc_add_7_30_n_124), .B (n_543), .Y (addinc_add_7_30_n_204));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2000__1666(.A_N (n_872),
       .B (addinc_add_7_30_n_7), .Y (addinc_add_7_30_n_203));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2001__7410(.A
       (addinc_add_7_30_n_27), .B (addinc_add_7_30_n_133), .Y
       (addinc_add_7_30_n_202));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2002__6417(.A
       (addinc_add_7_30_n_114), .B (addinc_add_7_30_n_127), .Y
       (addinc_add_7_30_n_201));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g2003__5477(.A
       (addinc_add_7_30_n_108), .B (addinc_add_7_30_n_96), .X
       (addinc_add_7_30_n_200));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2004__2398(.A_N
       (addinc_add_7_30_n_133), .B (addinc_add_7_30_n_153), .Y
       (addinc_add_7_30_n_199));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2005__5107(.A_N
       (addinc_add_7_30_n_140), .B (addinc_add_7_30_n_125), .Y
       (addinc_add_7_30_n_198));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2006__6260(.A_N
       (addinc_add_7_30_n_109), .B (addinc_add_7_30_n_120), .Y
       (addinc_add_7_30_n_197));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g2007__4319(.A
       (addinc_add_7_30_n_109), .B_N (addinc_add_7_30_n_1), .Y
       (addinc_add_7_30_n_196));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2009__5526(.A
       (addinc_add_7_30_n_102), .B (addinc_add_7_30_n_132), .Y
       (addinc_add_7_30_n_195));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2012__1617(.A
       (addinc_add_7_30_n_144), .B (addinc_add_7_30_n_148), .Y
       (addinc_add_7_30_n_191));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2017__8246(.A
       (addinc_add_7_30_n_128), .B (addinc_add_7_30_n_107), .Y
       (addinc_add_7_30_n_160));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2018__7098(.A
       (addinc_add_7_30_n_148), .B (addinc_add_7_30_n_104), .Y
       (addinc_add_7_30_n_159));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2019__6131(.A
       (addinc_add_7_30_n_6), .B (addinc_add_7_30_n_12), .Y
       (addinc_add_7_30_n_158));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2021__5115(.A
       (addinc_add_7_30_n_145), .B (addinc_add_7_30_n_113), .Y
       (addinc_add_7_30_n_156));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2022__7482(.A
       (addinc_add_7_30_n_28), .B (addinc_add_7_30_n_135), .Y
       (addinc_add_7_30_n_179));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2024__6161(.A_N
       (addinc_add_7_30_n_24), .B (addinc_add_7_30_n_3), .Y
       (addinc_add_7_30_n_177));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2027__9945(.A
       (addinc_add_7_30_n_5), .B (addinc_add_7_30_n_129), .Y
       (addinc_add_7_30_n_175));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2028__2883(.A (n_884), .B
       (addinc_add_7_30_n_101), .Y (addinc_add_7_30_n_174));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2029__2346(.A
       (addinc_add_7_30_n_142), .B (addinc_add_7_30_n_94), .Y
       (addinc_add_7_30_n_173));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2030__1666(.A (n_727), .B
       (addinc_add_7_30_n_98), .Y (addinc_add_7_30_n_172));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2031__7410(.A_N
       (addinc_add_7_30_n_150), .B (addinc_add_7_30_n_0), .Y
       (addinc_add_7_30_n_171));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2033__6417(.A
       (addinc_add_7_30_n_105), .B (addinc_add_7_30_n_144), .Y
       (addinc_add_7_30_n_155));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2035__2398(.A_N
       (addinc_add_7_30_n_111), .B (addinc_add_7_30_n_90), .Y
       (addinc_add_7_30_n_169));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2036__5107(.A
       (addinc_add_7_30_n_9), .B (addinc_add_7_30_n_100), .Y
       (addinc_add_7_30_n_168));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2039__8428(.A
       (addinc_add_7_30_n_2), .B (addinc_add_7_30_n_148), .Y
       (addinc_add_7_30_n_166));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2040__5526(.A_N
       (addinc_add_7_30_n_27), .B (addinc_add_7_30_n_149), .Y
       (addinc_add_7_30_n_165));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2042__3680(.A
       (addinc_add_7_30_n_116), .B (addinc_add_7_30_n_1), .Y
       (addinc_add_7_30_n_163));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2043__1617(.A
       (addinc_add_7_30_n_14), .B (addinc_add_7_30_n_150), .Y
       (addinc_add_7_30_n_162));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2044(.A
       (addinc_add_7_30_n_6), .Y (addinc_add_7_30_n_150));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2047(.A
       (addinc_add_7_30_n_144), .Y (addinc_add_7_30_n_143));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2048(.A
       (addinc_add_7_30_n_141), .Y (addinc_add_7_30_n_142));
  sky130_fd_sc_hd__clkinv_1 addinc_add_7_30_g2051(.A
       (addinc_add_7_30_n_134), .Y (addinc_add_7_30_n_135));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2053(.A (n_871), .Y
       (addinc_add_7_30_n_127));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2055(.A
       (addinc_add_7_30_n_125), .Y (addinc_add_7_30_n_124));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2059__2802(.A (n_72), .B
       (n_70), .Y (addinc_add_7_30_n_153));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2060__1705(.A (n_647), .B
       (n_646), .Y (addinc_add_7_30_n_152));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2062__5122(.A (B[29]), .B
       (A[29]), .Y (addinc_add_7_30_n_151));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2065__8246(.A (n_74), .B
       (n_73), .Y (addinc_add_7_30_n_149));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2066__7098(.A (n_488), .B
       (n_441), .Y (addinc_add_7_30_n_148));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2070__1881(.A
       (addinc_add_7_30_n_74), .B (addinc_add_7_30_n_49), .Y
       (addinc_add_7_30_n_145));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2071__5115(.A (n_635), .B
       (n_825), .Y (addinc_add_7_30_n_144));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2072__7482(.A
       (addinc_add_7_30_n_48), .B (n_714), .Y (addinc_add_7_30_n_141));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2073__4733(.A (n_470), .B
       (addinc_add_7_30_n_39), .Y (addinc_add_7_30_n_140));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2077__2883(.A
       (addinc_add_7_30_n_71), .B (n_846), .Y (addinc_add_7_30_n_134));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2078__2346(.A (n_70), .B
       (n_72), .Y (addinc_add_7_30_n_133));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2079__1666(.A (A[29]), .B
       (B[29]), .Y (addinc_add_7_30_n_132));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2081__6417(.A (n_722), .B
       (n_717), .Y (addinc_add_7_30_n_129));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2082__5477(.A (n_465), .B
       (n_445), .Y (addinc_add_7_30_n_128));
  sky130_fd_sc_hd__nor2_4 addinc_add_7_30_g2084__2398(.A (n_864), .B
       (n_865), .Y (addinc_add_7_30_n_29));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2087__6260(.A
       (addinc_add_7_30_n_39), .B (n_470), .Y (addinc_add_7_30_n_125));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2088(.A
       (addinc_add_7_30_n_117), .Y (addinc_add_7_30_n_118));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2089(.A
       (addinc_add_7_30_n_113), .Y (addinc_add_7_30_n_114));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2090(.A
       (addinc_add_7_30_n_14), .Y (addinc_add_7_30_n_112));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2091(.A
       (addinc_add_7_30_n_12), .Y (addinc_add_7_30_n_110));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2094(.A
       (addinc_add_7_30_n_107), .Y (addinc_add_7_30_n_108));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2095(.A
       (addinc_add_7_30_n_104), .Y (addinc_add_7_30_n_105));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2098(.A
       (addinc_add_7_30_n_100), .Y (addinc_add_7_30_n_99));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2101(.A
       (addinc_add_7_30_n_96), .Y (addinc_add_7_30_n_95));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2102(.A
       (addinc_add_7_30_n_94), .Y (addinc_add_7_30_n_93));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2109__6783(.A (n_451), .B
       (n_499), .Y (addinc_add_7_30_n_122));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2110__3680(.A (n_13), .B
       (n_837), .Y (addinc_add_7_30_n_121));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2111__1617(.A (B[31]), .B
       (A[31]), .Y (addinc_add_7_30_n_120));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2112__2802(.A (B[11]), .B
       (n_638), .Y (addinc_add_7_30_n_119));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2114__1705(.A (n_759), .B
       (n_758), .Y (addinc_add_7_30_n_117));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2116__5122(.A (n_20), .B
       (n_33), .Y (addinc_add_7_30_n_116));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2118__7098(.A
       (addinc_add_7_30_n_81), .B (addinc_add_7_30_n_57), .Y
       (addinc_add_7_30_n_113));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2120__6131(.A (n_444), .B
       (n_440), .Y (addinc_add_7_30_n_111));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2122__1881(.A (A[31]), .B
       (B[31]), .Y (addinc_add_7_30_n_109));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2123__5115(.A (n_846), .B
       (addinc_add_7_30_n_71), .Y (addinc_add_7_30_n_28));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2124__7482(.A (n_448), .B
       (n_456), .Y (addinc_add_7_30_n_107));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2125__4733(.A
       (addinc_add_7_30_n_68), .B (n_27), .Y (addinc_add_7_30_n_106));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2126__6161(.A (n_825), .B
       (n_635), .Y (addinc_add_7_30_n_104));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2127__9315(.A (n_500), .B
       (n_452), .Y (addinc_add_7_30_n_103));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g2128__9945(.A (n_27), .B
       (addinc_add_7_30_n_68), .Y (addinc_add_7_30_n_102));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2129__2883(.A (n_455), .B
       (n_450), .Y (addinc_add_7_30_n_101));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2130__2346(.A (n_464), .B
       (n_463), .Y (addinc_add_7_30_n_100));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2131__1666(.A (n_862), .B
       (n_512), .Y (addinc_add_7_30_n_98));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2132__7410(.A (n_73), .B
       (n_74), .Y (addinc_add_7_30_n_27));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2133__6417(.A (n_456), .B
       (n_448), .Y (addinc_add_7_30_n_96));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2134__5477(.A (n_714), .B
       (addinc_add_7_30_n_48), .Y (addinc_add_7_30_n_94));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2136__5107(.A (n_440), .B
       (n_444), .Y (addinc_add_7_30_n_90));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2157(.A (n_18), .Y
       (addinc_add_7_30_n_74));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2184(.A (n_15), .Y
       (addinc_add_7_30_n_57));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2194(.A (n_14), .Y
       (addinc_add_7_30_n_49));
  sky130_fd_sc_hd__and2_2 addinc_add_7_30_g2__6260(.A
       (addinc_add_7_30_n_119), .B (n_529), .X (addinc_add_7_30_n_26));
  sky130_fd_sc_hd__and2_1 addinc_add_7_30_g2217__8428(.A
       (addinc_add_7_30_n_44), .B (n_502), .X (addinc_add_7_30_n_24));
  sky130_fd_sc_hd__nand2b_2 addinc_add_7_30_g2220__3680(.A_N (n_834),
       .B (addinc_add_7_30_n_329), .Y (addinc_add_7_30_n_21));
  sky130_fd_sc_hd__nand2b_2 addinc_add_7_30_g2222__2802(.A_N
       (addinc_add_7_30_n_213), .B (addinc_add_7_30_n_262), .Y
       (addinc_add_7_30_n_19));
  sky130_fd_sc_hd__nand2b_2 addinc_add_7_30_g2223__1705(.A_N (n_526),
       .B (addinc_add_7_30_n_219), .Y (addinc_add_7_30_n_18));
  sky130_fd_sc_hd__o21ba_2 addinc_add_7_30_g2224__5122(.A1
       (addinc_add_7_30_n_135), .A2 (n_460), .B1_N
       (addinc_add_7_30_n_28), .X (addinc_add_7_30_n_17));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2225__8246(.A
       (addinc_add_7_30_n_103), .B (addinc_add_7_30_n_122), .Y
       (addinc_add_7_30_n_16));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g2226__7098(.A
       (addinc_add_7_30_n_24), .B_N (addinc_add_7_30_n_101), .Y
       (addinc_add_7_30_n_15));
  sky130_fd_sc_hd__and2b_1 addinc_add_7_30_g2227__6131(.A_N (A[16]), .B
       (n_496), .X (addinc_add_7_30_n_14));
  sky130_fd_sc_hd__nor2b_4 addinc_add_7_30_g2229__5115(.A (n_496), .B_N
       (A[16]), .Y (addinc_add_7_30_n_12));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2232__6161(.A (n_463), .B
       (n_464), .X (addinc_add_7_30_n_9));
  sky130_fd_sc_hd__or2_2 addinc_add_7_30_g2235__9945(.A
       (addinc_add_7_30_n_49), .B (addinc_add_7_30_n_74), .X
       (addinc_add_7_30_n_7));
  sky130_fd_sc_hd__nand2b_4 addinc_add_7_30_g2237__2883(.A_N (A[17]),
       .B (n_485), .Y (addinc_add_7_30_n_6));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2238__2346(.A (n_717), .B
       (n_722), .X (addinc_add_7_30_n_5));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2239__1666(.A (n_445), .B
       (n_465), .X (addinc_add_7_30_n_4));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2240__7410(.A (n_502), .B
       (addinc_add_7_30_n_44), .X (addinc_add_7_30_n_3));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2241__6417(.A (n_441), .B
       (n_488), .X (addinc_add_7_30_n_2));
  sky130_fd_sc_hd__or2_4 addinc_add_7_30_g2242__5477(.A (n_33), .B
       (n_20), .X (addinc_add_7_30_n_1));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2243__2398(.A_N (n_485),
       .B (A[17]), .Y (addinc_add_7_30_n_0));
  sky130_fd_sc_hd__inv_4 fopt(.A (B[10]), .Y (n_440));
  sky130_fd_sc_hd__inv_2 fopt2246(.A (B[9]), .Y (n_441));
  sky130_fd_sc_hd__inv_4 fopt2248(.A (A[10]), .Y (n_444));
  sky130_fd_sc_hd__inv_2 fopt2249(.A (B[3]), .Y (n_445));
  sky130_fd_sc_hd__inv_4 fopt2251(.A (B[2]), .Y (n_448));
  sky130_fd_sc_hd__inv_2 fopt2253(.A (B[18]), .Y (n_450));
  sky130_fd_sc_hd__clkbuf_1 fopt2254(.A (B[5]), .X (n_451));
  sky130_fd_sc_hd__inv_2 fopt2255(.A (B[5]), .Y (n_452));
  sky130_fd_sc_hd__inv_2 fopt2257(.A (A[18]), .Y (n_455));
  sky130_fd_sc_hd__inv_4 fopt2258(.A (A[2]), .Y (n_456));
  sky130_fd_sc_hd__inv_2 fopt1(.A (n_461), .Y (n_460));
  sky130_fd_sc_hd__buf_1 fopt2(.A (addinc_add_7_30_n_262), .X (n_461));
  sky130_fd_sc_hd__inv_2 fopt2261(.A (B[15]), .Y (n_463));
  sky130_fd_sc_hd__inv_2 fopt2262(.A (A[15]), .Y (n_464));
  sky130_fd_sc_hd__inv_2 fopt2263(.A (A[3]), .Y (n_465));
  sky130_fd_sc_hd__inv_2 fopt2267(.A (B[6]), .Y (n_470));
  sky130_fd_sc_hd__inv_1 fopt2269(.A (n_481), .Y (n_480));
  sky130_fd_sc_hd__clkinv_1 fopt2270(.A (n_619), .Y (n_481));
  sky130_fd_sc_hd__clkinv_2 fopt2272(.A (B[17]), .Y (n_485));
  sky130_fd_sc_hd__inv_2 fopt2273(.A (A[9]), .Y (n_488));
  sky130_fd_sc_hd__clkinv_1 fopt2276(.A (n_491), .Y (n_492));
  sky130_fd_sc_hd__inv_2 fopt2278(.A (B[16]), .Y (n_496));
  sky130_fd_sc_hd__clkbuf_1 fopt2280(.A (A[5]), .X (n_499));
  sky130_fd_sc_hd__inv_2 fopt2281(.A (A[5]), .Y (n_500));
  sky130_fd_sc_hd__inv_2 fopt2283(.A (B[19]), .Y (n_502));
  sky130_fd_sc_hd__inv_2 fopt2288(.A (B[20]), .Y (n_512));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2008__2296(.A
       (addinc_add_7_30_n_90), .B (n_525), .Y (n_526));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2086__2297(.A (n_639), .B
       (n_629), .Y (n_525));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1990__2298(.A (n_525), .B
       (addinc_add_7_30_n_100), .Y (n_527));
  sky130_fd_sc_hd__nand4_1 addinc_add_7_30_g1959__2299(.A
       (addinc_add_7_30_n_90), .B (addinc_add_7_30_n_148), .C (n_525),
       .D (addinc_add_7_30_n_144), .Y (n_491));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2020__2300(.A (n_525), .B
       (addinc_add_7_30_n_111), .Y (n_529));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2041__2301(.A
       (addinc_add_7_30_n_119), .B (n_525), .Y (n_531));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2312(.A (n_542), .Y (n_543));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2080__2313(.A (n_837), .B
       (n_13), .Y (n_542));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g1988__2314(.A
       (addinc_add_7_30_n_129), .B (n_542), .Y (n_544));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1947__2315(.A1 (n_542), .A2
       (addinc_add_7_30_n_140), .B1 (addinc_add_7_30_n_121), .Y
       (n_545));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2034__2316(.A_N
       (addinc_add_7_30_n_121), .B (n_542), .Y (n_547));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2105__2318(.A (n_23), .B
       (n_548), .Y (n_549));
  sky130_fd_sc_hd__clkbuf_1 g2319(.A (Cin), .X (n_548));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2135__2326(.A (n_721), .B
       (n_718), .Y (n_555));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1892__2363(.A
       (addinc_add_7_30_n_19), .B (n_879), .Y (n_591));
  sky130_fd_sc_hd__inv_2 g2366(.A (n_592), .Y (n_593));
  sky130_fd_sc_hd__nand3_2 addinc_add_7_30_g1922__2367(.A
       (addinc_add_7_30_n_227), .B (addinc_add_7_30_n_211), .C (n_885),
       .Y (n_592));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1953__2371(.A
       (addinc_add_7_30_n_27), .B_N (n_883), .Y (n_598));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1820__2372(.A (n_886), .B
       (addinc_add_7_30_n_277), .Y (n_601));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g1958__2377(.A
       (addinc_add_7_30_n_15), .B (addinc_add_7_30_n_162), .X (n_603));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1828__2379(.A (n_887), .B
       (n_733), .Y (n_607));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g1895__2384(.A (n_608), .B
       (n_609), .X (n_610));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1903__2385(.A
       (addinc_add_7_30_n_271), .B (n_713), .Y (n_608));
  sky130_fd_sc_hd__a21oi_2 addinc_add_7_30_g1919__2386(.A1
       (addinc_add_7_30_n_226), .A2 (n_710), .B1 (n_665), .Y (n_609));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g1895__6783_dup(.A (n_609),
       .B (n_608), .X (n_612));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1865_0__2388(.A (n_616), .B
       (n_612), .Y (n_617));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g1880__2389(.A (n_712), .B
       (n_615), .X (n_616));
  sky130_fd_sc_hd__nand2_4 g2391(.A (n_591), .B (n_593), .Y (n_615));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g2291__2392(.A (n_618), .B
       (n_610), .Y (n_619));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g1880__2364_dup(.A (n_615),
       .B (n_712), .X (n_618));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1981__2393(.A
       (addinc_add_7_30_n_156), .B (addinc_add_7_30_n_7), .Y (n_620));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1925__2396(.A1 (n_620), .A2
       (n_650), .B1 (n_867), .X (n_623));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1886__2398(.A1 (n_623), .A2
       (addinc_add_7_30_n_195), .B1 (addinc_add_7_30_n_233), .X
       (n_625));
  sky130_fd_sc_hd__clkinv_2 addinc_add_7_30_g2399(.A (n_626), .Y
       (n_627));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1925__2305_dup(.A1 (n_620),
       .A2 (n_650), .B1 (n_867), .X (n_626));
  sky130_fd_sc_hd__inv_2 fopt2403(.A (B[11]), .Y (n_629));
  sky130_fd_sc_hd__inv_2 fopt2407(.A (A[8]), .Y (n_635));
  sky130_fd_sc_hd__clkbuf_1 fopt2408(.A (A[11]), .X (n_638));
  sky130_fd_sc_hd__inv_2 fopt2409(.A (A[11]), .Y (n_639));
  sky130_fd_sc_hd__inv_1 fopt2410(.A (n_555), .Y (n_641));
  sky130_fd_sc_hd__inv_2 g2414(.A (n_32), .Y (n_646));
  sky130_fd_sc_hd__inv_2 g2415(.A (n_2), .Y (n_647));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2069__2417(.A (n_646), .B
       (n_647), .Y (n_648));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2038__2418(.A
       (addinc_add_7_30_n_29), .B (n_648), .Y (n_650));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1992__2419(.A_N (n_648),
       .B (addinc_add_7_30_n_152), .Y (n_652));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1890__2424(.A1
       (addinc_add_7_30_n_258), .A2 (n_880), .B1
       (addinc_add_7_30_n_226), .Y (n_656));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1862__2425(.A
       (addinc_add_7_30_n_303), .B (n_492), .C (n_880), .Y (n_658));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1955__2427(.A (n_641), .B_N
       (n_880), .Y (n_659));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2025__2430(.A (n_662), .B
       (n_555), .Y (n_664));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2231__2432(.A (n_718), .B
       (n_721), .X (n_662));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1968__2433(.A1
       (addinc_add_7_30_n_99), .A2 (n_662), .B1 (addinc_add_7_30_n_9),
       .Y (n_665));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1909__2434(.A1 (n_641), .A2
       (addinc_add_7_30_n_225), .B1 (n_662), .Y (n_666));
  sky130_fd_sc_hd__and2_4 addinc_add_7_30_g2216__2480(.A (n_555), .B
       (addinc_add_7_30_n_100), .X (n_710));
  sky130_fd_sc_hd__nand2b_2 addinc_add_7_30_g2221__2481(.A_N (n_711),
       .B (addinc_add_7_30_n_258), .Y (n_712));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1952__2482(.A (n_710), .B
       (n_880), .Y (n_711));
  sky130_fd_sc_hd__nor2_1 addinc_add_7_30_g1930__2483(.A (n_711), .B
       (n_491), .Y (n_713));
  sky130_fd_sc_hd__inv_4 fopt2485(.A (A[12]), .Y (n_714));
  sky130_fd_sc_hd__inv_2 fopt2486(.A (B[13]), .Y (n_717));
  sky130_fd_sc_hd__inv_2 fopt2488(.A (B[14]), .Y (n_718));
  sky130_fd_sc_hd__inv_2 fopt2489(.A (A[14]), .Y (n_721));
  sky130_fd_sc_hd__inv_2 fopt2490(.A (A[13]), .Y (n_722));
  sky130_fd_sc_hd__or2_1 addinc_add_7_30_g2230__2494(.A (n_512), .B
       (n_862), .X (n_727));
  sky130_fd_sc_hd__or2_2 addinc_add_7_30_g2233__2495(.A (n_861), .B
       (n_858), .X (n_728));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2496(.A (n_732), .Y (n_730));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1888__2499(.A1 (n_834), .A2
       (n_883), .B1 (n_732), .Y (n_733));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1870__2501(.A1 (n_736), .A2
       (addinc_add_7_30_n_230), .B1 (n_623), .Y (n_737));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1900__2502(.A (n_734), .B
       (n_735), .Y (n_736));
  sky130_fd_sc_hd__nand2_4 addinc_add_7_30_g1902__2503(.A
       (addinc_add_7_30_n_261), .B (addinc_add_7_30_n_242), .Y (n_734));
  sky130_fd_sc_hd__a21oi_2 addinc_add_7_30_g1921__2504(.A1 (n_732), .A2
       (addinc_add_7_30_n_202), .B1 (addinc_add_7_30_n_215), .Y
       (n_735));
  sky130_fd_sc_hd__a21o_1 addinc_add_7_30_g1876__2505(.A1
       (addinc_add_7_30_n_246), .A2 (n_736), .B1
       (addinc_add_7_30_n_278), .X (n_739));
  sky130_fd_sc_hd__a21oi_2 addinc_add_7_30_g1878__2508(.A1 (n_736), .A2
       (addinc_add_7_30_n_247), .B1 (n_625), .Y (n_741));
  sky130_fd_sc_hd__a21oi_2 addinc_add_7_30_g1867__2509(.A1 (n_736), .A2
       (addinc_add_7_30_n_248), .B1 (addinc_add_7_30_n_275), .Y
       (n_742));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1877__2510(.A1 (n_736), .A2
       (addinc_add_7_30_n_253), .B1 (addinc_add_7_30_n_285), .Y
       (n_743));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1875__2511(.A1 (n_736), .A2
       (n_877), .B1 (n_868), .Y (n_744));
  sky130_fd_sc_hd__a21boi_1 addinc_add_7_30_g1868__2512(.A1 (n_736),
       .A2 (addinc_add_7_30_n_127), .B1_N (addinc_add_7_30_n_114), .Y
       (n_745));
  sky130_fd_sc_hd__nand2b_2 addinc_add_7_30_g2218__2513(.A_N (n_736),
       .B (addinc_add_7_30_n_328), .Y (n_746));
  sky130_fd_sc_hd__xor3_1 addinc_add_7_30_g2245__2514(.A (n_548), .B
       (n_748), .C (n_23), .X (S[0]));
  sky130_fd_sc_hd__buf_1 g2515(.A (n_747), .X (n_748));
  sky130_fd_sc_hd__buf_1 g2516(.A (B[0]), .X (n_747));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2106__2517(.A (n_548), .B
       (n_747), .Y (n_750));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2104__2518(.A (n_23), .B
       (n_747), .Y (n_751));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1956__2519(.A1 (n_881), .A2
       (n_727), .B1 (n_728), .Y (n_732));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g2023__2523(.A_N (n_881),
       .B (n_728), .Y (n_757));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2525(.A (n_42), .Y (n_758));
  sky130_fd_sc_hd__inv_2 addinc_add_7_30_g2526(.A (n_50), .Y (n_759));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2075__2529(.A (n_758), .B
       (n_759), .Y (n_760));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2037__2530(.A
       (addinc_add_7_30_n_118), .B (n_832), .Y (n_763));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g2014__2531(.A (n_760), .B
       (addinc_add_7_30_n_103), .Y (n_764));
  sky130_fd_sc_hd__inv_2 fopt2596(.A (B[8]), .Y (n_825));
  sky130_fd_sc_hd__inv_1 fopt2599(.A (n_832), .Y (n_831));
  sky130_fd_sc_hd__buf_2 fopt2600(.A (n_760), .X (n_832));
  sky130_fd_sc_hd__clkbuf_1 fopt2601(.A (addinc_add_7_30_n_261), .X
       (n_834));
  sky130_fd_sc_hd__inv_2 fopt2603(.A (A[7]), .Y (n_837));
  sky130_fd_sc_hd__clkinv_1 fopt2606(.A (n_844), .Y (n_843));
  sky130_fd_sc_hd__buf_1 fopt2607(.A (n_620), .X (n_844));
  sky130_fd_sc_hd__inv_2 fopt2609(.A (B[1]), .Y (n_846));
  sky130_fd_sc_hd__buf_1 fopt2610(.A (addinc_add_7_30_n_30), .X
       (n_849));
  sky130_fd_sc_hd__inv_2 fopt2612(.A (n_855), .Y (n_853));
  sky130_fd_sc_hd__buf_1 fopt2615(.A (n_591), .X (n_855));
  sky130_fd_sc_hd__inv_2 fopt2616(.A (A[21]), .Y (n_858));
  sky130_fd_sc_hd__buf_1 fopt2617(.A (addinc_add_7_30_n_219), .X
       (n_859));
  sky130_fd_sc_hd__inv_2 fopt2618(.A (B[21]), .Y (n_861));
  sky130_fd_sc_hd__inv_2 fopt2619(.A (A[20]), .Y (n_862));
  sky130_fd_sc_hd__inv_2 g2620(.A (n_55), .Y (n_864));
  sky130_fd_sc_hd__clkbuf_1 g2621(.A (A[26]), .X (n_865));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1973__2622(.A1 (n_866), .A2
       (n_648), .B1 (addinc_add_7_30_n_152), .Y (n_867));
  sky130_fd_sc_hd__nand2_1 addinc_add_7_30_g2076__2623(.A (n_864), .B
       (n_865), .Y (n_866));
  sky130_fd_sc_hd__o21ai_1 addinc_add_7_30_g1910__2624(.A1
       (addinc_add_7_30_n_29), .A2 (n_843), .B1 (n_866), .Y (n_868));
  sky130_fd_sc_hd__nand2b_1 addinc_add_7_30_g1994__2625(.A_N
       (addinc_add_7_30_n_29), .B (n_869), .Y (n_870));
  sky130_fd_sc_hd__buf_1 g2626(.A (n_866), .X (n_869));
  sky130_fd_sc_hd__and2_0 addinc_add_7_30_g2228__2627(.A
       (addinc_add_7_30_n_57), .B (addinc_add_7_30_n_81), .X (n_871));
  sky130_fd_sc_hd__inv_1 addinc_add_7_30_g2628(.A
       (addinc_add_7_30_n_145), .Y (n_872));
  sky130_fd_sc_hd__a21oi_1 addinc_add_7_30_g1869__2629(.A1 (n_736), .A2
       (n_873), .B1 (n_844), .Y (n_874));
  sky130_fd_sc_hd__nor2_2 addinc_add_7_30_g2010__2630(.A (n_871), .B
       (n_872), .Y (n_873));
  sky130_fd_sc_hd__nand3_1 addinc_add_7_30_g1840__2631(.A (n_619), .B
       (addinc_add_7_30_n_245), .C (n_875), .Y (n_876));
  sky130_fd_sc_hd__buf_1 g2632(.A (n_873), .X (n_875));
  sky130_fd_sc_hd__nor2b_1 addinc_add_7_30_g1950__2633(.A
       (addinc_add_7_30_n_29), .B_N (n_873), .Y (n_877));
  sky130_fd_sc_hd__nand2_2 addinc_add_7_30_g1960__2634(.A (n_650), .B
       (n_873), .Y (n_878));
  sky130_fd_sc_hd__and3_4 g2635(.A (addinc_add_7_30_n_212), .B
       (addinc_add_7_30_n_160), .C (addinc_add_7_30_n_4), .X (n_879));
  sky130_fd_sc_hd__and2_4 g2636(.A (addinc_add_7_30_n_129), .B
       (addinc_add_7_30_n_94), .X (n_880));
  sky130_fd_sc_hd__and2_1 g2637(.A (n_861), .B (n_858), .X (n_881));
  sky130_fd_sc_hd__nand2b_2 g2638(.A_N (addinc_add_7_30_n_224), .B
       (addinc_add_7_30_n_331), .Y (n_882));
  sky130_fd_sc_hd__nor2b_1 g2639(.A (n_881), .B_N
       (addinc_add_7_30_n_98), .Y (n_883));
  sky130_fd_sc_hd__nand2b_1 g2640(.A_N (n_455), .B (B[18]), .Y (n_884));
  sky130_fd_sc_hd__and4_4 g2641(.A (addinc_add_7_30_n_94), .B
       (addinc_add_7_30_n_125), .C (addinc_add_7_30_n_90), .D (n_555),
       .X (n_885));
  sky130_fd_sc_hd__nand3_1 g2642(.A (n_619), .B (n_603), .C (n_598), .Y
       (n_886));
  sky130_fd_sc_hd__nand3_1 g2643(.A (n_619), .B (n_603), .C (n_883), .Y
       (n_887));
  sky130_fd_sc_hd__ha_1 g2645(.A (addinc_add_7_30_n_179), .B (n_461),
       .COUT (UNCONNECTED), .SUM (S[1]));
endmodule

