
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Mar 26 2025 17:25:49 -03 (Mar 26 2025 20:25:49 UTC)

// Verification Directory fv/ripple_carry_adder_32bits 

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc, Cin);
  not gc (wc, n_3);
  or g23 (n_17, n_3, wc0);
  not gc0 (wc0, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc1, B);
  not gc1 (wc1, A);
  or g29 (n_21, A, wc2);
  not gc2 (wc2, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_90(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc3, Cin);
  not gc3 (wc3, n_3);
  or g23 (n_17, n_3, wc4);
  not gc4 (wc4, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc5, B);
  not gc5 (wc5, A);
  or g29 (n_21, A, wc6);
  not gc6 (wc6, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_89(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc7, Cin);
  not gc7 (wc7, n_3);
  or g23 (n_17, n_3, wc8);
  not gc8 (wc8, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc9, B);
  not gc9 (wc9, A);
  or g29 (n_21, A, wc10);
  not gc10 (wc10, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_88(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc11, Cin);
  not gc11 (wc11, n_3);
  or g23 (n_17, n_3, wc12);
  not gc12 (wc12, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc13, B);
  not gc13 (wc13, A);
  or g29 (n_21, A, wc14);
  not gc14 (wc14, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_87(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc15, Cin);
  not gc15 (wc15, n_3);
  or g23 (n_17, n_3, wc16);
  not gc16 (wc16, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc17, B);
  not gc17 (wc17, A);
  or g29 (n_21, A, wc18);
  not gc18 (wc18, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_86(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc19, Cin);
  not gc19 (wc19, n_3);
  or g23 (n_17, n_3, wc20);
  not gc20 (wc20, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc21, B);
  not gc21 (wc21, A);
  or g29 (n_21, A, wc22);
  not gc22 (wc22, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_85(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc23, Cin);
  not gc23 (wc23, n_3);
  or g23 (n_17, n_3, wc24);
  not gc24 (wc24, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc25, B);
  not gc25 (wc25, A);
  or g29 (n_21, A, wc26);
  not gc26 (wc26, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_84(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc27, Cin);
  not gc27 (wc27, n_3);
  or g23 (n_17, n_3, wc28);
  not gc28 (wc28, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc29, B);
  not gc29 (wc29, A);
  or g29 (n_21, A, wc30);
  not gc30 (wc30, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_83(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc31, Cin);
  not gc31 (wc31, n_3);
  or g23 (n_17, n_3, wc32);
  not gc32 (wc32, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc33, B);
  not gc33 (wc33, A);
  or g29 (n_21, A, wc34);
  not gc34 (wc34, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_82(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc35, Cin);
  not gc35 (wc35, n_3);
  or g23 (n_17, n_3, wc36);
  not gc36 (wc36, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc37, B);
  not gc37 (wc37, A);
  or g29 (n_21, A, wc38);
  not gc38 (wc38, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_81(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc39, Cin);
  not gc39 (wc39, n_3);
  or g23 (n_17, n_3, wc40);
  not gc40 (wc40, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc41, B);
  not gc41 (wc41, A);
  or g29 (n_21, A, wc42);
  not gc42 (wc42, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_80(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc43, Cin);
  not gc43 (wc43, n_3);
  or g23 (n_17, n_3, wc44);
  not gc44 (wc44, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc45, B);
  not gc45 (wc45, A);
  or g29 (n_21, A, wc46);
  not gc46 (wc46, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_79(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc47, Cin);
  not gc47 (wc47, n_3);
  or g23 (n_17, n_3, wc48);
  not gc48 (wc48, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc49, B);
  not gc49 (wc49, A);
  or g29 (n_21, A, wc50);
  not gc50 (wc50, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_78(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc51, Cin);
  not gc51 (wc51, n_3);
  or g23 (n_17, n_3, wc52);
  not gc52 (wc52, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc53, B);
  not gc53 (wc53, A);
  or g29 (n_21, A, wc54);
  not gc54 (wc54, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_77(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc55, Cin);
  not gc55 (wc55, n_3);
  or g23 (n_17, n_3, wc56);
  not gc56 (wc56, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc57, B);
  not gc57 (wc57, A);
  or g29 (n_21, A, wc58);
  not gc58 (wc58, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_76(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc59, Cin);
  not gc59 (wc59, n_3);
  or g23 (n_17, n_3, wc60);
  not gc60 (wc60, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc61, B);
  not gc61 (wc61, A);
  or g29 (n_21, A, wc62);
  not gc62 (wc62, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_75(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc63, Cin);
  not gc63 (wc63, n_3);
  or g23 (n_17, n_3, wc64);
  not gc64 (wc64, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc65, B);
  not gc65 (wc65, A);
  or g29 (n_21, A, wc66);
  not gc66 (wc66, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_74(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc67, Cin);
  not gc67 (wc67, n_3);
  or g23 (n_17, n_3, wc68);
  not gc68 (wc68, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc69, B);
  not gc69 (wc69, A);
  or g29 (n_21, A, wc70);
  not gc70 (wc70, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_73(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc71, Cin);
  not gc71 (wc71, n_3);
  or g23 (n_17, n_3, wc72);
  not gc72 (wc72, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc73, B);
  not gc73 (wc73, A);
  or g29 (n_21, A, wc74);
  not gc74 (wc74, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_72(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc75, Cin);
  not gc75 (wc75, n_3);
  or g23 (n_17, n_3, wc76);
  not gc76 (wc76, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc77, B);
  not gc77 (wc77, A);
  or g29 (n_21, A, wc78);
  not gc78 (wc78, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_71(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc79, Cin);
  not gc79 (wc79, n_3);
  or g23 (n_17, n_3, wc80);
  not gc80 (wc80, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc81, B);
  not gc81 (wc81, A);
  or g29 (n_21, A, wc82);
  not gc82 (wc82, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_70(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc83, Cin);
  not gc83 (wc83, n_3);
  or g23 (n_17, n_3, wc84);
  not gc84 (wc84, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc85, B);
  not gc85 (wc85, A);
  or g29 (n_21, A, wc86);
  not gc86 (wc86, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_69(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc87, Cin);
  not gc87 (wc87, n_3);
  or g23 (n_17, n_3, wc88);
  not gc88 (wc88, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc89, B);
  not gc89 (wc89, A);
  or g29 (n_21, A, wc90);
  not gc90 (wc90, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_68(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc91, Cin);
  not gc91 (wc91, n_3);
  or g23 (n_17, n_3, wc92);
  not gc92 (wc92, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc93, B);
  not gc93 (wc93, A);
  or g29 (n_21, A, wc94);
  not gc94 (wc94, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_67(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc95, Cin);
  not gc95 (wc95, n_3);
  or g23 (n_17, n_3, wc96);
  not gc96 (wc96, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc97, B);
  not gc97 (wc97, A);
  or g29 (n_21, A, wc98);
  not gc98 (wc98, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_66(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc99, Cin);
  not gc99 (wc99, n_3);
  or g23 (n_17, n_3, wc100);
  not gc100 (wc100, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc101, B);
  not gc101 (wc101, A);
  or g29 (n_21, A, wc102);
  not gc102 (wc102, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_65(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc103, Cin);
  not gc103 (wc103, n_3);
  or g23 (n_17, n_3, wc104);
  not gc104 (wc104, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc105, B);
  not gc105 (wc105, A);
  or g29 (n_21, A, wc106);
  not gc106 (wc106, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_64(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc107, Cin);
  not gc107 (wc107, n_3);
  or g23 (n_17, n_3, wc108);
  not gc108 (wc108, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc109, B);
  not gc109 (wc109, A);
  or g29 (n_21, A, wc110);
  not gc110 (wc110, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_63(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc111, Cin);
  not gc111 (wc111, n_3);
  or g23 (n_17, n_3, wc112);
  not gc112 (wc112, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc113, B);
  not gc113 (wc113, A);
  or g29 (n_21, A, wc114);
  not gc114 (wc114, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_62(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc115, Cin);
  not gc115 (wc115, n_3);
  or g23 (n_17, n_3, wc116);
  not gc116 (wc116, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc117, B);
  not gc117 (wc117, A);
  or g29 (n_21, A, wc118);
  not gc118 (wc118, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module full_adder_61(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_14, n_16, n_17, n_18, n_19, n_20, n_21;
  or g18 (n_14, B, Cin);
  or g22 (n_16, wc119, Cin);
  not gc119 (wc119, n_3);
  or g23 (n_17, n_3, wc120);
  not gc120 (wc120, Cin);
  nand g24 (S, n_16, n_17);
  nand g25 (n_18, n_14, A);
  nand g26 (n_19, B, Cin);
  nand g27 (Cout, n_18, n_19);
  or g28 (n_20, wc121, B);
  not gc121 (wc121, A);
  or g29 (n_21, A, wc122);
  not gc122 (wc122, B);
  nand g30 (n_3, n_20, n_21);
endmodule

module ripple_carry_adder_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire [31:0] carry;
  half_adder HA(.A (A[0]), .B (B[0]), .S (S[0]), .Cout (carry[0]));
  full_adder \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_90 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_89 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_88 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_87 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_86 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_85 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (carry[7]));
  full_adder_84 \full_adder_loop[8].FA (.A (A[8]), .B (B[8]), .Cin
       (carry[7]), .S (S[8]), .Cout (carry[8]));
  full_adder_83 \full_adder_loop[9].FA (.A (A[9]), .B (B[9]), .Cin
       (carry[8]), .S (S[9]), .Cout (carry[9]));
  full_adder_82 \full_adder_loop[10].FA (.A (A[10]), .B (B[10]), .Cin
       (carry[9]), .S (S[10]), .Cout (carry[10]));
  full_adder_81 \full_adder_loop[11].FA (.A (A[11]), .B (B[11]), .Cin
       (carry[10]), .S (S[11]), .Cout (carry[11]));
  full_adder_80 \full_adder_loop[12].FA (.A (A[12]), .B (B[12]), .Cin
       (carry[11]), .S (S[12]), .Cout (carry[12]));
  full_adder_79 \full_adder_loop[13].FA (.A (A[13]), .B (B[13]), .Cin
       (carry[12]), .S (S[13]), .Cout (carry[13]));
  full_adder_78 \full_adder_loop[14].FA (.A (A[14]), .B (B[14]), .Cin
       (carry[13]), .S (S[14]), .Cout (carry[14]));
  full_adder_77 \full_adder_loop[15].FA (.A (A[15]), .B (B[15]), .Cin
       (carry[14]), .S (S[15]), .Cout (carry[15]));
  full_adder_76 \full_adder_loop[16].FA (.A (A[16]), .B (B[16]), .Cin
       (carry[15]), .S (S[16]), .Cout (carry[16]));
  full_adder_75 \full_adder_loop[17].FA (.A (A[17]), .B (B[17]), .Cin
       (carry[16]), .S (S[17]), .Cout (carry[17]));
  full_adder_74 \full_adder_loop[18].FA (.A (A[18]), .B (B[18]), .Cin
       (carry[17]), .S (S[18]), .Cout (carry[18]));
  full_adder_73 \full_adder_loop[19].FA (.A (A[19]), .B (B[19]), .Cin
       (carry[18]), .S (S[19]), .Cout (carry[19]));
  full_adder_72 \full_adder_loop[20].FA (.A (A[20]), .B (B[20]), .Cin
       (carry[19]), .S (S[20]), .Cout (carry[20]));
  full_adder_71 \full_adder_loop[21].FA (.A (A[21]), .B (B[21]), .Cin
       (carry[20]), .S (S[21]), .Cout (carry[21]));
  full_adder_70 \full_adder_loop[22].FA (.A (A[22]), .B (B[22]), .Cin
       (carry[21]), .S (S[22]), .Cout (carry[22]));
  full_adder_69 \full_adder_loop[23].FA (.A (A[23]), .B (B[23]), .Cin
       (carry[22]), .S (S[23]), .Cout (carry[23]));
  full_adder_68 \full_adder_loop[24].FA (.A (A[24]), .B (B[24]), .Cin
       (carry[23]), .S (S[24]), .Cout (carry[24]));
  full_adder_67 \full_adder_loop[25].FA (.A (A[25]), .B (B[25]), .Cin
       (carry[24]), .S (S[25]), .Cout (carry[25]));
  full_adder_66 \full_adder_loop[26].FA (.A (A[26]), .B (B[26]), .Cin
       (carry[25]), .S (S[26]), .Cout (carry[26]));
  full_adder_65 \full_adder_loop[27].FA (.A (A[27]), .B (B[27]), .Cin
       (carry[26]), .S (S[27]), .Cout (carry[27]));
  full_adder_64 \full_adder_loop[28].FA (.A (A[28]), .B (B[28]), .Cin
       (carry[27]), .S (S[28]), .Cout (carry[28]));
  full_adder_63 \full_adder_loop[29].FA (.A (A[29]), .B (B[29]), .Cin
       (carry[28]), .S (S[29]), .Cout (carry[29]));
  full_adder_62 \full_adder_loop[30].FA (.A (A[30]), .B (B[30]), .Cin
       (carry[29]), .S (S[30]), .Cout (carry[30]));
  full_adder_61 \full_adder_loop[31].FA (.A (A[31]), .B (B[31]), .Cin
       (carry[30]), .S (S[31]), .Cout (Cout));
endmodule

