
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr  7 2025 18:17:43 -03 (Apr  7 2025 21:17:43 UTC)

// Verification Directory fv/carry_select_adder_46814_32bits 

module full_adder_4(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nor2_1 g29__2398(.A (n_2), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__inv_2 g31(.A (B), .Y (n_2));
  sky130_fd_sc_hd__inv_2 g33(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xor2_1 g2__5107(.A (n_2), .B (n_1), .X (S));
endmodule

module full_adder_227(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  sky130_fd_sc_hd__nand2_1 g61__6260(.A (n_7), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g62__4319(.A (Cin), .B (n_6), .X (S));
  sky130_fd_sc_hd__nand2_1 g63__8428(.A (n_5), .B (Cin), .Y (n_7));
  sky130_fd_sc_hd__xor2_1 g64__5526(.A (n_0), .B (n_1), .X (n_6));
  sky130_fd_sc_hd__nand2_1 g65__6783(.A (n_3), .B (n_2), .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g66__3680(.A (n_0), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g68(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g69(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g71(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g72(.A (B), .Y (n_2));
endmodule

module full_adder_226(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g60__1617(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g61__2802(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g62__1705(.A (Cin), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g63__5122(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g65__8246(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__or2_0 g2__7098(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_225(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g57__6131(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__1881(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5115(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__7482(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__4733(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__6161(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_224(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  sky130_fd_sc_hd__xor2_1 g58__9945(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__ha_1 g60__2346(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__1666(.A (A), .B (B), .X (n_0));
  sky130_fd_sc_hd__a21o_1 g2(.A1 (Cin), .A2 (n_0), .B1 (n_1), .X
       (Cout));
endmodule

module full_adder_223(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_1 g57__7410(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__6417(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5477(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__2398(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__5107(.A (A), .B (B), .X (n_0));
endmodule

module ripple_carry_adder_WIDTH6(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  wire UNCONNECTED_HIER_Z;
  full_adder_4 F1A(.A (A[0]), .B (B[0]), .Cin (UNCONNECTED_HIER_Z), .S
       (S[0]), .Cout (carry[0]));
  full_adder_227 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_226 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_225 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_224 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_223 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_46_233(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nand2_1 g40__6260(.A (n_1), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g42(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g44(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g2__4319(.A (n_1), .B (n_2), .Y (S));
endmodule

module full_adder_202(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  sky130_fd_sc_hd__nand2_1 g60__8428(.A (n_7), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g61__5526(.A (Cin), .B (n_6), .X (S));
  sky130_fd_sc_hd__nand2_1 g62__6783(.A (Cin), .B (n_5), .Y (n_7));
  sky130_fd_sc_hd__xor2_1 g63__3680(.A (n_0), .B (n_1), .X (n_6));
  sky130_fd_sc_hd__nand2_1 g64__1617(.A (n_3), .B (n_2), .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g65__2802(.A (n_0), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g67(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g68(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g70(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__inv_2 g71(.A (B), .Y (n_2));
endmodule

module full_adder_201(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g57__1705(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__5122(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__8246(.A (Cin), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__7098(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g62__6131(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__or2_0 g2__1881(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_200(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g57__5115(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__7482(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__4733(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__6161(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__9315(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__9945(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_199(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  sky130_fd_sc_hd__a21o_1 g57__2883(.A1 (Cin), .A2 (n_0), .B1 (n_1), .X
       (Cout));
  sky130_fd_sc_hd__xor2_1 g58__2346(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__ha_1 g59__1666(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g60__7410(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_198(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_1 g57__6417(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__5477(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__2398(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__5107(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__6260(.A (A), .B (B), .X (n_0));
endmodule

module ripple_carry_adder_WIDTH6_1(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  wire UNCONNECTED_HIER_Z0;
  full_adder_46_233 F1A(.A (A[0]), .B (B[0]), .Cin
       (UNCONNECTED_HIER_Z0), .S (S[0]), .Cout (carry[0]));
  full_adder_202 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_201 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_200 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_199 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_198 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_4_232(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nor2_1 g29__4319(.A (n_1), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__inv_2 g31(.A (B), .Y (n_2));
  sky130_fd_sc_hd__inv_2 g33(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xor2_1 g2__8428(.A (n_2), .B (n_1), .X (S));
endmodule

module full_adder_222(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6, n_7;
  sky130_fd_sc_hd__nand2_2 g95__5526(.A (n_7), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g96__6783(.A (Cin), .B (n_6), .X (S));
  sky130_fd_sc_hd__nand2_2 g97__3680(.A (Cin), .B (n_5), .Y (n_7));
  sky130_fd_sc_hd__xor2_1 g98__1617(.A (B), .B (A), .X (n_6));
  sky130_fd_sc_hd__nand2_1 g99__2802(.A (n_3), .B (n_2), .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g100__1705(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g103(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g106(.A (B), .Y (n_2));
endmodule

module full_adder_221(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g60__5122(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g61__8246(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_2 g62__7098(.A (Cin), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g63__6131(.A (n_1), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g65__1881(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g69(.A (B), .X (n_1));
  sky130_fd_sc_hd__or2_1 g2__5115(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_220(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g60__7482(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g61__4733(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g62__6161(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g63__9315(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g64__9945(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g65__2883(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_219(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g57__2346(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__1666(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__7410(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__6417(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__5477(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__2398(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_218(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g57__5107(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__6260(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__4319(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__8428(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__5526(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__6783(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_217(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_2 g57__3680(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__1617(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__2802(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__1705(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__5122(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_216(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_2 g57__8246(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__7098(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__6131(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__1881(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__5115(.A (A), .B (B), .X (n_0));
endmodule

module ripple_carry_adder_WIDTH8(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z1;
  full_adder_4_232 F1A(.A (A[0]), .B (B[0]), .Cin
       (UNCONNECTED_HIER_Z1), .S (S[0]), .Cout (carry[0]));
  full_adder_222 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_221 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_220 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_219 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_218 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_217 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_216 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_46_234(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nand2_1 g40__7482(.A (n_1), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g42(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g44(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g2__4733(.A (n_1), .B (n_2), .Y (S));
endmodule

module full_adder_197(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  sky130_fd_sc_hd__o21ai_2 g87__6161(.A1 (n_2), .A2 (n_0), .B1 (n_1),
       .Y (Cout));
  sky130_fd_sc_hd__nor2_1 g90__9945(.A (A), .B (B), .Y (n_2));
  sky130_fd_sc_hd__nand2_1 g91__2883(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g92(.A (Cin), .Y (n_0));
  sky130_fd_sc_hd__xnor3_1 g2(.A (n_0), .B (B), .C (A), .X (S));
endmodule

module full_adder_196(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g60__1666(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g61__7410(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g62__6417(.A (Cin), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g63__5477(.A (n_1), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g65__2398(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g69(.A (B), .X (n_1));
  sky130_fd_sc_hd__or2_0 g2__5107(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_195(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_4, n_11;
  sky130_fd_sc_hd__nand2_2 g60__6260(.A (n_11), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g61__4319(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__xor2_1 g63__5526(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g65__3680(.A (B), .B (A), .Y (n_2));
  sky130_fd_sc_hd__o21ai_2 g2(.A1 (A), .A2 (B), .B1 (Cin), .Y (n_11));
endmodule

module full_adder_194(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g57__1617(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g59__2802(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__1705(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__5122(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__8246(.A (B), .B (A), .Y (n_2));
  sky130_fd_sc_hd__xor2_1 g68__70(.A (n_4), .B (Cin), .X (S));
endmodule

module full_adder_193(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g57__6131(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__1881(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5115(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__7482(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__4733(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__6161(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_192(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g57__9315(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__9945(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_2 g59__2883(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__2346(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__1666(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__7410(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_191(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_2 g57__6417(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__5477(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__2398(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__5107(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__6260(.A (A), .B (B), .X (n_0));
endmodule

module ripple_carry_adder_WIDTH8_1(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z2;
  full_adder_46_234 F1A(.A (A[0]), .B (B[0]), .Cin
       (UNCONNECTED_HIER_Z2), .S (S[0]), .Cout (carry[0]));
  full_adder_197 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_196 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_195 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_194 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_193 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_192 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_191 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_4_231(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED, n_1, n_2;
  sky130_fd_sc_hd__nor2_2 g34__4319(.A (n_1), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__inv_2 g36(.A (B), .Y (n_2));
  sky130_fd_sc_hd__inv_2 g38(.A (A), .Y (n_1));
  sky130_fd_sc_hd__ha_1 g40__8428(.A (n_2), .B (n_1), .COUT
       (UNCONNECTED), .SUM (S));
endmodule

module full_adder_215(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_4 g192__5526(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g193__6783(.A (n_4), .B (n_7), .X (S));
  sky130_fd_sc_hd__nand2_4 g194__3680(.A (n_6), .B (Cin), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g195__1617(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_2 g196__2802(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_4 g197__1705(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__buf_2 g198(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g200(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_2 g201(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g203(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_2 g204(.A (B), .Y (n_2));
endmodule

module full_adder_214(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_4 g122__5122(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__8246(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__7098(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g125__6131(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_2 g126__1881(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_4 g127__5115(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__clkbuf_1 g128(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g130(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g131(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g133(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g134(.A (B), .Y (n_2));
endmodule

module full_adder_213(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_4, n_5, n_7, n_8, n_14;
  sky130_fd_sc_hd__nand2_4 g122__7482(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__4733(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__6161(.A (Cin), .B (n_14), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g125__9315(.A (n_0), .B (A), .X (n_7));
  sky130_fd_sc_hd__nand2_2 g127__2883(.A (B), .B (A), .Y (n_5));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__clkbuf_1 g132(.A (B), .X (n_0));
  sky130_fd_sc_hd__or2_4 g2(.A (A), .B (B), .X (n_14));
endmodule

module full_adder_212(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__2346(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__1666(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__7410(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__6417(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__5477(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__2398(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
endmodule

module full_adder_211(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__5107(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__6260(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__4319(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__8428(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_2 g126__5526(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__6783(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
endmodule

module full_adder_210(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__3680(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__1617(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__2802(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__1705(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_2 g126__5122(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__8246(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
endmodule

module full_adder_209(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__7098(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__6131(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__1881(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__5115(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_2 g126__7482(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__4733(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
endmodule

module full_adder_208(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__6161(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__9315(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__9945(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__2883(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_2 g126__2346(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__1666(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
endmodule

module full_adder_207(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__7410(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__6417(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__5477(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__2398(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_2 g126__5107(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__6260(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
endmodule

module full_adder_206(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__4319(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__8428(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__5526(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__6783(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_2 g126__3680(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__1617(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
endmodule

module full_adder_205(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_4 g123__2802(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__mux2i_1 g124__1705(.A0 (n_1), .A1 (n_0), .S (n_4),
       .Y (S));
  sky130_fd_sc_hd__nand2_4 g125__5122(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g126__8246(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_4 g127__7098(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_8 g128__6131(.A (B), .B (A), .Y (n_2));
  sky130_fd_sc_hd__inv_2 g129(.A (n_0), .Y (n_1));
  sky130_fd_sc_hd__buf_2 g130(.A (Cin), .X (n_0));
endmodule

module full_adder_204(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2_4 g123__1881(.A (n_3), .B (n_0), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g124__5115(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_4 g125__7482(.A (Cin), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__xor2_1 g126__4733(.A (B), .B (A), .X (n_2));
  sky130_fd_sc_hd__or2_4 g127__6161(.A (A), .B (B), .X (n_1));
  sky130_fd_sc_hd__nand2_4 g128__9315(.A (B), .B (A), .Y (n_0));
endmodule

module full_adder_203(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_10;
  sky130_fd_sc_hd__nand2_1 g117__9945(.A (n_4), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g119__2346(.A (Cin), .B (n_3), .Y (n_4));
  sky130_fd_sc_hd__or2_0 g122__1666(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g123__7410(.A (B), .B (A), .Y (n_2));
  sky130_fd_sc_hd__xnor2_2 g2__6417(.A (B), .B (A), .Y (n_0));
  sky130_fd_sc_hd__o21ai_2 g13(.A1 (n_0), .A2 (Cin), .B1 (n_10), .Y
       (S));
  sky130_fd_sc_hd__nand2_1 g14(.A (Cin), .B (n_0), .Y (n_10));
endmodule

module ripple_carry_adder_WIDTH14(A, B, Cin, S, Cout);
  input [13:0] A, B;
  input Cin;
  output [13:0] S;
  output Cout;
  wire [13:0] A, B;
  wire Cin;
  wire [13:0] S;
  wire Cout;
  wire [13:0] carry;
  wire UNCONNECTED_HIER_Z3;
  full_adder_4_231 F1A(.A (A[0]), .B (B[0]), .Cin
       (UNCONNECTED_HIER_Z3), .S (S[0]), .Cout (carry[0]));
  full_adder_215 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_214 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_213 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_212 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_211 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_210 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_209 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (carry[7]));
  full_adder_208 \full_adder_loop[8].FA (.A (A[8]), .B (B[8]), .Cin
       (carry[7]), .S (S[8]), .Cout (carry[8]));
  full_adder_207 \full_adder_loop[9].FA (.A (A[9]), .B (B[9]), .Cin
       (carry[8]), .S (S[9]), .Cout (carry[9]));
  full_adder_206 \full_adder_loop[10].FA (.A (A[10]), .B (B[10]), .Cin
       (carry[9]), .S (S[10]), .Cout (carry[10]));
  full_adder_205 \full_adder_loop[11].FA (.A (A[11]), .B (B[11]), .Cin
       (carry[10]), .S (S[11]), .Cout (carry[11]));
  full_adder_204 \full_adder_loop[12].FA (.A (A[12]), .B (B[12]), .Cin
       (carry[11]), .S (S[12]), .Cout (carry[12]));
  full_adder_203 \full_adder_loop[13].FA (.A (A[13]), .B (B[13]), .Cin
       (carry[12]), .S (S[13]), .Cout (Cout));
endmodule

module full_adder_46(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nand2_4 g56__5477(.A (n_1), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__clkinv_2 g58(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_2 g60(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g2__2398(.A (n_1), .B (n_2), .Y (S));
endmodule

module full_adder_190(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  sky130_fd_sc_hd__nand2_4 g179__5107(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g180__6260(.A (Cin), .B (n_7), .X (S));
  sky130_fd_sc_hd__nand2_4 g181__4319(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g182__8428(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_2 g183__5526(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_4 g184__6783(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__inv_2 g187(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_2 g188(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g190(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_2 g191(.A (B), .Y (n_2));
endmodule

module full_adder_189(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_4 g122__3680(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__1617(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__2802(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g125__1705(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_2 g126__5122(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_4 g127__8246(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g130(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g131(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g133(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g134(.A (B), .Y (n_2));
endmodule

module full_adder_188(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__7098(.A (n_6), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__6131(.A (n_5), .B (n_3), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__1881(.A (Cin), .B (n_0), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__5115(.A (n_1), .B (A), .X (n_5));
  sky130_fd_sc_hd__nand2_1 g127__7482(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_3));
  sky130_fd_sc_hd__clkbuf_1 g132(.A (B), .X (n_1));
  sky130_fd_sc_hd__or2_4 g2__4733(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_187(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__6161(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__9315(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__9945(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__2883(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__2346(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__1666(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
endmodule

module full_adder_186(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__7410(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__6417(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__5477(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__2398(.A (n_0), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__5107(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__6260(.A (n_0), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__buf_1 g130(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g132(.A (B), .X (n_0));
endmodule

module full_adder_185(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__4319(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__8428(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__5526(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__6783(.A (n_0), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__3680(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__1617(.A (n_0), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g130(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g132(.A (B), .X (n_0));
endmodule

module full_adder_184(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__2802(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__1705(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__5122(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__8246(.A (n_0), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__7098(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__6131(.A (n_0), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_1 g128(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g130(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g132(.A (B), .X (n_0));
endmodule

module full_adder_183(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__1881(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__5115(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__7482(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__4733(.A (n_0), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__6161(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__9315(.A (n_0), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g130(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g132(.A (B), .X (n_0));
endmodule

module full_adder_182(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__9945(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__2883(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__2346(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__1666(.A (n_0), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__7410(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__6417(.A (n_0), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g130(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g132(.A (B), .X (n_0));
endmodule

module full_adder_181(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__5477(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__2398(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__5107(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__6260(.A (n_0), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__4319(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__8428(.A (n_0), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__dlymetal6s2s_1 g128(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__buf_1 g129(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g130(.A (B), .X (n_0));
endmodule

module full_adder_180(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g123__5526(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__mux2i_1 g124__6783(.A0 (n_2), .A1 (n_1), .S (n_5),
       .Y (S));
  sky130_fd_sc_hd__nand2_4 g125__3680(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g126__1617(.A (B), .B (n_0), .X (n_5));
  sky130_fd_sc_hd__or2_4 g127__2802(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_8 g128__1705(.A (B), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g129(.A (n_1), .Y (n_2));
  sky130_fd_sc_hd__buf_2 g130(.A (Cin), .X (n_1));
  sky130_fd_sc_hd__buf_1 g131(.A (A), .X (n_0));
endmodule

module full_adder_179(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2_4 g123__5122(.A (n_3), .B (n_0), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g124__8246(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_4 g125__7098(.A (Cin), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__xor2_1 g126__6131(.A (B), .B (A), .X (n_2));
  sky130_fd_sc_hd__or2_4 g127__1881(.A (A), .B (B), .X (n_1));
  sky130_fd_sc_hd__nand2_4 g128__5115(.A (B), .B (A), .Y (n_0));
endmodule

module full_adder_178(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_10, n_11, n_12, n_13;
  sky130_fd_sc_hd__nand2_1 g117__7482(.A (n_4), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g119__6161(.A (n_3), .B (Cin), .Y (n_4));
  sky130_fd_sc_hd__or2_0 g122__9315(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g123__9945(.A (B), .B (A), .Y (n_2));
  sky130_fd_sc_hd__xnor2_1 g2__2883(.A (B), .B (A), .Y (n_0));
  sky130_fd_sc_hd__nand2_2 g13(.A (n_12), .B (n_13), .Y (S));
  sky130_fd_sc_hd__nand2_2 g15(.A (n_10), .B (n_11), .Y (n_12));
  sky130_fd_sc_hd__clkinv_2 g16(.A (Cin), .Y (n_10));
  sky130_fd_sc_hd__inv_1 g17(.A (n_0), .Y (n_11));
  sky130_fd_sc_hd__nand2_1 g14(.A (n_0), .B (Cin), .Y (n_13));
endmodule

module ripple_carry_adder_WIDTH14_1(A, B, Cin, S, Cout);
  input [13:0] A, B;
  input Cin;
  output [13:0] S;
  output Cout;
  wire [13:0] A, B;
  wire Cin;
  wire [13:0] S;
  wire Cout;
  wire [13:0] carry;
  wire UNCONNECTED_HIER_Z4;
  full_adder_46 F1A(.A (A[0]), .B (B[0]), .Cin (UNCONNECTED_HIER_Z4),
       .S (S[0]), .Cout (carry[0]));
  full_adder_190 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_189 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_188 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_187 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_186 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_185 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_184 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (carry[7]));
  full_adder_183 \full_adder_loop[8].FA (.A (A[8]), .B (B[8]), .Cin
       (carry[7]), .S (S[8]), .Cout (carry[8]));
  full_adder_182 \full_adder_loop[9].FA (.A (A[9]), .B (B[9]), .Cin
       (carry[8]), .S (S[9]), .Cout (carry[9]));
  full_adder_181 \full_adder_loop[10].FA (.A (A[10]), .B (B[10]), .Cin
       (carry[9]), .S (S[10]), .Cout (carry[10]));
  full_adder_180 \full_adder_loop[11].FA (.A (A[11]), .B (B[11]), .Cin
       (carry[10]), .S (S[11]), .Cout (carry[11]));
  full_adder_179 \full_adder_loop[12].FA (.A (A[12]), .B (B[12]), .Cin
       (carry[11]), .S (S[12]), .Cout (carry[12]));
  full_adder_178 \full_adder_loop[13].FA (.A (A[13]), .B (B[13]), .Cin
       (carry[12]), .S (S[13]), .Cout (Cout));
endmodule

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__o21ai_1 g95__2346(.A1 (n_0), .A2 (n_2), .B1 (n_1),
       .Y (Cout));
  sky130_fd_sc_hd__xnor2_1 g96__1666(.A (n_0), .B (n_3), .Y (S));
  sky130_fd_sc_hd__xor2_1 g97__7410(.A (B), .B (A), .X (n_3));
  sky130_fd_sc_hd__nor2_1 g98__6417(.A (A), .B (B), .Y (n_2));
  sky130_fd_sc_hd__nand2_1 g99__5477(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g101(.A (Cin), .Y (n_0));
endmodule

module full_adder_230(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_4, n_6, n_7, n_13;
  sky130_fd_sc_hd__nand2_1 g60__2398(.A (n_7), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g61__5107(.A (Cin), .B (n_6), .X (S));
  sky130_fd_sc_hd__nand2_1 g62__6260(.A (Cin), .B (n_13), .Y (n_7));
  sky130_fd_sc_hd__xor2_1 g63__4319(.A (B), .B (A), .X (n_6));
  sky130_fd_sc_hd__nand2_1 g65__5526(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__or2_0 g2(.A (A), .B (B), .X (n_13));
endmodule

module full_adder_229(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  sky130_fd_sc_hd__xor2_1 g58__3680(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__ha_1 g60__2802(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g2__1705(.A (B), .B (A), .X (n_0));
  sky130_fd_sc_hd__a21o_1 g2(.A1 (Cin), .A2 (n_0), .B1 (n_1), .X
       (Cout));
endmodule

module full_adder_228(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  sky130_fd_sc_hd__a21o_1 g57__5122(.A1 (Cin), .A2 (n_0), .B1 (n_1), .X
       (Cout));
  sky130_fd_sc_hd__xor2_1 g58__8246(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__ha_1 g59__7098(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g60__6131(.A (B), .B (A), .X (n_0));
endmodule

module ripple_carry_adder_WIDTH4(A, B, Cin, S, Cout);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output Cout;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire Cout;
  wire [3:0] carry;
  full_adder F1A(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (carry[0]));
  full_adder_230 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_229 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_228 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (Cout));
endmodule

module carry_select_adder_46814_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire [31:0] S0;
  wire [3:0] C0;
  wire [31:0] S1;
  wire [3:0] C1;
  wire [3:0] C_mid;
  wire UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10,
       n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_16, n_18, n_27, n_28, n_29;
  wire n_31, n_32, n_36, n_40, n_41, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_51, n_52, n_53, n_54;
  wire n_55, n_58, n_60, n_61, n_62, n_63, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_73, n_74, n_75, n_76;
  wire n_78, n_81, n_82, n_83, n_87, n_93, n_198, n_200;
  wire n_201, n_202, n_203, n_204, n_205, n_208, n_209, n_212;
  wire n_214, n_216, n_217, n_218, n_220, n_221, n_233, n_234;
  wire n_235, n_236, n_239, n_240;
  ripple_carry_adder_WIDTH6 \CSA_BLOCKS[1].RCA_C0 (.A ({A[9:6], n_93,
       A[4]}), .B ({B[9:6], n_87, B[4]}), .Cin (UNCONNECTED_HIER_Z5),
       .S (S0[9:4]), .Cout (C0[1]));
  ripple_carry_adder_WIDTH6_1 \CSA_BLOCKS[1].RCA_C1 (.A ({A[9:6], n_93,
       n_218}), .B ({B[9:6], n_87, n_214}), .Cin (UNCONNECTED_HIER_Z6),
       .S (S1[9:4]), .Cout (C1[1]));
  ripple_carry_adder_WIDTH8 \CSA_BLOCKS[2].RCA_C0 (.A ({A[17], n_83,
       n_82, n_81, A[13], n_221, A[11], n_78}), .B ({B[17], n_76, n_75,
       n_74, B[13], n_73, B[11:10]}), .Cin (UNCONNECTED_HIER_Z7), .S
       (S0[17:10]), .Cout (C0[2]));
  ripple_carry_adder_WIDTH8_1 \CSA_BLOCKS[2].RCA_C1 (.A ({A[17], n_83,
       n_82, n_81, n_32, n_220, A[11], n_78}), .B ({B[17], n_76, n_75,
       n_74, n_41, n_73, B[11], n_212}), .Cin (UNCONNECTED_HIER_Z8), .S
       (S1[17:10]), .Cout (C1[2]));
  ripple_carry_adder_WIDTH14 \CSA_BLOCKS[3].RCA_C0 (.A ({n_69, n_68,
       n_67, n_66, n_65, n_64, n_63, n_62, n_61, n_60, n_217, n_58,
       n_205, n_203}), .B ({n_55, n_54, n_53, n_52, n_51, n_50, n_49,
       n_48, n_47, n_46, n_45, n_44, n_201, n_209}), .Cin
       (UNCONNECTED_HIER_Z9), .S (S0[31:18]), .Cout (C0[3]));
  ripple_carry_adder_WIDTH14_1 \CSA_BLOCKS[3].RCA_C1 (.A ({n_69, n_68,
       n_67, n_66, n_65, n_64, n_63, n_62, n_61, n_60, n_216, n_58,
       n_204, n_202}), .B ({n_55, n_54, n_53, n_52, n_51, n_50, n_49,
       n_48, n_47, n_46, n_45, n_44, n_200, n_208}), .Cin
       (UNCONNECTED_HIER_Z10), .S (S1[31:18]), .Cout (C1[3]));
  ripple_carry_adder_WIDTH4 RCA_LSB(.A (A[3:0]), .B (B[3:0]), .Cin
       (n_40), .S (S[3:0]), .Cout (C_mid[0]));
  sky130_fd_sc_hd__inv_1 g291(.A (n_36), .Y (n_41));
  sky130_fd_sc_hd__clkinv_1 g278(.A (n_28), .Y (n_40));
  sky130_fd_sc_hd__inv_1 g306(.A (n_27), .Y (n_61));
  sky130_fd_sc_hd__inv_1 g351(.A (n_31), .Y (n_32));
  sky130_fd_sc_hd__inv_2 g337(.A (n_18), .Y (n_60));
  sky130_fd_sc_hd__inv_2 g299(.A (n_29), .Y (n_81));
  sky130_fd_sc_hd__inv_2 g304(.A (n_16), .Y (n_46));
  sky130_fd_sc_hd__clkinv_1 g300(.A (A[14]), .Y (n_29));
  sky130_fd_sc_hd__inv_2 g279(.A (Cin), .Y (n_28));
  sky130_fd_sc_hd__clkinv_1 g307(.A (A[23]), .Y (n_27));
  sky130_fd_sc_hd__buf_1 g347(.A (B[12]), .X (n_73));
  sky130_fd_sc_hd__clkbuf_1 g336(.A (A[24]), .X (n_62));
  sky130_fd_sc_hd__buf_1 g335(.A (A[30]), .X (n_68));
  sky130_fd_sc_hd__clkbuf_1 g324(.A (B[5]), .X (n_87));
  sky130_fd_sc_hd__clkbuf_1 g312(.A (B[20]), .X (n_44));
  sky130_fd_sc_hd__clkbuf_1 g308(.A (A[10]), .X (n_78));
  sky130_fd_sc_hd__buf_1 g287(.A (A[31]), .X (n_69));
  sky130_fd_sc_hd__buf_1 g350(.A (A[29]), .X (n_67));
  sky130_fd_sc_hd__clkbuf_1 g298(.A (B[15]), .X (n_75));
  sky130_fd_sc_hd__clkbuf_1 g344(.A (A[25]), .X (n_63));
  sky130_fd_sc_hd__clkbuf_1 g315(.A (B[31]), .X (n_55));
  sky130_fd_sc_hd__inv_2 g293(.A (B[13]), .Y (n_36));
  sky130_fd_sc_hd__inv_2 g338(.A (A[22]), .Y (n_18));
  sky130_fd_sc_hd__inv_2 g305(.A (B[22]), .Y (n_16));
  sky130_fd_sc_hd__clkbuf_1 g334(.A (A[20]), .X (n_58));
  sky130_fd_sc_hd__clkbuf_1 g295(.A (B[28]), .X (n_52));
  sky130_fd_sc_hd__clkbuf_1 g345(.A (B[27]), .X (n_51));
  sky130_fd_sc_hd__clkbuf_1 g355(.A (A[26]), .X (n_64));
  sky130_fd_sc_hd__clkbuf_1 g354(.A (A[16]), .X (n_83));
  sky130_fd_sc_hd__buf_1 g326(.A (B[30]), .X (n_54));
  sky130_fd_sc_hd__clkbuf_1 g316(.A (B[26]), .X (n_50));
  sky130_fd_sc_hd__buf_1 g328(.A (B[29]), .X (n_53));
  sky130_fd_sc_hd__clkbuf_1 g349(.A (B[16]), .X (n_76));
  sky130_fd_sc_hd__clkbuf_1 g317(.A (B[25]), .X (n_49));
  sky130_fd_sc_hd__buf_1 g303(.A (B[21]), .X (n_45));
  sky130_fd_sc_hd__clkbuf_1 g318(.A (B[23]), .X (n_47));
  sky130_fd_sc_hd__clkbuf_1 g297(.A (B[24]), .X (n_48));
  sky130_fd_sc_hd__clkbuf_1 g301(.A (A[28]), .X (n_66));
  sky130_fd_sc_hd__inv_2 g353(.A (A[13]), .Y (n_31));
  sky130_fd_sc_hd__clkbuf_1 g311(.A (A[5]), .X (n_93));
  sky130_fd_sc_hd__clkbuf_1 g290(.A (B[14]), .X (n_74));
  sky130_fd_sc_hd__clkbuf_1 g331(.A (A[15]), .X (n_82));
  sky130_fd_sc_hd__clkbuf_1 g342(.A (A[27]), .X (n_65));
  sky130_fd_sc_hd__a22o_2 g834__1881(.A1 (n_239), .A2 (S0[18]), .B1
       (n_240), .B2 (S1[18]), .X (S[18]));
  sky130_fd_sc_hd__nand2_4 g835__5115(.A (n_10), .B (n_13), .Y (S[30]));
  sky130_fd_sc_hd__a22o_4 g836__7482(.A1 (n_239), .A2 (S0[27]), .B1
       (S1[27]), .B2 (n_240), .X (S[27]));
  sky130_fd_sc_hd__a22o_2 g837__4733(.A1 (n_239), .A2 (S0[20]), .B1
       (n_240), .B2 (S1[20]), .X (S[20]));
  sky130_fd_sc_hd__a22o_2 g839__9315(.A1 (n_239), .A2 (S0[19]), .B1
       (n_240), .B2 (S1[19]), .X (S[19]));
  sky130_fd_sc_hd__nand2_8 g840__9945(.A (n_9), .B (n_14), .Y (S[31]));
  sky130_fd_sc_hd__a22o_4 g841__2883(.A1 (S0[28]), .A2 (n_239), .B1
       (n_198), .B2 (S1[28]), .X (S[28]));
  sky130_fd_sc_hd__a22o_4 g842__2346(.A1 (S0[29]), .A2 (n_239), .B1
       (n_198), .B2 (S1[29]), .X (S[29]));
  sky130_fd_sc_hd__a22o_2 g843__1666(.A1 (n_239), .A2 (S0[25]), .B1
       (n_240), .B2 (S1[25]), .X (S[25]));
  sky130_fd_sc_hd__a22o_2 g844__7410(.A1 (n_239), .A2 (S0[24]), .B1
       (n_240), .B2 (S1[24]), .X (S[24]));
  sky130_fd_sc_hd__nand2_4 g845__6417(.A (n_11), .B (n_12), .Y (Cout));
  sky130_fd_sc_hd__a22o_4 g846__5477(.A1 (n_239), .A2 (S0[23]), .B1
       (n_198), .B2 (S1[23]), .X (S[23]));
  sky130_fd_sc_hd__a22o_4 g847__2398(.A1 (n_239), .A2 (S0[22]), .B1
       (n_198), .B2 (S1[22]), .X (S[22]));
  sky130_fd_sc_hd__a22o_4 g848__5107(.A1 (n_239), .A2 (S0[21]), .B1
       (n_198), .B2 (S1[21]), .X (S[21]));
  sky130_fd_sc_hd__nand2_4 g849__6260(.A (S1[31]), .B (n_198), .Y
       (n_14));
  sky130_fd_sc_hd__nand2_1 g850__4319(.A (S1[30]), .B (n_198), .Y
       (n_13));
  sky130_fd_sc_hd__nand2_2 g851__8428(.A (C1[3]), .B (n_198), .Y
       (n_12));
  sky130_fd_sc_hd__nand2_1 g852__5526(.A (C0[3]), .B (n_239), .Y
       (n_11));
  sky130_fd_sc_hd__nand2_1 g853__6783(.A (n_239), .B (S0[30]), .Y
       (n_10));
  sky130_fd_sc_hd__nand2_2 g854__3680(.A (S0[31]), .B (n_239), .Y
       (n_9));
  sky130_fd_sc_hd__mux2_2 g856__1617(.A0 (S0[16]), .A1 (S1[16]), .S
       (n_4), .X (S[16]));
  sky130_fd_sc_hd__mux2_2 g857__2802(.A0 (S0[17]), .A1 (S1[17]), .S
       (n_4), .X (S[17]));
  sky130_fd_sc_hd__mux2_2 g858__1705(.A0 (S0[15]), .A1 (S1[15]), .S
       (n_4), .X (S[15]));
  sky130_fd_sc_hd__mux2_2 g860__5122(.A0 (S0[12]), .A1 (S1[12]), .S
       (n_4), .X (S[12]));
  sky130_fd_sc_hd__mux2_2 g861__8246(.A0 (S0[13]), .A1 (S1[13]), .S
       (n_4), .X (S[13]));
  sky130_fd_sc_hd__mux2_2 g862__7098(.A0 (S0[14]), .A1 (S1[14]), .S
       (n_4), .X (S[14]));
  sky130_fd_sc_hd__mux2_2 g863__6131(.A0 (S0[11]), .A1 (S1[11]), .S
       (n_4), .X (S[11]));
  sky130_fd_sc_hd__mux2_2 g864__1881(.A0 (S0[10]), .A1 (S1[10]), .S
       (n_4), .X (S[10]));
  sky130_fd_sc_hd__nand2_4 g865__5115(.A (C1[2]), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__nand2_4 g866__7482(.A (C0[2]), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__mux2_2 g867__4733(.A0 (S0[7]), .A1 (S1[7]), .S
       (C_mid[0]), .X (S[7]));
  sky130_fd_sc_hd__mux2_2 g868__6161(.A0 (S0[6]), .A1 (S1[6]), .S
       (C_mid[0]), .X (S[6]));
  sky130_fd_sc_hd__mux2_2 g869__9315(.A0 (S0[5]), .A1 (S1[5]), .S
       (C_mid[0]), .X (S[5]));
  sky130_fd_sc_hd__inv_4 g870(.A (n_4), .Y (n_3));
  sky130_fd_sc_hd__mux2_2 g871__9945(.A0 (S0[8]), .A1 (S1[8]), .S
       (C_mid[0]), .X (S[8]));
  sky130_fd_sc_hd__mux2_2 g872__2883(.A0 (S0[4]), .A1 (S1[4]), .S
       (C_mid[0]), .X (S[4]));
  sky130_fd_sc_hd__mux2_2 g873__2346(.A0 (S0[9]), .A1 (S1[9]), .S
       (C_mid[0]), .X (S[9]));
  sky130_fd_sc_hd__nand2_4 g874__1666(.A (n_2), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__nand2_2 g875__7410(.A (C1[1]), .B (C_mid[0]), .Y
       (n_2));
  sky130_fd_sc_hd__nand2_2 g876__6417(.A (C0[1]), .B (n_0), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g877(.A (C_mid[0]), .Y (n_0));
  sky130_fd_sc_hd__nand2_8 g859_0__2398(.A (n_233), .B (n_234), .Y
       (n_198));
  sky130_fd_sc_hd__clkbuf_1 g879(.A (B[19]), .X (n_200));
  sky130_fd_sc_hd__clkbuf_1 g313_dup(.A (B[19]), .X (n_201));
  sky130_fd_sc_hd__clkbuf_1 g880(.A (A[18]), .X (n_202));
  sky130_fd_sc_hd__clkbuf_1 g325_dup(.A (A[18]), .X (n_203));
  sky130_fd_sc_hd__clkbuf_1 g881(.A (A[19]), .X (n_204));
  sky130_fd_sc_hd__clkbuf_1 g348_dup(.A (A[19]), .X (n_205));
  sky130_fd_sc_hd__clkbuf_1 g883(.A (B[18]), .X (n_208));
  sky130_fd_sc_hd__clkbuf_1 g296_dup(.A (B[18]), .X (n_209));
  sky130_fd_sc_hd__buf_1 g885(.A (B[10]), .X (n_212));
  sky130_fd_sc_hd__clkbuf_1 g886(.A (B[4]), .X (n_214));
  sky130_fd_sc_hd__buf_1 g887(.A (A[21]), .X (n_216));
  sky130_fd_sc_hd__buf_1 g294_dup(.A (A[21]), .X (n_217));
  sky130_fd_sc_hd__clkbuf_1 g888(.A (A[4]), .X (n_218));
  sky130_fd_sc_hd__buf_1 g889(.A (A[12]), .X (n_220));
  sky130_fd_sc_hd__buf_1 g330_dup(.A (A[12]), .X (n_221));
  sky130_fd_sc_hd__buf_2 g2(.A (n_5), .X (n_233));
  sky130_fd_sc_hd__buf_2 g1(.A (n_6), .X (n_234));
  sky130_fd_sc_hd__inv_2 g22(.A (n_235), .Y (n_236));
  sky130_fd_sc_hd__nand2_4 g25(.A (n_5), .B (n_6), .Y (n_235));
  sky130_fd_sc_hd__inv_6 g24(.A (n_235), .Y (n_239));
  sky130_fd_sc_hd__buf_6 g23(.A (n_235), .X (n_240));
  sky130_fd_sc_hd__mux2_4 g890(.A0 (S1[26]), .A1 (S0[26]), .S (n_236),
       .X (S[26]));
endmodule

