
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr  7 2025 17:51:09 -03 (Apr  7 2025 20:51:09 UTC)

// Verification Directory fv/carry_select_adder_8888_32bits 

module full_adder_24_228(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__ha_2 g2(.A (B), .B (A), .COUT (Cout), .SUM (S));
endmodule

module full_adder_219(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  sky130_fd_sc_hd__nand2_2 g134__6260(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g135__4319(.A (n_4), .B (n_7), .X (S));
  sky130_fd_sc_hd__nand2_1 g136__8428(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g137__5526(.A (n_0), .B (A), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g138__6783(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g139__3680(.A (n_0), .B (A), .Y (n_5));
  sky130_fd_sc_hd__clkbuf_1 g140(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g143(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g145(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__inv_2 g146(.A (B), .Y (n_2));
endmodule

module full_adder_218(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_2 g117__1617(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g118__2802(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__nand2_2 g119__1705(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g120__5122(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g121__8246(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g122__7098(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__clkbuf_1 g123(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g125(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g126(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g128(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g129(.A (B), .Y (n_2));
endmodule

module full_adder_217(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_4, n_5, n_7, n_8, n_14;
  sky130_fd_sc_hd__nand2_2 g117__6131(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g118__1881(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__nand2_2 g119__5115(.A (Cin), .B (n_14), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g120__7482(.A (B), .B (A), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g122__6161(.A (B), .B (A), .Y (n_5));
  sky130_fd_sc_hd__buf_2 g123(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__or2_1 g2(.A (A), .B (B), .X (n_14));
endmodule

module full_adder_216(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_1 g89__9315(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g90__9945(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_1 g91__2883(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g92__2346(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g93__1666(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g94__7410(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g95(.A (Cin), .X (n_2));
endmodule

module full_adder_215(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_1 g82__6417(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g83__5477(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_1 g84__2398(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g85__5107(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g86__6260(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g87__4319(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g88(.A (Cin), .X (n_2));
endmodule

module full_adder_214(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_1 g82__8428(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g83__5526(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_1 g84__6783(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g85__3680(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g86__1617(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g87__2802(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g88(.A (Cin), .X (n_2));
endmodule

module full_adder_213(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g94__1705(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g95__5122(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_1 g96__8246(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g97__7098(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g98__6131(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g99__1881(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g100(.A (Cin), .X (n_2));
endmodule

module ripple_carry_adder_WIDTH8_5_231(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z;
  full_adder_24_228 F1A(.A (A[0]), .B (B[0]), .Cin
       (UNCONNECTED_HIER_Z), .S (S[0]), .Cout (carry[0]));
  full_adder_219 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_218 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_217 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_216 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_215 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_214 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_213 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_32_230(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nand2_1 g54__5115(.A (n_1), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g56(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g58(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g2__7482(.A (n_1), .B (n_2), .Y (S));
endmodule

module full_adder_212(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_1 g149__4733(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g150__6161(.A (n_4), .B (n_7), .X (S));
  sky130_fd_sc_hd__nand2_1 g151__9315(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g152__9945(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g153__2883(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g154__2346(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__clkbuf_1 g155(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g157(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g158(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g160(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__inv_2 g161(.A (B), .Y (n_2));
endmodule

module full_adder_211(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  sky130_fd_sc_hd__nand2_2 g116__1666(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g117__7410(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__nand2_1 g118__6417(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g119__5477(.A (B), .B (A), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g120__2398(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g121__5107(.A (B), .B (A), .Y (n_5));
  sky130_fd_sc_hd__clkbuf_1 g122(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__clkinv_1 g125(.A (A), .Y (n_3));
  sky130_fd_sc_hd__clkinv_1 g128(.A (B), .Y (n_2));
endmodule

module full_adder_210(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g116__6260(.A (n_6), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g117__4319(.A (n_5), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_2 g118__8428(.A (Cin), .B (n_0), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g119__5526(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__nand2_1 g121__6783(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__or2_1 g2__3680(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_209(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g116__1617(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g117__2802(.A (n_5), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_2 g118__1705(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g119__5122(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g120__8246(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g121__7098(.A (B), .B (A), .Y (n_3));
endmodule

module full_adder_208(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g117__6131(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g118__1881(.A (n_5), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_2 g119__5115(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g120__7482(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g121__4733(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g122__6161(.A (B), .B (A), .Y (n_3));
endmodule

module full_adder_207(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g89__9315(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g90__9945(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_2 g91__2883(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g92__2346(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g93__1666(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g94__7410(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_1 g95(.A (Cin), .X (n_2));
endmodule

module full_adder_206(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g94__6417(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g95__5477(.A (n_5), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g96__2398(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g97__5107(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g98__6260(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g99__4319(.A (B), .B (A), .Y (n_3));
endmodule

module ripple_carry_adder_WIDTH8_6_233(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z0;
  full_adder_32_230 F1A(.A (A[0]), .B (B[0]), .Cin
       (UNCONNECTED_HIER_Z0), .S (S[0]), .Cout (carry[0]));
  full_adder_212 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_211 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_210 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_209 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_208 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_207 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_206 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_24(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nor2_1 g34__8428(.A (n_2), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__inv_2 g36(.A (B), .Y (n_2));
  sky130_fd_sc_hd__inv_2 g38(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xor2_1 g2__5526(.A (n_2), .B (n_1), .X (S));
endmodule

module full_adder_205(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  sky130_fd_sc_hd__nand2_1 g120__6783(.A (n_7), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__3680(.A (Cin), .B (n_6), .X (S));
  sky130_fd_sc_hd__nand2_1 g122__1617(.A (Cin), .B (n_5), .Y (n_7));
  sky130_fd_sc_hd__xor2_1 g123__2802(.A (n_0), .B (n_1), .X (n_6));
  sky130_fd_sc_hd__nand2_1 g124__1705(.A (n_3), .B (n_2), .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g125__5122(.A (n_0), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g127(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g128(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g130(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__inv_2 g131(.A (B), .Y (n_2));
endmodule

module full_adder_204(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g82__8246(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g83__7098(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g84__6131(.A (Cin), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g85__1881(.A (B), .B (n_2), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g87__5115(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g89(.A (A), .X (n_2));
  sky130_fd_sc_hd__or2_0 g2__7482(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_203(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g82__4733(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g83__6161(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g84__9315(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g85__9945(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g86__2883(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g87__2346(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_202(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g79__1666(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g80__7410(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g81__6417(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g82__5477(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g83__2398(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g84__5107(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_201(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g79__6260(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g80__4319(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g81__8428(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g82__5526(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g83__6783(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g84__3680(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_200(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_9, n_10, n_11, n_12, n_14;
  sky130_fd_sc_hd__xor2_1 g80__2802(.A (n_14), .B (n_9), .X (S));
  sky130_fd_sc_hd__buf_2 g1(.A (Cin), .X (n_9));
  sky130_fd_sc_hd__nand2_2 g27(.A (n_11), .B (n_12), .Y (Cout));
  sky130_fd_sc_hd__nand2_2 g28(.A (Cin), .B (n_10), .Y (n_11));
  sky130_fd_sc_hd__or2_0 g30(.A (A), .B (B), .X (n_10));
  sky130_fd_sc_hd__nand2_1 g31(.A (B), .B (A), .Y (n_12));
  sky130_fd_sc_hd__xor2_1 g29(.A (B), .B (A), .X (n_14));
endmodule

module full_adder_199(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_2 g79__7098(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g80__6131(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__o21ai_2 g81__1881(.A1 (A), .A2 (B), .B1 (Cin), .Y
       (n_3));
  sky130_fd_sc_hd__ha_1 g82__5115(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
endmodule

module ripple_carry_adder_WIDTH8_5_232(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z1;
  full_adder_24 F1A(.A (A[0]), .B (B[0]), .Cin (UNCONNECTED_HIER_Z1),
       .S (S[0]), .Cout (carry[0]));
  full_adder_205 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_204 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_203 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_202 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_201 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_200 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_199 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_32(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nand2_1 g54__7482(.A (n_1), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g56(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g58(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g2__4733(.A (n_1), .B (n_2), .Y (S));
endmodule

module full_adder_198(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  sky130_fd_sc_hd__nand2_1 g82__6161(.A (n_7), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g83__9315(.A (Cin), .B (n_6), .X (S));
  sky130_fd_sc_hd__nand2_1 g84__9945(.A (Cin), .B (n_5), .Y (n_7));
  sky130_fd_sc_hd__xor2_1 g85__2883(.A (n_0), .B (n_1), .X (n_6));
  sky130_fd_sc_hd__nand2_1 g86__2346(.A (n_3), .B (n_2), .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g87__1666(.A (n_0), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g89(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g90(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g92(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__inv_2 g93(.A (B), .Y (n_2));
endmodule

module full_adder_197(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g82__7410(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g83__6417(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g84__5477(.A (Cin), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g85__2398(.A (B), .B (n_2), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g87__5107(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g89(.A (A), .X (n_2));
  sky130_fd_sc_hd__or2_1 g2__6260(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_196(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g82__4319(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g83__8428(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g84__5526(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g85__6783(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g86__3680(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g87__1617(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_195(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_4, n_11, n_12, n_13, n_14;
  sky130_fd_sc_hd__xor2_1 g83__1705(.A (n_4), .B (n_11), .X (S));
  sky130_fd_sc_hd__xor2_1 g85__8246(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__buf_2 g1(.A (Cin), .X (n_11));
  sky130_fd_sc_hd__nand2_2 g17(.A (n_13), .B (n_14), .Y (Cout));
  sky130_fd_sc_hd__nand2_2 g18(.A (Cin), .B (n_12), .Y (n_13));
  sky130_fd_sc_hd__or2_0 g20(.A (A), .B (B), .X (n_12));
  sky130_fd_sc_hd__nand2_1 g19(.A (B), .B (A), .Y (n_14));
endmodule

module full_adder_194(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g79__1881(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g80__5115(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_2 g81__7482(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g82__4733(.A (n_0), .B (n_1), .X (n_4));
  sky130_fd_sc_hd__or2_0 g83__6161(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g84__9315(.A (n_0), .B (n_1), .Y (n_2));
  sky130_fd_sc_hd__clkbuf_1 g86(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g88(.A (B), .X (n_0));
endmodule

module full_adder_193(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g79__9945(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g80__2883(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_2 g81__2346(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g82__1666(.A (B), .B (n_1), .X (n_4));
  sky130_fd_sc_hd__or2_0 g83__7410(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g84__6417(.A (B), .B (n_1), .Y (n_2));
  sky130_fd_sc_hd__clkbuf_1 g86(.A (A), .X (n_1));
endmodule

module full_adder_192(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_9, n_10;
  sky130_fd_sc_hd__nand2b_1 g79__5477(.A_N (n_1), .B (n_10), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g80__2398(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__ha_1 g82__6260(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__nand2_2 g2(.A (n_9), .B (Cin), .Y (n_10));
  sky130_fd_sc_hd__or2_1 g3(.A (A), .B (B), .X (n_9));
endmodule

module ripple_carry_adder_WIDTH8_6_234(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z2;
  full_adder_32 F1A(.A (A[0]), .B (B[0]), .Cin (UNCONNECTED_HIER_Z2),
       .S (S[0]), .Cout (carry[0]));
  full_adder_198 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_197 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_196 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_195 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_194 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_193 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_192 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_24_227(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nor2_1 g29__4319(.A (n_2), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g31(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g33(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xor2_1 g2__8428(.A (n_2), .B (n_1), .X (S));
endmodule

module full_adder_191(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED, n_2, n_3, n_4, n_5, n_6, n_7;
  sky130_fd_sc_hd__nand2_1 g95__5526(.A (n_7), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g97__3680(.A (Cin), .B (n_5), .Y (n_7));
  sky130_fd_sc_hd__xor2_1 g98__1617(.A (B), .B (A), .X (n_6));
  sky130_fd_sc_hd__nand2_1 g99__2802(.A (n_3), .B (n_2), .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g100__1705(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g103(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g106(.A (B), .Y (n_2));
  sky130_fd_sc_hd__ha_1 g96__108(.A (Cin), .B (n_6), .COUT
       (UNCONNECTED), .SUM (S));
endmodule

module full_adder_190(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED0, n_0, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g60__5122(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g62__7098(.A (Cin), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g63__6131(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g65__1881(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__or2_0 g2__5115(.A (A), .B (B), .X (n_0));
  sky130_fd_sc_hd__ha_1 g61__71(.A (n_4), .B (Cin), .COUT
       (UNCONNECTED0), .SUM (S));
endmodule

module full_adder_189(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED1, n_10, n_12, n_13;
  sky130_fd_sc_hd__ha_1 g58__63(.A (n_12), .B (Cin), .COUT
       (UNCONNECTED1), .SUM (S));
  sky130_fd_sc_hd__o2bb2ai_1 g26(.A1_N (A), .A2_N (B), .B1 (n_13), .B2
       (n_10), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g28(.A (Cin), .Y (n_10));
  sky130_fd_sc_hd__xor2_1 g27(.A (B), .B (A), .X (n_12));
  sky130_fd_sc_hd__nor2_1 g2(.A (A), .B (B), .Y (n_13));
endmodule

module full_adder_188(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED2, n_0, n_1, n_2;
  sky130_fd_sc_hd__ha_1 g60__7410(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__6417(.A (A), .B (B), .X (n_0));
  sky130_fd_sc_hd__ha_1 g58__63(.A (n_2), .B (Cin), .COUT
       (UNCONNECTED2), .SUM (S));
  sky130_fd_sc_hd__a21o_1 g2(.A1 (Cin), .A2 (n_0), .B1 (n_1), .X
       (Cout));
endmodule

module full_adder_187(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_8;
  sky130_fd_sc_hd__ha_1 g60__6260(.A (B), .B (A), .COUT (n_0), .SUM
       (n_1));
  sky130_fd_sc_hd__or2_0 g3(.A (A), .B (B), .X (n_8));
  sky130_fd_sc_hd__a21o_1 g63(.A1 (n_8), .A2 (Cin), .B1 (n_0), .X
       (Cout));
  sky130_fd_sc_hd__xor2_1 g58__65(.A (n_1), .B (Cin), .X (S));
endmodule

module full_adder_186(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fah_1 g57__4319(.A (A), .B (B), .CI (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_185(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fah_1 g57__8428(.A (A), .B (B), .CI (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module ripple_carry_adder_WIDTH8_5(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z3;
  full_adder_24_227 F1A(.A (A[0]), .B (B[0]), .Cin
       (UNCONNECTED_HIER_Z3), .S (S[0]), .Cout (carry[0]));
  full_adder_191 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_190 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_189 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_188 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_187 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_186 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_185 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_32_229(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nand2_1 g40__5526(.A (n_1), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g42(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g44(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g2__6783(.A (n_1), .B (n_2), .Y (S));
endmodule

module full_adder_184(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__o21ai_1 g60__3680(.A1 (n_2), .A2 (n_0), .B1 (n_1),
       .Y (Cout));
  sky130_fd_sc_hd__xnor2_1 g61__1617(.A (n_0), .B (n_3), .Y (S));
  sky130_fd_sc_hd__xor2_1 g62__2802(.A (B), .B (A), .X (n_3));
  sky130_fd_sc_hd__nor2_1 g63__1705(.A (A), .B (B), .Y (n_2));
  sky130_fd_sc_hd__nand2_1 g64__5122(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g65(.A (Cin), .Y (n_0));
endmodule

module full_adder_183(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED3, n_0, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g57__8246(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g59__6131(.A (Cin), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__1881(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g62__5115(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__or2_0 g2__7482(.A (A), .B (B), .X (n_0));
  sky130_fd_sc_hd__ha_1 g58__68(.A (n_4), .B (Cin), .COUT
       (UNCONNECTED3), .SUM (S));
endmodule

module full_adder_182(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED4, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g57__4733(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g59__9315(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__9945(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__2883(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__2346(.A (B), .B (A), .Y (n_2));
  sky130_fd_sc_hd__ha_1 g58__68(.A (n_4), .B (Cin), .COUT
       (UNCONNECTED4), .SUM (S));
endmodule

module full_adder_181(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_1 g57__1666(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__7410(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__6417(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__5477(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__2398(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_180(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_8;
  sky130_fd_sc_hd__xor2_1 g58__6260(.A (n_1), .B (Cin), .X (S));
  sky130_fd_sc_hd__ha_1 g60__8428(.A (B), .B (A), .COUT (n_0), .SUM
       (n_1));
  sky130_fd_sc_hd__or2_0 g16(.A (A), .B (B), .X (n_8));
  sky130_fd_sc_hd__a21o_1 g2(.A1 (Cin), .A2 (n_8), .B1 (n_0), .X
       (Cout));
endmodule

module full_adder_179(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fah_1 g57__5526(.A (A), .B (B), .CI (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_178(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fah_1 g57__6783(.A (A), .B (B), .CI (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module ripple_carry_adder_WIDTH8_6(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z4;
  full_adder_32_229 F1A(.A (A[0]), .B (B[0]), .Cin
       (UNCONNECTED_HIER_Z4), .S (S[0]), .Cout (carry[0]));
  full_adder_184 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_183 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_182 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_181 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_180 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_179 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_178 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED5, n_33, n_34, n_35, n_40;
  sky130_fd_sc_hd__o21ai_2 g103(.A1 (n_33), .A2 (n_34), .B1 (n_35), .Y
       (Cout));
  sky130_fd_sc_hd__clkinv_1 g107(.A (B), .Y (n_33));
  sky130_fd_sc_hd__nor2_2 g106(.A (Cin), .B (A), .Y (n_34));
  sky130_fd_sc_hd__nand2_1 g105(.A (Cin), .B (A), .Y (n_35));
  sky130_fd_sc_hd__ha_1 g109(.A (n_40), .B (Cin), .COUT (UNCONNECTED5),
       .SUM (S));
  sky130_fd_sc_hd__xor2_1 g2(.A (B), .B (A), .X (n_40));
endmodule

module full_adder_226(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_6, n_8, n_14;
  wire n_15, n_16;
  sky130_fd_sc_hd__nand2_4 g119__8246(.A (n_8), .B (n_16), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g120__7098(.A (n_4), .B (n_14), .X (S));
  sky130_fd_sc_hd__nand2_4 g121__6131(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__nand2_1 g123__5115(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__buf_2 g125(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g127(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g128(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g130(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__inv_2 g131(.A (B), .Y (n_2));
  sky130_fd_sc_hd__ha_1 g2(.A (n_0), .B (n_1), .COUT (n_15), .SUM
       (n_14));
  sky130_fd_sc_hd__inv_1 g3(.A (n_15), .Y (n_16));
endmodule

module full_adder_225(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_5, n_7, n_8, n_14;
  sky130_fd_sc_hd__nand2_4 g119__4733(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g120__6161(.A (n_7), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_4 g121__9315(.A (Cin), .B (n_14), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g122__9945(.A (B), .B (A), .X (n_7));
  sky130_fd_sc_hd__nand2_4 g124__2346(.A (B), .B (A), .Y (n_5));
  sky130_fd_sc_hd__or2_2 g2(.A (A), .B (B), .X (n_14));
endmodule

module full_adder_224(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g119__1666(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g120__7410(.A (n_5), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_4 g121__6417(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g122__5477(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_4 g123__2398(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g124__5107(.A (B), .B (A), .Y (n_3));
endmodule

module full_adder_223(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED6, n_0, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g119__6260(.A (n_6), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g121__4319(.A (Cin), .B (n_5), .Y (n_6));
  sky130_fd_sc_hd__or2_4 g122__8428(.A (A), .B (B), .X (n_5));
  sky130_fd_sc_hd__nand2_4 g123__5526(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__buf_1 fopt(.A (Cin), .X (n_0));
  sky130_fd_sc_hd__fa_1 g129__6783(.A (n_0), .B (A), .CIN (B), .COUT
       (UNCONNECTED6), .SUM (S));
endmodule

module full_adder_222(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED7, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g116__3680(.A (n_6), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g118__1617(.A (Cin), .B (n_5), .Y (n_6));
  sky130_fd_sc_hd__or2_4 g119__2802(.A (A), .B (B), .X (n_5));
  sky130_fd_sc_hd__nand2_4 g120__1705(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__buf_2 g121(.A (Cin), .X (n_3));
  sky130_fd_sc_hd__fa_1 g126__5122(.A (B), .B (A), .CIN (n_3), .COUT
       (UNCONNECTED7), .SUM (S));
endmodule

module full_adder_221(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED8, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_4 g116__8246(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g118__6131(.A (Cin), .B (n_4), .Y (n_5));
  sky130_fd_sc_hd__or2_4 g119__1881(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g120__5115(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g121(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__fa_2 g117__126(.A (B), .B (A), .CIN (n_2), .COUT
       (UNCONNECTED8), .SUM (S));
endmodule

module full_adder_220(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_4 g89__7482(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor3_1 g90__4733(.A (B), .B (A), .C (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g91__6161(.A (Cin), .B (n_4), .Y (n_5));
  sky130_fd_sc_hd__or2_4 g92__9315(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g93__9945(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g94(.A (Cin), .X (n_2));
endmodule

module ripple_carry_adder_WIDTH8(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder F1A(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (carry[0]));
  full_adder_226 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_225 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_224 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_223 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_222 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_221 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_220 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module carry_select_adder_8888_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire [31:0] S0;
  wire [3:0] C0;
  wire [31:0] S1;
  wire [3:0] C1;
  wire [3:0] C_mid;
  wire UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10,
       n_1, n_4;
  wire n_16, n_19, n_21, n_22, n_26, n_28, n_30, n_31;
  wire n_52, n_53, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_67, n_69, n_71;
  wire n_72, n_75, n_76, n_77, n_78, n_79, n_80, n_82;
  wire n_83, n_84, n_88, n_89, n_90, n_94, n_95, n_96;
  wire n_98, n_101, n_102, n_103, n_104, n_107, n_108, n_111;
  wire n_123, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, n_134, n_135, n_136, n_139, n_140, n_141;
  wire n_142, n_143, n_144, n_146, n_147, n_148, n_149, n_150;
  wire n_151, n_336, n_337, n_338, n_353, n_404, n_405, n_415;
  wire n_416, n_417, n_423, n_424, n_425, n_426, n_428, n_429;
  wire n_440, n_444, n_448, n_452, n_456, n_460, n_468, n_469;
  wire n_470, n_471, n_473, n_474, n_478, n_479, n_480, n_481;
  wire n_482, n_483, n_484, n_485, n_486, n_487, n_489, n_493;
  wire n_494, n_495, n_496, n_497, n_498, n_499, n_500, n_501;
  wire n_502, n_504;
  ripple_carry_adder_WIDTH8_5_231 \CSA_BLOCKS[1].RCA_C0 (.A ({n_151,
       n_150, n_149, n_148, n_147, n_146, A[9], n_104}), .B ({n_144,
       n_143, n_142, n_141, n_140, n_139, n_500, n_102}), .Cin
       (UNCONNECTED_HIER_Z5), .S (S0[15:8]), .Cout (C0[1]));
  ripple_carry_adder_WIDTH8_6_233 \CSA_BLOCKS[1].RCA_C1 (.A ({n_151,
       n_150, n_149, n_148, n_147, n_146, n_502, n_104}), .B ({n_144,
       n_143, n_142, n_141, n_140, n_139, n_501, n_102}), .Cin
       (UNCONNECTED_HIER_Z6), .S (S1[15:8]), .Cout (C1[1]));
  ripple_carry_adder_WIDTH8_5_232 \CSA_BLOCKS[2].RCA_C0 (.A ({n_136,
       n_135, n_134, n_133, n_108, n_132, n_131, n_130}), .B ({n_129,
       n_128, n_127, n_126, n_84, n_125, B[17], n_123}), .Cin
       (UNCONNECTED_HIER_Z7), .S (S0[23:16]), .Cout (C0[2]));
  ripple_carry_adder_WIDTH8_6_234 \CSA_BLOCKS[2].RCA_C1 (.A ({n_136,
       n_135, n_134, n_133, n_108, n_132, n_131, n_130}), .B ({n_129,
       n_128, n_127, n_126, n_84, n_125, B[17], n_123}), .Cin
       (UNCONNECTED_HIER_Z8), .S (S1[23:16]), .Cout (C1[2]));
  ripple_carry_adder_WIDTH8_5 \CSA_BLOCKS[3].RCA_C0 (.A ({A[31:25],
       n_90}), .B ({B[31:25], n_78}), .Cin (UNCONNECTED_HIER_Z9), .S
       (S0[31:24]), .Cout (C0[3]));
  ripple_carry_adder_WIDTH8_6 \CSA_BLOCKS[3].RCA_C1 (.A ({A[31:27],
       n_88, n_98, n_90}), .B ({B[31:25], n_78}), .Cin
       (UNCONNECTED_HIER_Z10), .S (S1[31:24]), .Cout (C1[3]));
  ripple_carry_adder_WIDTH8 RCA_LSB(.A ({n_69, n_64, n_61, n_75, n_94,
       n_76, A[1:0]}), .B ({n_67, n_56, n_58, n_111, n_82, n_95, B[1],
       n_63}), .Cin (n_79), .S (S[7:0]), .Cout (C_mid[0]));
  sky130_fd_sc_hd__inv_1 g2512(.A (n_71), .Y (n_111));
  sky130_fd_sc_hd__inv_1 g2527(.A (n_107), .Y (n_108));
  sky130_fd_sc_hd__inv_2 g2561(.A (n_103), .Y (n_104));
  sky130_fd_sc_hd__inv_2 g2530(.A (n_101), .Y (n_102));
  sky130_fd_sc_hd__inv_2 g2553(.A (n_96), .Y (n_98));
  sky130_fd_sc_hd__inv_1 g2469(.A (n_72), .Y (n_95));
  sky130_fd_sc_hd__inv_1 g2472(.A (n_60), .Y (n_94));
  sky130_fd_sc_hd__inv_2 g2524(.A (n_52), .Y (n_141));
  sky130_fd_sc_hd__inv_2 g2483(.A (n_62), .Y (n_148));
  sky130_fd_sc_hd__inv_1 g2539(.A (n_89), .Y (n_90));
  sky130_fd_sc_hd__inv_2 g2492(.A (n_80), .Y (n_88));
  sky130_fd_sc_hd__inv_1 g2534(.A (n_83), .Y (n_84));
  sky130_fd_sc_hd__inv_1 g2474(.A (n_53), .Y (n_82));
  sky130_fd_sc_hd__inv_1 g2515(.A (n_55), .Y (n_79));
  sky130_fd_sc_hd__inv_1 g2545(.A (n_77), .Y (n_78));
  sky130_fd_sc_hd__inv_2 g2517(.A (n_59), .Y (n_76));
  sky130_fd_sc_hd__inv_1 g2521(.A (n_57), .Y (n_75));
  sky130_fd_sc_hd__inv_2 g2556(.A (n_65), .Y (n_133));
  sky130_fd_sc_hd__inv_2 g2470(.A (B[2]), .Y (n_72));
  sky130_fd_sc_hd__inv_2 g2513(.A (B[4]), .Y (n_71));
  sky130_fd_sc_hd__clkbuf_1 g2476(.A (A[7]), .X (n_69));
  sky130_fd_sc_hd__clkbuf_1 g2520(.A (B[7]), .X (n_67));
  sky130_fd_sc_hd__clkinv_1 g2557(.A (A[20]), .Y (n_65));
  sky130_fd_sc_hd__clkbuf_1 g2523(.A (A[6]), .X (n_64));
  sky130_fd_sc_hd__buf_6 g2468(.A (B[0]), .X (n_63));
  sky130_fd_sc_hd__clkbuf_1 g2482(.A (B[20]), .X (n_126));
  sky130_fd_sc_hd__inv_2 g2547(.A (B[24]), .Y (n_77));
  sky130_fd_sc_hd__clkbuf_1 g2564(.A (B[13]), .X (n_142));
  sky130_fd_sc_hd__inv_2 g2562(.A (A[8]), .Y (n_103));
  sky130_fd_sc_hd__clkbuf_1 g2552(.A (A[13]), .X (n_149));
  sky130_fd_sc_hd__inv_4 g2532(.A (B[8]), .Y (n_101));
  sky130_fd_sc_hd__inv_2 g2529(.A (A[19]), .Y (n_107));
  sky130_fd_sc_hd__clkbuf_1 g2563(.A (A[16]), .X (n_130));
  sky130_fd_sc_hd__inv_2 g2541(.A (A[24]), .Y (n_89));
  sky130_fd_sc_hd__clkbuf_1 g2495(.A (A[15]), .X (n_151));
  sky130_fd_sc_hd__inv_2 g2536(.A (B[19]), .Y (n_83));
  sky130_fd_sc_hd__inv_2 g2494(.A (A[26]), .Y (n_80));
  sky130_fd_sc_hd__clkbuf_1 g2533(.A (A[14]), .X (n_150));
  sky130_fd_sc_hd__clkbuf_1 g2508(.A (B[15]), .X (n_144));
  sky130_fd_sc_hd__inv_2 g2484(.A (A[12]), .Y (n_62));
  sky130_fd_sc_hd__clkbuf_1 g2478(.A (A[5]), .X (n_61));
  sky130_fd_sc_hd__inv_2 g2473(.A (A[3]), .Y (n_60));
  sky130_fd_sc_hd__inv_2 g2518(.A (A[2]), .Y (n_59));
  sky130_fd_sc_hd__clkbuf_1 g2467(.A (B[5]), .X (n_58));
  sky130_fd_sc_hd__inv_2 g2522(.A (A[4]), .Y (n_57));
  sky130_fd_sc_hd__clkbuf_1 g2519(.A (B[6]), .X (n_56));
  sky130_fd_sc_hd__inv_2 g2516(.A (Cin), .Y (n_55));
  sky130_fd_sc_hd__inv_2 g2475(.A (B[3]), .Y (n_53));
  sky130_fd_sc_hd__inv_2 g2525(.A (B[12]), .Y (n_52));
  sky130_fd_sc_hd__buf_1 g2490(.A (B[11]), .X (n_140));
  sky130_fd_sc_hd__clkbuf_1 g2509(.A (A[23]), .X (n_136));
  sky130_fd_sc_hd__inv_2 g2555(.A (A[25]), .Y (n_96));
  sky130_fd_sc_hd__buf_1 g2526(.A (A[18]), .X (n_132));
  sky130_fd_sc_hd__clkbuf_1 g2549(.A (B[16]), .X (n_123));
  sky130_fd_sc_hd__clkbuf_1 g2480(.A (B[14]), .X (n_143));
  sky130_fd_sc_hd__clkbuf_1 g2538(.A (A[17]), .X (n_131));
  sky130_fd_sc_hd__clkbuf_1 g2537(.A (A[21]), .X (n_134));
  sky130_fd_sc_hd__buf_1 g2489(.A (B[18]), .X (n_125));
  sky130_fd_sc_hd__clkbuf_1 g2551(.A (A[10]), .X (n_146));
  sky130_fd_sc_hd__clkbuf_1 g2510(.A (A[22]), .X (n_135));
  sky130_fd_sc_hd__clkbuf_1 g2544(.A (B[10]), .X (n_139));
  sky130_fd_sc_hd__clkbuf_1 g2550(.A (B[22]), .X (n_128));
  sky130_fd_sc_hd__buf_1 g2542(.A (B[23]), .X (n_129));
  sky130_fd_sc_hd__buf_1 g2496(.A (A[11]), .X (n_147));
  sky130_fd_sc_hd__clkbuf_1 g2497(.A (B[21]), .X (n_127));
  sky130_fd_sc_hd__nand2_4 g5234__9945(.A (n_26), .B (n_495), .Y
       (S[19]));
  sky130_fd_sc_hd__nand2_4 g5235__2883(.A (n_28), .B (n_494), .Y
       (S[20]));
  sky130_fd_sc_hd__nand2_4 g5236__2346(.A (n_30), .B (n_499), .Y
       (S[21]));
  sky130_fd_sc_hd__nand2_4 g5237__1666(.A (n_31), .B (n_496), .Y
       (S[18]));
  sky130_fd_sc_hd__nand2_4 g5239__7410(.A (n_16), .B (n_337), .Y
       (S[23]));
  sky130_fd_sc_hd__nand2_4 g5240__6417(.A (n_19), .B (n_498), .Y
       (S[16]));
  sky130_fd_sc_hd__nand2_4 g5241__5477(.A (n_21), .B (n_497), .Y
       (S[17]));
  sky130_fd_sc_hd__nand2_4 g5242__2398(.A (n_22), .B (n_336), .Y
       (S[22]));
  sky130_fd_sc_hd__nand2_1 g5244__6260(.A (n_338), .B (S0[18]), .Y
       (n_31));
  sky130_fd_sc_hd__nand2_1 g5245__4319(.A (n_338), .B (S0[21]), .Y
       (n_30));
  sky130_fd_sc_hd__nand2_1 g5247__5526(.A (n_338), .B (S0[20]), .Y
       (n_28));
  sky130_fd_sc_hd__nand2_1 g5249__3680(.A (n_338), .B (S0[19]), .Y
       (n_26));
  sky130_fd_sc_hd__nand2_1 g5253__5122(.A (n_338), .B (S0[22]), .Y
       (n_22));
  sky130_fd_sc_hd__nand2_1 g5254__8246(.A (n_338), .B (S0[17]), .Y
       (n_21));
  sky130_fd_sc_hd__nand2_1 g5256__6131(.A (n_338), .B (S0[16]), .Y
       (n_19));
  sky130_fd_sc_hd__nand2_1 g5259__7482(.A (n_338), .B (S0[23]), .Y
       (n_16));
  sky130_fd_sc_hd__a22o_2 g5262__9315(.A1 (n_4), .A2 (S0[14]), .B1
       (n_1), .B2 (S1[14]), .X (S[14]));
  sky130_fd_sc_hd__a22o_2 g5263__9945(.A1 (n_4), .A2 (S0[8]), .B1
       (n_1), .B2 (S1[8]), .X (S[8]));
  sky130_fd_sc_hd__a22o_2 g5264__2883(.A1 (n_4), .A2 (S0[15]), .B1
       (n_1), .B2 (S1[15]), .X (S[15]));
  sky130_fd_sc_hd__a22o_2 g5265__2346(.A1 (n_4), .A2 (S0[13]), .B1
       (n_1), .B2 (S1[13]), .X (S[13]));
  sky130_fd_sc_hd__a22o_2 g5268__1666(.A1 (n_4), .A2 (S0[11]), .B1
       (n_1), .B2 (S1[11]), .X (S[11]));
  sky130_fd_sc_hd__a22o_2 g5269__7410(.A1 (n_4), .A2 (S0[12]), .B1
       (n_1), .B2 (S1[12]), .X (S[12]));
  sky130_fd_sc_hd__a22o_2 g5270__6417(.A1 (n_4), .A2 (S0[9]), .B1
       (n_1), .B2 (S1[9]), .X (S[9]));
  sky130_fd_sc_hd__a22o_2 g5271__5477(.A1 (n_4), .A2 (S0[10]), .B1
       (n_1), .B2 (S1[10]), .X (S[10]));
  sky130_fd_sc_hd__inv_2 g5281(.A (n_1), .Y (n_4));
  sky130_fd_sc_hd__buf_6 g5285(.A (C_mid[0]), .X (n_1));
  sky130_fd_sc_hd__nand2_1 g5260__5347(.A (n_469), .B (S1[22]), .Y
       (n_336));
  sky130_fd_sc_hd__nand2_1 g5257__5348(.A (n_469), .B (S1[23]), .Y
       (n_337));
  sky130_fd_sc_hd__clkinv_2 fopt5351(.A (n_469), .Y (n_338));
  sky130_fd_sc_hd__nand2_1 g5229__5363(.A (n_473), .B (S1[24]), .Y
       (n_353));
  sky130_fd_sc_hd__nand2_4 g51(.A (n_474), .B (n_486), .Y (S[31]));
  sky130_fd_sc_hd__inv_2 g11(.A (C_mid[0]), .Y (n_404));
  sky130_fd_sc_hd__clkinv_1 g10(.A (C0[1]), .Y (n_405));
  sky130_fd_sc_hd__nand2_4 g219(.A (n_426), .B (C0[2]), .Y (n_415));
  sky130_fd_sc_hd__nand3_2 g220(.A (n_416), .B (n_425), .C (C1[2]), .Y
       (n_417));
  sky130_fd_sc_hd__nand2_1 g224(.A (n_404), .B (n_405), .Y (n_416));
  sky130_fd_sc_hd__nand2_2 g21(.A (n_423), .B (n_425), .Y (n_426));
  sky130_fd_sc_hd__nand2_1 g23(.A (n_404), .B (n_405), .Y (n_423));
  sky130_fd_sc_hd__nand2_2 g5369(.A (C_mid[0]), .B (n_424), .Y (n_425));
  sky130_fd_sc_hd__clkinv_1 g24(.A (C1[1]), .Y (n_424));
  sky130_fd_sc_hd__nand2_4 g5370(.A (n_353), .B (n_429), .Y (S[24]));
  sky130_fd_sc_hd__nand2_2 g5371(.A (n_428), .B (S0[24]), .Y (n_429));
  sky130_fd_sc_hd__inv_2 g5375(.A (n_473), .Y (n_428));
  sky130_fd_sc_hd__nand2_4 g5377(.A (n_440), .B (n_487), .Y (S[30]));
  sky130_fd_sc_hd__nand2_1 g5378(.A (n_473), .B (S1[30]), .Y (n_440));
  sky130_fd_sc_hd__nand2_4 g5381(.A (n_444), .B (n_484), .Y (S[29]));
  sky130_fd_sc_hd__nand2_1 g5382(.A (n_473), .B (S1[29]), .Y (n_444));
  sky130_fd_sc_hd__nand2_4 g5385(.A (n_448), .B (n_483), .Y (S[28]));
  sky130_fd_sc_hd__nand2_1 g5386(.A (n_473), .B (S1[28]), .Y (n_448));
  sky130_fd_sc_hd__nand2_4 g5389(.A (n_452), .B (n_482), .Y (S[27]));
  sky130_fd_sc_hd__nand2_1 g5390(.A (n_473), .B (S1[27]), .Y (n_452));
  sky130_fd_sc_hd__nand2_4 g5393(.A (n_456), .B (n_481), .Y (S[26]));
  sky130_fd_sc_hd__nand2_1 g5394(.A (n_473), .B (S1[26]), .Y (n_456));
  sky130_fd_sc_hd__nand2_4 g5397(.A (n_460), .B (n_480), .Y (S[25]));
  sky130_fd_sc_hd__nand2_1 g5398(.A (n_473), .B (S1[25]), .Y (n_460));
  sky130_fd_sc_hd__nand2_2 g5401(.A (n_504), .B (n_468), .Y (n_469));
  sky130_fd_sc_hd__nand2_1 g17(.A (n_404), .B (C0[1]), .Y (n_468));
  sky130_fd_sc_hd__nand2_4 g5403(.A (n_470), .B (n_471), .Y (Cout));
  sky130_fd_sc_hd__nand2_2 g5404(.A (n_428), .B (C0[3]), .Y (n_470));
  sky130_fd_sc_hd__nand2_1 g18(.A (C1[3]), .B (n_478), .Y (n_471));
  sky130_fd_sc_hd__nand2_1 g5405(.A (n_473), .B (S1[31]), .Y (n_474));
  sky130_fd_sc_hd__nand2_4 g12(.A (n_415), .B (n_417), .Y (n_473));
  sky130_fd_sc_hd__nand2_4 g5406(.A (n_415), .B (n_417), .Y (n_478));
  sky130_fd_sc_hd__nand2_1 g5407(.A (n_479), .B (S0[25]), .Y (n_480));
  sky130_fd_sc_hd__inv_4 g5408(.A (n_478), .Y (n_479));
  sky130_fd_sc_hd__nand2_1 g5409(.A (n_479), .B (S0[26]), .Y (n_481));
  sky130_fd_sc_hd__nand2_1 g5410(.A (n_479), .B (S0[27]), .Y (n_482));
  sky130_fd_sc_hd__nand2_1 g5411(.A (n_479), .B (S0[28]), .Y (n_483));
  sky130_fd_sc_hd__nand2_1 g5412(.A (n_479), .B (S0[29]), .Y (n_484));
  sky130_fd_sc_hd__nand2_2 g5413(.A (n_485), .B (S0[31]), .Y (n_486));
  sky130_fd_sc_hd__inv_2 g5414(.A (n_478), .Y (n_485));
  sky130_fd_sc_hd__nand2_1 g5415(.A (n_485), .B (S0[30]), .Y (n_487));
  sky130_fd_sc_hd__buf_1 g5417(.A (C1[1]), .X (n_489));
  sky130_fd_sc_hd__nand2_1 g5246__5418(.A (n_493), .B (S1[20]), .Y
       (n_494));
  sky130_fd_sc_hd__nand2_1 g2(.A (n_468), .B (n_504), .Y (n_493));
  sky130_fd_sc_hd__nand2_1 g5248__5420(.A (n_493), .B (S1[19]), .Y
       (n_495));
  sky130_fd_sc_hd__nand2_1 g5251__5421(.A (n_493), .B (S1[18]), .Y
       (n_496));
  sky130_fd_sc_hd__nand2_1 g5261__5422(.A (n_493), .B (S1[17]), .Y
       (n_497));
  sky130_fd_sc_hd__nand2_1 g5255__5423(.A (n_493), .B (S1[16]), .Y
       (n_498));
  sky130_fd_sc_hd__nand2_1 g5252__5424(.A (n_493), .B (S1[21]), .Y
       (n_499));
  sky130_fd_sc_hd__clkbuf_1 g5426(.A (B[9]), .X (n_500));
  sky130_fd_sc_hd__clkbuf_1 g2558_dup(.A (B[9]), .X (n_501));
  sky130_fd_sc_hd__clkbuf_1 g5427(.A (A[9]), .X (n_502));
  sky130_fd_sc_hd__nand2_2 g5428(.A (n_1), .B (n_489), .Y (n_504));
endmodule

