
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr  7 2025 18:38:32 -03 (Apr  7 2025 21:38:32 UTC)

// Verification Directory fv/carry_select_adder_66668_32bits 

module full_adder_26_232(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_12, n_13;
  or g10 (n_12, wc, B);
  not gc (wc, A);
  or g11 (n_13, A, wc0);
  not gc0 (wc0, B);
  nand g12 (S, n_12, n_13);
  and g13 (Cout, A, B);
endmodule

module full_adder_218(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_16, n_25, n_30, n_56, n_57, n_58, n_59;
  nand g69 (Cout, n_16, n_25);
  or g70 (n_56, wc1, n_13);
  not gc1 (wc1, Cin);
  or g71 (n_57, Cin, wc2);
  not gc2 (wc2, n_13);
  nand g72 (S, n_56, n_57);
  nand g73 (n_25, B, n_30);
  nand g74 (n_16, A, Cin);
  or g75 (n_30, A, Cin);
  or g76 (n_58, wc3, B);
  not gc3 (wc3, A);
  or g77 (n_59, A, wc4);
  not gc4 (wc4, B);
  nand g78 (n_13, n_58, n_59);
endmodule

module full_adder_217(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc5, n_13);
  not gc5 (wc5, Cin);
  or g67 (n_52, Cin, wc6);
  not gc6 (wc6, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc7, B);
  not gc7 (wc7, A);
  or g72 (n_54, A, wc8);
  not gc8 (wc8, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_216(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc9, n_13);
  not gc9 (wc9, Cin);
  or g67 (n_52, Cin, wc10);
  not gc10 (wc10, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc11, B);
  not gc11 (wc11, A);
  or g72 (n_54, A, wc12);
  not gc12 (wc12, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_215(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc13, n_13);
  not gc13 (wc13, Cin);
  or g67 (n_52, Cin, wc14);
  not gc14 (wc14, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc15, B);
  not gc15 (wc15, A);
  or g72 (n_54, A, wc16);
  not gc16 (wc16, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_209(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc17, n_13);
  not gc17 (wc17, Cin);
  or g67 (n_52, Cin, wc18);
  not gc18 (wc18, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc19, B);
  not gc19 (wc19, A);
  or g72 (n_54, A, wc20);
  not gc20 (wc20, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module ripple_carry_adder_WIDTH6_5_235(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder_26_232 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]),
       .Cout (carry[0]));
  full_adder_218 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_217 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_216 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_215 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_209 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_32_234(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_14;
  nand g20 (n_14, A, B);
  or g21 (Cout, A, B);
  nand g22 (S, n_14, Cout);
endmodule

module full_adder_213(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_16, n_24, n_28, n_54, n_55, n_56, n_57;
  nand g65 (Cout, n_16, n_24);
  or g66 (n_54, wc21, n_13);
  not gc21 (wc21, Cin);
  or g67 (n_55, Cin, wc22);
  not gc22 (wc22, n_13);
  nand g68 (S, n_54, n_55);
  nand g69 (n_24, B, n_28);
  nand g70 (n_16, A, Cin);
  or g71 (n_28, Cin, A);
  or g72 (n_56, wc23, B);
  not gc23 (wc23, A);
  or g73 (n_57, A, wc24);
  not gc24 (wc24, B);
  nand g74 (n_13, n_56, n_57);
endmodule

module full_adder_212(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc25, n_13);
  not gc25 (wc25, Cin);
  or g67 (n_52, Cin, wc26);
  not gc26 (wc26, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc27, B);
  not gc27 (wc27, A);
  or g72 (n_54, A, wc28);
  not gc28 (wc28, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_211(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc29, n_13);
  not gc29 (wc29, Cin);
  or g67 (n_52, Cin, wc30);
  not gc30 (wc30, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc31, B);
  not gc31 (wc31, A);
  or g72 (n_54, A, wc32);
  not gc32 (wc32, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_210(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc33, n_13);
  not gc33 (wc33, Cin);
  or g67 (n_52, Cin, wc34);
  not gc34 (wc34, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc35, B);
  not gc35 (wc35, A);
  or g72 (n_54, A, wc36);
  not gc36 (wc36, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module ripple_carry_adder_WIDTH6_6_237(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder_32_234 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]),
       .Cout (carry[0]));
  full_adder_213 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_212 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_211 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_210 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_209 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_26(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_12, n_13;
  or g10 (n_12, wc37, B);
  not gc37 (wc37, A);
  or g11 (n_13, A, wc38);
  not gc38 (wc38, B);
  nand g12 (S, n_12, n_13);
  and g13 (Cout, A, B);
endmodule

module full_adder_208(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_15, n_16, n_24, n_25, n_27, n_28, n_29;
  wire n_30;
  or g40 (Cout, wc39, n_25);
  not gc39 (wc39, n_16);
  or g41 (n_27, wc40, n_13);
  not gc40 (wc40, Cin);
  or g42 (n_28, Cin, wc41);
  not gc41 (wc41, n_13);
  nand g43 (S, n_27, n_28);
  nand g44 (n_25, n_24, n_15);
  or g45 (n_29, wc42, B);
  not gc42 (wc42, A);
  or g46 (n_30, A, wc43);
  not gc43 (wc43, B);
  nand g47 (n_13, n_29, n_30);
  nand g48 (n_15, B, Cin);
  nand g49 (n_16, A, Cin);
  nand g50 (n_24, A, B);
endmodule

module full_adder_207(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_48, n_49, n_50, n_51, n_52, n_53;
  or g55 (n_48, B, A);
  nand g63 (Cout, n_23, n_49);
  or g64 (n_50, wc44, n_13);
  not gc44 (wc44, Cin);
  or g65 (n_51, Cin, wc45);
  not gc45 (wc45, n_13);
  nand g66 (S, n_50, n_51);
  nand g67 (n_49, n_48, Cin);
  nand g68 (n_23, A, B);
  or g69 (n_52, wc46, B);
  not gc46 (wc46, A);
  or g70 (n_53, A, wc47);
  not gc47 (wc47, B);
  nand g71 (n_13, n_52, n_53);
endmodule

module full_adder_206(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_48, n_49, n_50, n_51, n_52, n_53;
  or g55 (n_48, B, A);
  nand g63 (Cout, n_23, n_49);
  or g64 (n_50, wc48, n_13);
  not gc48 (wc48, Cin);
  or g65 (n_51, Cin, wc49);
  not gc49 (wc49, n_13);
  nand g66 (S, n_50, n_51);
  nand g67 (n_49, n_48, Cin);
  nand g68 (n_23, A, B);
  or g69 (n_52, wc50, B);
  not gc50 (wc50, A);
  or g70 (n_53, A, wc51);
  not gc51 (wc51, B);
  nand g71 (n_13, n_52, n_53);
endmodule

module full_adder_205(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g29 (n_19, A, B);
  nand g34 (Cout, n_24, n_25);
  or g35 (n_26, wc52, n_13);
  not gc52 (wc52, Cin);
  or g36 (n_27, Cin, wc53);
  not gc53 (wc53, n_13);
  nand g37 (S, n_26, n_27);
  nand g38 (n_24, n_19, Cin);
  nand g39 (n_25, A, B);
  or g40 (n_28, wc54, B);
  not gc54 (wc54, A);
  or g41 (n_29, A, wc55);
  not gc55 (wc55, B);
  nand g42 (n_13, n_28, n_29);
endmodule

module full_adder_199(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc56, n_13);
  not gc56 (wc56, Cin);
  or g64 (n_49, Cin, wc57);
  not gc57 (wc57, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc58, B);
  not gc58 (wc58, A);
  or g69 (n_51, A, wc59);
  not gc59 (wc59, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module ripple_carry_adder_WIDTH6_5_236(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder_26 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]), .Cout
       (carry[0]));
  full_adder_208 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_207 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_206 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_205 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_199 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_32(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_14;
  nand g20 (n_14, A, B);
  or g21 (Cout, A, B);
  nand g22 (S, n_14, Cout);
endmodule

module full_adder_203(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_16, n_24, n_28, n_54, n_55, n_56, n_57;
  nand g65 (Cout, n_16, n_24);
  or g66 (n_54, wc60, n_13);
  not gc60 (wc60, Cin);
  or g67 (n_55, Cin, wc61);
  not gc61 (wc61, n_13);
  nand g68 (S, n_54, n_55);
  nand g69 (n_24, B, n_28);
  nand g70 (n_16, A, Cin);
  or g71 (n_28, Cin, A);
  or g72 (n_56, wc62, B);
  not gc62 (wc62, A);
  or g73 (n_57, A, wc63);
  not gc63 (wc63, B);
  nand g74 (n_13, n_56, n_57);
endmodule

module full_adder_202(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc64, n_13);
  not gc64 (wc64, Cin);
  or g64 (n_49, Cin, wc65);
  not gc65 (wc65, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc66, B);
  not gc66 (wc66, A);
  or g69 (n_51, A, wc67);
  not gc67 (wc67, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module full_adder_201(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc68, n_13);
  not gc68 (wc68, Cin);
  or g64 (n_49, Cin, wc69);
  not gc69 (wc69, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc70, B);
  not gc70 (wc70, A);
  or g69 (n_51, A, wc71);
  not gc71 (wc71, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module full_adder_200(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc72, n_13);
  not gc72 (wc72, Cin);
  or g64 (n_49, Cin, wc73);
  not gc73 (wc73, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc74, B);
  not gc74 (wc74, A);
  or g69 (n_51, A, wc75);
  not gc75 (wc75, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module ripple_carry_adder_WIDTH6_6_238(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder_32 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]), .Cout
       (carry[0]));
  full_adder_203 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_202 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_201 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_200 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_199 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_26_231(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_12, n_13;
  or g10 (n_12, wc76, B);
  not gc76 (wc76, A);
  or g11 (n_13, A, wc77);
  not gc77 (wc77, B);
  nand g12 (S, n_12, n_13);
  and g13 (Cout, A, B);
endmodule

module full_adder_198(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_20, n_25, n_26, n_28, n_29, n_30, n_31;
  or g23 (n_20, A, B);
  nand g30 (Cout, n_25, n_26);
  or g31 (n_28, wc78, n_13);
  not gc78 (wc78, Cin);
  or g32 (n_29, Cin, wc79);
  not gc79 (wc79, n_13);
  nand g33 (S, n_28, n_29);
  nand g34 (n_25, n_20, Cin);
  nand g35 (n_26, A, B);
  or g36 (n_30, wc80, B);
  not gc80 (wc80, A);
  or g37 (n_31, A, wc81);
  not gc81 (wc81, B);
  nand g38 (n_13, n_30, n_31);
endmodule

module full_adder_197(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc82, n_13);
  not gc82 (wc82, Cin);
  or g28 (n_27, Cin, wc83);
  not gc83 (wc83, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc84, B);
  not gc84 (wc84, A);
  or g33 (n_29, A, wc85);
  not gc85 (wc85, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_196(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc86, n_13);
  not gc86 (wc86, Cin);
  or g28 (n_27, Cin, wc87);
  not gc87 (wc87, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc88, B);
  not gc88 (wc88, A);
  or g33 (n_29, A, wc89);
  not gc89 (wc89, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_195(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc90, n_13);
  not gc90 (wc90, Cin);
  or g28 (n_27, Cin, wc91);
  not gc91 (wc91, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc92, B);
  not gc92 (wc92, A);
  or g33 (n_29, A, wc93);
  not gc93 (wc93, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_189(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc94, n_13);
  not gc94 (wc94, Cin);
  or g28 (n_27, Cin, wc95);
  not gc95 (wc95, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc96, B);
  not gc96 (wc96, A);
  or g33 (n_29, A, wc97);
  not gc97 (wc97, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module ripple_carry_adder_WIDTH6_5(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder_26_231 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]),
       .Cout (carry[0]));
  full_adder_198 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_197 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_196 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_195 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_189 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_32_233(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_14;
  nand g20 (n_14, A, B);
  or g21 (Cout, A, B);
  nand g22 (S, n_14, Cout);
endmodule

module full_adder_193(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc98, n_13);
  not gc98 (wc98, Cin);
  or g28 (n_27, Cin, wc99);
  not gc99 (wc99, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc100, B);
  not gc100 (wc100, A);
  or g33 (n_29, A, wc101);
  not gc101 (wc101, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_192(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc102, n_13);
  not gc102 (wc102, Cin);
  or g28 (n_27, Cin, wc103);
  not gc103 (wc103, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc104, B);
  not gc104 (wc104, A);
  or g33 (n_29, A, wc105);
  not gc105 (wc105, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_191(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc106, n_13);
  not gc106 (wc106, Cin);
  or g28 (n_27, Cin, wc107);
  not gc107 (wc107, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc108, B);
  not gc108 (wc108, A);
  or g33 (n_29, A, wc109);
  not gc109 (wc109, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_190(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc110, n_13);
  not gc110 (wc110, Cin);
  or g28 (n_27, Cin, wc111);
  not gc111 (wc111, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc112, B);
  not gc112 (wc112, A);
  or g33 (n_29, A, wc113);
  not gc113 (wc113, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module ripple_carry_adder_WIDTH6_6(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder_32_233 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]),
       .Cout (carry[0]));
  full_adder_193 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_192 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_191 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_190 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_189 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_6(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_12, n_13;
  or g10 (n_12, wc114, B);
  not gc114 (wc114, A);
  or g11 (n_13, A, wc115);
  not gc115 (wc115, B);
  nand g12 (S, n_12, n_13);
  and g13 (Cout, A, B);
endmodule

module full_adder_225(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_20, n_25, n_26, n_28, n_29, n_30, n_31;
  or g23 (n_20, A, B);
  nand g30 (Cout, n_25, n_26);
  or g31 (n_28, wc116, n_13);
  not gc116 (wc116, Cin);
  or g32 (n_29, Cin, wc117);
  not gc117 (wc117, n_13);
  nand g33 (S, n_28, n_29);
  nand g34 (n_25, n_20, Cin);
  nand g35 (n_26, A, B);
  or g36 (n_30, wc118, B);
  not gc118 (wc118, A);
  or g37 (n_31, A, wc119);
  not gc119 (wc119, B);
  nand g38 (n_13, n_30, n_31);
endmodule

module full_adder_224(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc120, n_13);
  not gc120 (wc120, Cin);
  or g28 (n_27, Cin, wc121);
  not gc121 (wc121, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc122, B);
  not gc122 (wc122, A);
  or g33 (n_29, A, wc123);
  not gc123 (wc123, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_223(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc124, n_13);
  not gc124 (wc124, Cin);
  or g28 (n_27, Cin, wc125);
  not gc125 (wc125, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc126, B);
  not gc126 (wc126, A);
  or g33 (n_29, A, wc127);
  not gc127 (wc127, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_222(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc128, n_13);
  not gc128 (wc128, Cin);
  or g28 (n_27, Cin, wc129);
  not gc129 (wc129, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc130, B);
  not gc130 (wc130, A);
  or g33 (n_29, A, wc131);
  not gc131 (wc131, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_221(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc132, n_13);
  not gc132 (wc132, Cin);
  or g28 (n_27, Cin, wc133);
  not gc133 (wc133, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc134, B);
  not gc134 (wc134, A);
  or g33 (n_29, A, wc135);
  not gc135 (wc135, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_220(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc136, n_13);
  not gc136 (wc136, Cin);
  or g28 (n_27, Cin, wc137);
  not gc137 (wc137, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc138, B);
  not gc138 (wc138, A);
  or g33 (n_29, A, wc139);
  not gc139 (wc139, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_182(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc140, n_13);
  not gc140 (wc140, Cin);
  or g28 (n_27, Cin, wc141);
  not gc141 (wc141, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc142, B);
  not gc142 (wc142, A);
  or g33 (n_29, A, wc143);
  not gc143 (wc143, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module ripple_carry_adder_WIDTH8(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder_6 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]), .Cout
       (carry[0]));
  full_adder_225 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_224 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_223 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_222 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_221 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_220 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_182 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_50(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_14;
  nand g20 (n_14, A, B);
  or g21 (Cout, A, B);
  nand g22 (S, n_14, Cout);
endmodule

module full_adder_188(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc144, n_13);
  not gc144 (wc144, Cin);
  or g28 (n_27, Cin, wc145);
  not gc145 (wc145, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc146, B);
  not gc146 (wc146, A);
  or g33 (n_29, A, wc147);
  not gc147 (wc147, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_187(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc148, n_13);
  not gc148 (wc148, Cin);
  or g28 (n_27, Cin, wc149);
  not gc149 (wc149, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc150, B);
  not gc150 (wc150, A);
  or g33 (n_29, A, wc151);
  not gc151 (wc151, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_186(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc152, n_13);
  not gc152 (wc152, Cin);
  or g28 (n_27, Cin, wc153);
  not gc153 (wc153, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc154, B);
  not gc154 (wc154, A);
  or g33 (n_29, A, wc155);
  not gc155 (wc155, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_185(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc156, n_13);
  not gc156 (wc156, Cin);
  or g28 (n_27, Cin, wc157);
  not gc157 (wc157, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc158, B);
  not gc158 (wc158, A);
  or g33 (n_29, A, wc159);
  not gc159 (wc159, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_184(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc160, n_13);
  not gc160 (wc160, Cin);
  or g28 (n_27, Cin, wc161);
  not gc161 (wc161, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc162, B);
  not gc162 (wc162, A);
  or g33 (n_29, A, wc163);
  not gc163 (wc163, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_183(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc164, n_13);
  not gc164 (wc164, Cin);
  or g28 (n_27, Cin, wc165);
  not gc165 (wc165, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc166, B);
  not gc166 (wc166, A);
  or g33 (n_29, A, wc167);
  not gc167 (wc167, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module ripple_carry_adder_WIDTH8_1(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder_50 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]), .Cout
       (carry[0]));
  full_adder_188 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_187 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_186 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_185 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_184 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_183 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_182 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_16, n_25, n_30, n_56, n_57, n_58, n_59;
  nand g69 (Cout, n_16, n_25);
  or g70 (n_56, wc168, n_13);
  not gc168 (wc168, Cin);
  or g71 (n_57, Cin, wc169);
  not gc169 (wc169, n_13);
  nand g72 (S, n_56, n_57);
  nand g73 (n_25, B, n_30);
  nand g74 (n_16, A, Cin);
  or g75 (n_30, A, Cin);
  or g76 (n_58, wc170, B);
  not gc170 (wc170, A);
  or g77 (n_59, A, wc171);
  not gc171 (wc171, B);
  nand g78 (n_13, n_58, n_59);
endmodule

module full_adder_230(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc172, n_13);
  not gc172 (wc172, Cin);
  or g67 (n_52, Cin, wc173);
  not gc173 (wc173, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc174, B);
  not gc174 (wc174, A);
  or g72 (n_54, A, wc175);
  not gc175 (wc175, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_229(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc176, n_13);
  not gc176 (wc176, Cin);
  or g67 (n_52, Cin, wc177);
  not gc177 (wc177, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc178, B);
  not gc178 (wc178, A);
  or g72 (n_54, A, wc179);
  not gc179 (wc179, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_228(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc180, n_13);
  not gc180 (wc180, Cin);
  or g67 (n_52, Cin, wc181);
  not gc181 (wc181, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc182, B);
  not gc182 (wc182, A);
  or g72 (n_54, A, wc183);
  not gc183 (wc183, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_227(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc184, n_13);
  not gc184 (wc184, Cin);
  or g67 (n_52, Cin, wc185);
  not gc185 (wc185, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc186, B);
  not gc186 (wc186, A);
  or g72 (n_54, A, wc187);
  not gc187 (wc187, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_226(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc188, n_13);
  not gc188 (wc188, Cin);
  or g67 (n_52, Cin, wc189);
  not gc189 (wc189, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc190, B);
  not gc190 (wc190, A);
  or g72 (n_54, A, wc191);
  not gc191 (wc191, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module ripple_carry_adder_WIDTH6(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder F1A(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (carry[0]));
  full_adder_230 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_229 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_228 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_227 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_226 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module carry_select_adder_66668_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire [31:0] S0;
  wire [4:0] C0;
  wire [31:0] S1;
  wire [4:0] C1;
  wire [4:0] C_mid;
  wire n_110, n_117, n_124, n_146, n_147, n_164, n_165, n_170;
  wire n_171, n_176, n_177, n_182, n_183, n_188, n_189, n_194;
  wire n_195, n_200, n_201, n_206, n_207, n_212, n_213, n_218;
  wire n_219, n_224, n_225, n_230, n_231, n_236, n_237, n_242;
  wire n_243, n_248, n_249, n_254, n_255, n_260, n_261, n_266;
  wire n_267, n_272, n_273, n_278, n_279, n_284, n_285, n_290;
  wire n_291, n_296, n_297, n_302, n_303, n_308, n_309, n_314;
  wire n_315, n_320, n_321, n_3615, n_3616, n_6720, n_6721, n_6805;
  wire n_6806, n_6808, n_6809, n_9029, n_9030, n_9031, n_9032, n_9033;
  wire n_9034, n_9035, n_9036, n_9037, n_9038;
  ripple_carry_adder_WIDTH6_5_235 \CSA_BLOCKS[1].RCA_C0 (.A (A[11:6]),
       .B (B[11:6]), .Cin (1'b0), .S (S0[11:6]), .Cout (C0[1]));
  ripple_carry_adder_WIDTH6_6_237 \CSA_BLOCKS[1].RCA_C1 (.A (A[11:6]),
       .B (B[11:6]), .Cin (1'b1), .S (S1[11:6]), .Cout (C1[1]));
  ripple_carry_adder_WIDTH6_5_236 \CSA_BLOCKS[2].RCA_C0 (.A (A[17:12]),
       .B (B[17:12]), .Cin (1'b0), .S (S0[17:12]), .Cout (C0[2]));
  ripple_carry_adder_WIDTH6_6_238 \CSA_BLOCKS[2].RCA_C1 (.A (A[17:12]),
       .B (B[17:12]), .Cin (1'b1), .S (S1[17:12]), .Cout (C1[2]));
  ripple_carry_adder_WIDTH6_5 \CSA_BLOCKS[3].RCA_C0 (.A (A[23:18]), .B
       (B[23:18]), .Cin (1'b0), .S (S0[23:18]), .Cout (C0[3]));
  ripple_carry_adder_WIDTH6_6 \CSA_BLOCKS[3].RCA_C1 (.A (A[23:18]), .B
       (B[23:18]), .Cin (1'b1), .S (S1[23:18]), .Cout (C1[3]));
  ripple_carry_adder_WIDTH8 \CSA_BLOCKS[4].RCA_C0 (.A (A[31:24]), .B
       (B[31:24]), .Cin (1'b0), .S (S0[31:24]), .Cout (C0[4]));
  ripple_carry_adder_WIDTH8_1 \CSA_BLOCKS[4].RCA_C1 (.A (A[31:24]), .B
       (B[31:24]), .Cin (1'b1), .S (S1[31:24]), .Cout (C1[4]));
  ripple_carry_adder_WIDTH6 RCA_LSB(.A (A[5:0]), .B (B[5:0]), .Cin
       (Cin), .S (S[5:0]), .Cout (C_mid[0]));
  nand g9703 (S[23], n_290, n_291);
  nand g9704 (S[18], n_320, n_321);
  nand g9705 (S[30], n_170, n_171);
  nand g9706 (S[19], n_314, n_315);
  nand g9707 (S[24], n_206, n_207);
  nand g9708 (S[27], n_188, n_189);
  nand g9709 (S[20], n_308, n_309);
  nand g9710 (S[29], n_176, n_177);
  nand g9711 (S[25], n_200, n_201);
  nand g9712 (S[21], n_302, n_303);
  nand g9713 (S[31], n_164, n_165);
  nand g9714 (S[28], n_182, n_183);
  nand g9715 (S[22], n_296, n_297);
  nand g9716 (S[26], n_194, n_195);
  nand g9717 (Cout, n_212, n_213);
  nand g9718 (n_195, n_124, S1[26]);
  or g9719 (n_212, n_124, wc192);
  not gc192 (wc192, C0[4]);
  nand g9720 (n_207, n_124, S1[24]);
  or g9721 (n_206, n_124, wc193);
  not gc193 (wc193, S0[24]);
  nand g9722 (n_321, n_117, S1[18]);
  or g9723 (n_320, n_117, wc194);
  not gc194 (wc194, S0[18]);
  nand g9724 (n_315, n_117, S1[19]);
  or g9725 (n_314, n_117, wc195);
  not gc195 (wc195, S0[19]);
  nand g9726 (n_309, n_117, S1[20]);
  or g9727 (n_308, n_117, wc196);
  not gc196 (wc196, S0[20]);
  nand g9728 (n_303, n_117, S1[21]);
  or g9729 (n_302, n_117, wc197);
  not gc197 (wc197, S0[21]);
  nand g9730 (n_297, n_117, S1[22]);
  or g9731 (n_296, n_117, wc198);
  not gc198 (wc198, S0[22]);
  nand g9732 (n_291, n_117, S1[23]);
  or g9733 (n_290, n_117, wc199);
  not gc199 (wc199, S0[23]);
  or g9734 (n_188, n_124, wc200);
  not gc200 (wc200, S0[27]);
  nand g9735 (n_201, n_124, S1[25]);
  nand g9736 (n_189, n_124, S1[27]);
  or g9737 (n_164, n_124, wc201);
  not gc201 (wc201, S0[31]);
  nand g9738 (n_165, n_124, S1[31]);
  or g9739 (n_170, n_124, wc202);
  not gc202 (wc202, S0[30]);
  or g9740 (n_200, n_124, wc203);
  not gc203 (wc203, S0[25]);
  nand g9741 (n_171, n_124, S1[30]);
  or g9742 (n_176, n_124, wc204);
  not gc204 (wc204, S0[29]);
  nand g9743 (n_177, n_124, S1[29]);
  or g9744 (n_182, n_124, wc205);
  not gc205 (wc205, S0[28]);
  or g9745 (n_194, n_124, wc206);
  not gc206 (wc206, S0[26]);
  nand g9746 (n_213, n_124, C1[4]);
  nand g9747 (n_183, n_124, S1[28]);
  nand g9748 (S[13], n_278, n_279);
  nand g9749 (S[12], n_284, n_285);
  nand g9750 (S[14], n_272, n_273);
  nand g9751 (n_124, n_6808, n_6809);
  or g9752 (n_117, n_9037, n_9038);
  nand g9753 (S[15], n_266, n_267);
  nand g9754 (S[17], n_254, n_255);
  nand g9755 (S[16], n_260, n_261);
  nand g9756 (n_261, n_110, S1[16]);
  or g9757 (n_260, n_110, wc207);
  not gc207 (wc207, S0[16]);
  or g9758 (n_266, n_110, wc208);
  not gc208 (wc208, S0[15]);
  nand g9759 (n_255, n_110, S1[17]);
  or g9760 (n_254, n_110, wc209);
  not gc209 (wc209, S0[17]);
  nand g9761 (n_267, n_110, S1[15]);
  or g9762 (n_272, n_110, wc210);
  not gc210 (wc210, S0[14]);
  nand g9763 (n_273, n_110, S1[14]);
  or g9764 (n_278, n_110, wc211);
  not gc211 (wc211, S0[13]);
  nand g9765 (n_279, n_110, S1[13]);
  or g9766 (n_284, n_110, wc212);
  not gc212 (wc212, S0[12]);
  nand g9767 (n_9037, n_9033, n_9034);
  nand g9768 (n_9038, n_9035, n_9036);
  nand g9771 (n_285, n_110, S1[12]);
  nand g9772 (S[10], n_224, n_225);
  or g9774 (n_9036, wc213, n_9032);
  not gc213 (wc213, C1[1]);
  nand g9775 (S[11], n_218, n_219);
  nand g9776 (n_6806, n_6720, n_6721);
  nand g9777 (S[6], n_248, n_249);
  nand g9778 (n_110, n_146, n_147);
  or g9779 (n_9033, C0[1], n_9029);
  nand g9780 (S[9], n_230, n_231);
  nand g9781 (S[7], n_242, n_243);
  or g9782 (n_9034, wc214, n_9030);
  not gc214 (wc214, C0[1]);
  nand g9783 (S[8], n_236, n_237);
  nand g9784 (n_6805, n_3615, n_3616);
  or g9785 (n_9035, C1[1], n_9031);
  nand g9786 (n_225, C_mid[0], S1[10]);
  or g9787 (n_224, C_mid[0], wc215);
  not gc215 (wc215, S0[10]);
  nand g9788 (n_219, C_mid[0], S1[11]);
  or g9789 (n_218, C_mid[0], wc216);
  not gc216 (wc216, S0[11]);
  or g9790 (n_230, C_mid[0], wc217);
  not gc217 (wc217, S0[9]);
  nand g9791 (n_231, C_mid[0], S1[9]);
  or g9792 (n_236, C_mid[0], wc218);
  not gc218 (wc218, S0[8]);
  nand g9793 (n_237, C_mid[0], S1[8]);
  or g9794 (n_242, C_mid[0], wc219);
  not gc219 (wc219, S0[7]);
  nand g9795 (n_243, C_mid[0], S1[7]);
  or g9796 (n_147, C_mid[0], wc220);
  not gc220 (wc220, C0[1]);
  or g9797 (n_248, C_mid[0], wc221);
  not gc221 (wc221, S0[6]);
  nand g9798 (n_249, C_mid[0], S1[6]);
  or g9799 (n_9029, C_mid[0], wc222);
  not gc222 (wc222, C0[2]);
  or g9800 (n_9030, C_mid[0], wc223);
  not gc223 (wc223, C1[2]);
  nand g9801 (n_9031, C_mid[0], C0[2]);
  nand g9802 (n_9032, C_mid[0], C1[2]);
  or g9803 (n_6721, C1[3], wc224);
  not gc224 (wc224, C1[2]);
  or g9804 (n_6720, C1[2], C0[3]);
  nand g9805 (n_146, C_mid[0], C1[1]);
  or g9808 (n_3616, C1[3], wc225);
  not gc225 (wc225, C0[2]);
  or g9809 (n_3615, C0[2], C0[3]);
  or g9811 (n_6808, n_6805, n_110);
  or g9812 (n_6809, wc226, n_6806);
  not gc226 (wc226, n_110);
endmodule

