
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr  7 2025 18:56:03 -03 (Apr  7 2025 21:56:03 UTC)

// Verification Directory fv/carry_select_adder_68810_32bits 

module full_adder_32_225(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED, n_1, n_12, n_13;
  sky130_fd_sc_hd__inv_2 g38(.A (A), .Y (n_1));
  sky130_fd_sc_hd__ha_1 g42__44(.A (n_13), .B (n_1), .COUT
       (UNCONNECTED), .SUM (S));
  sky130_fd_sc_hd__buf_1 g1(.A (n_12), .X (n_13));
  sky130_fd_sc_hd__inv_2 g45(.A (B), .Y (n_12));
  sky130_fd_sc_hd__nor2_4 g34__46(.A (n_12), .B (n_1), .Y (Cout));
endmodule

module full_adder_219(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_4, n_5, n_7, n_14, n_15, n_16;
  wire n_18;
  sky130_fd_sc_hd__xor2_1 g193__4319(.A (n_4), .B (n_7), .X (S));
  sky130_fd_sc_hd__xor2_1 g195__5526(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_4 g197__3680(.A (n_1), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__clkbuf_1 g198(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g200(.A (n_14), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g203(.A (n_15), .Y (n_0));
  sky130_fd_sc_hd__clkinv_2 g205(.A (A), .Y (n_14));
  sky130_fd_sc_hd__clkinv_2 g206(.A (B), .Y (n_15));
  sky130_fd_sc_hd__nand2_2 g196__208(.A (n_15), .B (n_14), .Y (n_16));
  sky130_fd_sc_hd__nand2_4 g14(.A (n_18), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g15(.A (n_16), .B (Cin), .Y (n_18));
endmodule

module full_adder_218(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_4 g122__1617(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__2802(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__1705(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g125__5122(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g126__8246(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_4 g127__7098(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__clkbuf_1 g128(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g130(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g131(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g133(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g134(.A (B), .Y (n_2));
endmodule

module full_adder_217(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__6131(.A (n_6), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__1881(.A (n_5), .B (n_3), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__5115(.A (Cin), .B (n_0), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__7482(.A (n_1), .B (n_2), .X (n_5));
  sky130_fd_sc_hd__nand2_1 g127__4733(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_3));
  sky130_fd_sc_hd__clkbuf_1 g130(.A (A), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g132(.A (B), .X (n_1));
  sky130_fd_sc_hd__or2_1 g2__6161(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_216(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__9315(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__9945(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__2883(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__2346(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_2 g126__1666(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__7410(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
endmodule

module full_adder_215(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__6417(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__5477(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__2398(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__5107(.A (n_0), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_1 g126__6260(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__4319(.A (n_0), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g128(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__buf_1 g132(.A (B), .X (n_0));
endmodule

module full_adder_214(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g123__8428(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g124__5526(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g125__6783(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g126__3680(.A (n_0), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_1 g127__1617(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g128__2802(.A (n_0), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g129(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__buf_1 g133(.A (B), .X (n_0));
endmodule

module full_adder_213(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_4, n_6, n_14, n_15, n_16;
  sky130_fd_sc_hd__nand2_4 g123__1705(.A (n_6), .B (n_16), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g124__5122(.A (n_14), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g125__8246(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__or2_4 g127__6131(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__buf_2 g129(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__ha_1 g2(.A (B), .B (A), .COUT (n_15), .SUM (n_14));
  sky130_fd_sc_hd__clkinv_2 g3(.A (n_15), .Y (n_16));
endmodule

module ripple_carry_adder_WIDTH8(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z;
  full_adder_32_225 F1A(.A (A[0]), .B (B[0]), .Cin
       (UNCONNECTED_HIER_Z), .S (S[0]), .Cout (carry[0]));
  full_adder_219 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_218 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_217 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_216 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_215 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_214 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_213 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_40_226(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_22, n_23;
  sky130_fd_sc_hd__dlygate4sd2_1 g1(.A (n_22), .X (n_13));
  sky130_fd_sc_hd__xnor2_1 g2__68(.A (n_19), .B (n_13), .Y (S));
  sky130_fd_sc_hd__dlygate4sd1_1 g69(.A (n_23), .X (n_19));
  sky130_fd_sc_hd__nand2_4 g9(.A (n_22), .B (n_23), .Y (Cout));
  sky130_fd_sc_hd__clkinv_2 g11(.A (B), .Y (n_22));
  sky130_fd_sc_hd__clkinv_2 g10(.A (A), .Y (n_23));
endmodule

module full_adder_203(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_6, n_7, n_8, n_14, n_15;
  wire n_16;
  sky130_fd_sc_hd__xor2_1 g180__6161(.A (n_4), .B (n_7), .X (S));
  sky130_fd_sc_hd__nand2_4 g181__9315(.A (n_6), .B (Cin), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g182__9945(.A (n_14), .B (n_15), .X (n_7));
  sky130_fd_sc_hd__nand2_2 g183__2883(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__clkbuf_1 g185(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g188(.A (A), .Y (n_3));
  sky130_fd_sc_hd__clkinv_2 g191(.A (B), .Y (n_2));
  sky130_fd_sc_hd__inv_2 g192(.A (n_2), .Y (n_14));
  sky130_fd_sc_hd__inv_2 g193(.A (n_3), .Y (n_15));
  sky130_fd_sc_hd__nand2_4 g179__194(.A (n_8), .B (n_16), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g184__195(.A (n_15), .B (n_14), .Y (n_16));
endmodule

module full_adder_202(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_4 g122__1666(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__7410(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__6417(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g125__5477(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_2 g126__2398(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_4 g127__5107(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g130(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g131(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g133(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g134(.A (B), .Y (n_2));
endmodule

module full_adder_201(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_5, n_12, n_13, n_14;
  sky130_fd_sc_hd__xor2_1 g123__4319(.A (n_5), .B (n_3), .X (S));
  sky130_fd_sc_hd__xor2_1 g125__5526(.A (n_1), .B (n_2), .X (n_5));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_3));
  sky130_fd_sc_hd__clkbuf_1 g130(.A (A), .X (n_2));
  sky130_fd_sc_hd__buf_2 g132(.A (B), .X (n_1));
  sky130_fd_sc_hd__nand2_4 g20(.A (n_13), .B (n_14), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g21(.A (Cin), .B (n_12), .Y (n_13));
  sky130_fd_sc_hd__or2_4 g23(.A (A), .B (B), .X (n_12));
  sky130_fd_sc_hd__nand2_1 g22(.A (B), .B (A), .Y (n_14));
endmodule

module full_adder_200(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__1617(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__2802(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__1705(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__5122(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__8246(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__7098(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
endmodule

module full_adder_199(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__6131(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__1881(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__5115(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__7482(.A (B), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__4733(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__6161(.A (B), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g130(.A (A), .X (n_1));
endmodule

module full_adder_198(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g122__9315(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g123__9945(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g124__2883(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g125__2346(.A (B), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g126__1666(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g127__7410(.A (B), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g128(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g130(.A (A), .X (n_1));
endmodule

module full_adder_197(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g123__6417(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g124__5477(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g125__2398(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g126__5107(.A (B), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g127__6260(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_8 g128__4319(.A (B), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g129(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__buf_1 g130(.A (A), .X (n_1));
endmodule

module ripple_carry_adder_WIDTH8_3_228(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z0;
  full_adder_40_226 F1A(.A (A[0]), .B (B[0]), .Cin
       (UNCONNECTED_HIER_Z0), .S (S[0]), .Cout (carry[0]));
  full_adder_203 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_202 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_201 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_200 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_199 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_198 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_197 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_32(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_6, n_8, n_9;
  sky130_fd_sc_hd__nor2_2 g34__8428(.A (n_6), .B (n_9), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g2__5526(.A (n_6), .B (n_8), .X (S));
  sky130_fd_sc_hd__inv_4 fopt39(.A (B), .Y (n_6));
  sky130_fd_sc_hd__clkbuf_1 fopt40(.A (n_9), .X (n_8));
  sky130_fd_sc_hd__inv_2 fopt41(.A (A), .Y (n_9));
endmodule

module full_adder_196(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_4, n_24, n_25, n_32, n_54, n_55, n_56, n_63;
  wire n_64, n_65, n_66, n_67;
  sky130_fd_sc_hd__nand2_2 g161__6783(.A (n_32), .B (n_25), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g162__3680(.A (n_4), .B (n_24), .X (S));
  sky130_fd_sc_hd__buf_2 g167(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__xor2_1 g164__180(.A (n_54), .B (n_67), .X (n_24));
  sky130_fd_sc_hd__nand2_2 g166__182(.A (n_55), .B (n_65), .Y (n_25));
  sky130_fd_sc_hd__nand2_2 g163__187(.A (n_64), .B (Cin), .Y (n_32));
  sky130_fd_sc_hd__clkbuf_1 fopt(.A (n_55), .X (n_54));
  sky130_fd_sc_hd__clkinv_1 fopt199(.A (n_56), .Y (n_55));
  sky130_fd_sc_hd__inv_2 fopt200(.A (B), .Y (n_56));
  sky130_fd_sc_hd__nand2_2 g165__207(.A (n_63), .B (n_56), .Y (n_64));
  sky130_fd_sc_hd__clkinv_4 fopt208(.A (A), .Y (n_63));
  sky130_fd_sc_hd__clkinv_2 fopt209(.A (n_63), .Y (n_65));
  sky130_fd_sc_hd__inv_1 fopt210(.A (n_66), .Y (n_67));
  sky130_fd_sc_hd__dlymetal6s2s_1 g1(.A (n_63), .X (n_66));
endmodule

module full_adder_195(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_2 g119__8246(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g120__7098(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__nand2_2 g121__6131(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g122__1881(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g123__5115(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_2 g124__7482(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__buf_2 g125(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g127(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g128(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g130(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g131(.A (B), .Y (n_2));
endmodule

module full_adder_194(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_4, n_5, n_15, n_16;
  sky130_fd_sc_hd__nand2_4 g117__4733(.A (n_16), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g118__6161(.A (n_5), .B (n_3), .X (S));
  sky130_fd_sc_hd__xor2_1 g120__9945(.A (n_1), .B (n_2), .X (n_5));
  sky130_fd_sc_hd__nand2_2 g122__2883(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__buf_2 g123(.A (Cin), .X (n_3));
  sky130_fd_sc_hd__clkbuf_1 g125(.A (A), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g127(.A (B), .X (n_1));
  sky130_fd_sc_hd__nand2_4 g7(.A (Cin), .B (n_15), .Y (n_16));
  sky130_fd_sc_hd__or2_1 g8(.A (A), .B (B), .X (n_15));
endmodule

module full_adder_193(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_12;
  sky130_fd_sc_hd__xor2_1 g118__7410(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__xor2_1 g120__5477(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_4 g121__2398(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g122__5107(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g123(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__nand2_4 g14(.A (n_12), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g15(.A (Cin), .B (n_4), .Y (n_12));
endmodule

module full_adder_192(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_4, n_5, n_15;
  sky130_fd_sc_hd__xor2_1 g118__4319(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__xor2_1 g120__5526(.A (B), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g121__6783(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g122__3680(.A (B), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g123(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g125(.A (A), .X (n_1));
  sky130_fd_sc_hd__nand2_4 g14(.A (n_15), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g15(.A (Cin), .B (n_4), .Y (n_15));
endmodule

module full_adder_191(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g117__1617(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g118__2802(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g119__1705(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g120__5122(.A (B), .B (n_1), .X (n_5));
  sky130_fd_sc_hd__or2_4 g121__8246(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g122__7098(.A (B), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g123(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g125(.A (A), .X (n_1));
endmodule

module full_adder_190(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_3, n_4, n_12, n_14;
  sky130_fd_sc_hd__or2_4 g121__4733(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_2 g122__6161(.A (B), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_1 g124(.A (A), .X (n_1));
  sky130_fd_sc_hd__nand2_4 g14(.A (n_12), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g15(.A (Cin), .B (n_4), .Y (n_12));
  sky130_fd_sc_hd__buf_2 fopt(.A (Cin), .X (n_14));
  sky130_fd_sc_hd__xor3_1 g2(.A (B), .B (n_1), .C (n_14), .X (S));
endmodule

module ripple_carry_adder_WIDTH8_227(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z1;
  full_adder_32 F1A(.A (A[0]), .B (B[0]), .Cin (UNCONNECTED_HIER_Z1),
       .S (S[0]), .Cout (carry[0]));
  full_adder_196 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_195 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_194 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_193 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_192 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_191 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_190 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_40(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_6, n_8;
  sky130_fd_sc_hd__nand2_2 g56__9315(.A (n_8), .B (n_6), .Y (Cout));
  sky130_fd_sc_hd__xnor2_1 g2__9945(.A (n_8), .B (n_6), .Y (S));
  sky130_fd_sc_hd__inv_4 fopt61(.A (B), .Y (n_6));
  sky130_fd_sc_hd__clkinv_4 fopt63(.A (A), .Y (n_8));
endmodule

module full_adder_189(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_4, n_20, n_21, n_50, n_51, n_52, n_54, n_55;
  wire n_56, n_58, n_59, n_60;
  sky130_fd_sc_hd__xor2_1 g149__2346(.A (n_4), .B (n_20), .X (S));
  sky130_fd_sc_hd__buf_2 g154(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__xor2_1 g151__163(.A (n_54), .B (n_59), .X (n_20));
  sky130_fd_sc_hd__nand2_4 g153__165(.A (n_55), .B (n_60), .Y (n_21));
  sky130_fd_sc_hd__nand2_4 g22(.A (n_52), .B (n_21), .Y (Cout));
  sky130_fd_sc_hd__inv_2 g23(.A (n_51), .Y (n_52));
  sky130_fd_sc_hd__a21oi_2 g24(.A1 (n_58), .A2 (n_56), .B1 (n_50), .Y
       (n_51));
  sky130_fd_sc_hd__clkinv_1 g25(.A (Cin), .Y (n_50));
  sky130_fd_sc_hd__clkbuf_1 fopt(.A (n_55), .X (n_54));
  sky130_fd_sc_hd__clkbuf_2 fopt185(.A (B), .X (n_55));
  sky130_fd_sc_hd__inv_2 fopt186(.A (B), .Y (n_56));
  sky130_fd_sc_hd__inv_2 fopt187(.A (A), .Y (n_58));
  sky130_fd_sc_hd__clkbuf_1 fopt188(.A (n_60), .X (n_59));
  sky130_fd_sc_hd__clkbuf_2 fopt189(.A (A), .X (n_60));
endmodule

module full_adder_188(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_4 g119__2398(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g120__5107(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__nand2_4 g121__6260(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g122__4319(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_2 g123__8428(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_4 g124__5526(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__buf_2 g125(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g127(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g128(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g130(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g131(.A (B), .Y (n_2));
endmodule

module full_adder_187(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g116__6783(.A (n_6), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g117__3680(.A (n_5), .B (n_3), .X (S));
  sky130_fd_sc_hd__nand2_4 g118__1617(.A (Cin), .B (n_0), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g119__2802(.A (n_1), .B (n_2), .X (n_5));
  sky130_fd_sc_hd__nand2_1 g121__1705(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__buf_2 g122(.A (Cin), .X (n_3));
  sky130_fd_sc_hd__clkbuf_1 g124(.A (A), .X (n_2));
  sky130_fd_sc_hd__buf_2 g126(.A (B), .X (n_1));
  sky130_fd_sc_hd__or2_4 g2__5122(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_186(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g116__8246(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g117__7098(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g118__6131(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g119__1881(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_4 g120__5115(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g121__7482(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g122(.A (Cin), .X (n_2));
endmodule

module full_adder_185(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g116__4733(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g117__6161(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g118__9315(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g119__9945(.A (n_0), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_4 g120__2883(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g121__2346(.A (n_0), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g122(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__buf_1 g126(.A (B), .X (n_0));
endmodule

module full_adder_184(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g116__1666(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g117__7410(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g118__6417(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g119__5477(.A (n_0), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_4 g120__2398(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_4 g121__5107(.A (n_0), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g122(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__buf_1 g126(.A (B), .X (n_0));
endmodule

module full_adder_183(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_4, n_5, n_13, n_15;
  sky130_fd_sc_hd__xor2_1 g117__4319(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__xor2_1 g119__5526(.A (n_0), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_4 g120__6783(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__buf_2 g122(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__buf_1 g124(.A (B), .X (n_0));
  sky130_fd_sc_hd__nand2_4 g21(.A (A), .B (n_0), .Y (n_13));
  sky130_fd_sc_hd__nand2_4 g14(.A (n_15), .B (n_13), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g15(.A (Cin), .B (n_4), .Y (n_15));
endmodule

module ripple_carry_adder_WIDTH8_3(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire UNCONNECTED_HIER_Z2;
  full_adder_40 F1A(.A (A[0]), .B (B[0]), .Cin (UNCONNECTED_HIER_Z2),
       .S (S[0]), .Cout (carry[0]));
  full_adder_189 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_188 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_187 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_186 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_185 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_184 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_183 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_14(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_8;
  sky130_fd_sc_hd__inv_2 g38(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xor2_1 g2__40(.A (n_8), .B (n_1), .X (S));
  sky130_fd_sc_hd__inv_2 g41(.A (B), .Y (n_8));
  sky130_fd_sc_hd__nor2_2 g34__42(.A (n_8), .B (n_1), .Y (Cout));
endmodule

module full_adder_212(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_5, n_6, n_7, n_8;
  sky130_fd_sc_hd__nand2_2 g192__1705(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g193__5122(.A (Cin), .B (n_7), .X (S));
  sky130_fd_sc_hd__nand2_1 g194__8246(.A (n_6), .B (Cin), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g195__7098(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g196__6131(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g197__1881(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__inv_2 g200(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g201(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g203(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__inv_2 g204(.A (B), .Y (n_2));
endmodule

module full_adder_211(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_5, n_7, n_8, n_14;
  sky130_fd_sc_hd__nand2_2 g120__5115(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__7482(.A (n_7), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_2 g122__4733(.A (Cin), .B (n_14), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g123__6161(.A (B), .B (A), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g125__9945(.A (B), .B (A), .Y (n_5));
  sky130_fd_sc_hd__or2_1 g2(.A (A), .B (B), .X (n_14));
endmodule

module full_adder_210(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g120__2883(.A (n_6), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__2346(.A (n_5), .B (n_3), .X (S));
  sky130_fd_sc_hd__nand2_2 g122__1666(.A (Cin), .B (n_0), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g123__7410(.A (n_1), .B (n_2), .X (n_5));
  sky130_fd_sc_hd__nand2_1 g125__6417(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__clkbuf_1 g126(.A (Cin), .X (n_3));
  sky130_fd_sc_hd__clkbuf_1 g128(.A (A), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g130(.A (B), .X (n_1));
  sky130_fd_sc_hd__or2_0 g2__5477(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_209(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g120__2398(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__5107(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g122__6260(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g123__4319(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g124__8428(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g125__5526(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g126(.A (Cin), .X (n_2));
endmodule

module full_adder_208(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g120__6783(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__3680(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g122__1617(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g123__2802(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g124__1705(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_2 g125__5122(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g126(.A (Cin), .X (n_2));
endmodule

module full_adder_207(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g120__8246(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__7098(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g122__6131(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g123__1881(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g124__5115(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g125__7482(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g126(.A (Cin), .X (n_2));
endmodule

module full_adder_206(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_4 g120__4733(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__6161(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_4 g122__9315(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g123__9945(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g124__2883(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_2 g125__2346(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g126(.A (Cin), .X (n_2));
endmodule

module full_adder_205(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_4;
  sky130_fd_sc_hd__nand2_4 g117__1666(.A (n_4), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g118__7410(.A (n_3), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_4 g119__6417(.A (Cin), .B (n_2), .Y (n_4));
  sky130_fd_sc_hd__xor2_1 g120__5477(.A (B), .B (A), .X (n_3));
  sky130_fd_sc_hd__or2_0 g121__2398(.A (A), .B (B), .X (n_2));
  sky130_fd_sc_hd__nand2_1 g122__5107(.A (B), .B (A), .Y (n_1));
endmodule

module full_adder_204(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__a21o_1 g117__6260(.A1 (Cin), .A2 (n_0), .B1 (n_1),
       .X (Cout));
  sky130_fd_sc_hd__o2bb2ai_2 g118__4319(.A1_N (n_3), .A2_N (Cin), .B1
       (n_3), .B2 (Cin), .Y (S));
  sky130_fd_sc_hd__inv_2 g119(.A (n_2), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g120__8428(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g121__5526(.A (A), .B (B), .X (n_0));
endmodule

module ripple_carry_adder_WIDTH10(A, B, Cin, S, Cout);
  input [9:0] A, B;
  input Cin;
  output [9:0] S;
  output Cout;
  wire [9:0] A, B;
  wire Cin;
  wire [9:0] S;
  wire Cout;
  wire [9:0] carry;
  wire UNCONNECTED_HIER_Z3;
  full_adder_14 F1A(.A (A[0]), .B (B[0]), .Cin (UNCONNECTED_HIER_Z3),
       .S (S[0]), .Cout (carry[0]));
  full_adder_212 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_211 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_210 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_209 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_208 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_207 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_206 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (carry[7]));
  full_adder_205 \full_adder_loop[8].FA (.A (A[8]), .B (B[8]), .Cin
       (carry[7]), .S (S[8]), .Cout (carry[8]));
  full_adder_204 \full_adder_loop[9].FA (.A (A[9]), .B (B[9]), .Cin
       (carry[8]), .S (S[9]), .Cout (Cout));
endmodule

module full_adder_48(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_8, n_11, n_12;
  sky130_fd_sc_hd__clkinv_1 g63(.A (B), .Y (n_8));
  sky130_fd_sc_hd__xnor2_1 g2__65(.A (n_12), .B (n_8), .Y (S));
  sky130_fd_sc_hd__buf_1 g1(.A (n_11), .X (n_12));
  sky130_fd_sc_hd__inv_2 g66(.A (A), .Y (n_11));
  sky130_fd_sc_hd__nand2_2 g56__67(.A (n_8), .B (n_11), .Y (Cout));
endmodule

module full_adder_182(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_1 g179__1617(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g180__2802(.A (n_4), .B (n_7), .X (S));
  sky130_fd_sc_hd__nand2_1 g181__1705(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g182__5122(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g183__8246(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g184__7098(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__buf_2 g185(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g187(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g188(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g190(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_2 g191(.A (B), .Y (n_2));
endmodule

module full_adder_181(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_14;
  sky130_fd_sc_hd__xor2_1 g121__1881(.A (n_7), .B (n_4), .X (S));
  sky130_fd_sc_hd__xor2_1 g123__7482(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g124__4733(.A (n_3), .B (n_2), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g125__6161(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__clkbuf_1 g126(.A (Cin), .X (n_4));
  sky130_fd_sc_hd__inv_2 g128(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g129(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g131(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g132(.A (B), .Y (n_2));
  sky130_fd_sc_hd__nand2_2 g14(.A (n_14), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__nand2_2 g15(.A (Cin), .B (n_6), .Y (n_14));
endmodule

module full_adder_180(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g120__9315(.A (n_6), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__9945(.A (n_5), .B (n_3), .X (S));
  sky130_fd_sc_hd__nand2_2 g122__2883(.A (Cin), .B (n_0), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g123__2346(.A (B), .B (n_2), .X (n_5));
  sky130_fd_sc_hd__nand2_1 g125__1666(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__clkbuf_1 g126(.A (Cin), .X (n_3));
  sky130_fd_sc_hd__clkbuf_1 g128(.A (A), .X (n_2));
  sky130_fd_sc_hd__or2_0 g2__7410(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_179(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_1 g120__6417(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__5477(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_1 g122__2398(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g123__5107(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g124__6260(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g125__4319(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g126(.A (Cin), .X (n_2));
endmodule

module full_adder_178(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g120__8428(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__5526(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_1 g122__6783(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g123__3680(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g124__1617(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g125__2802(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g126(.A (Cin), .X (n_2));
endmodule

module full_adder_177(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g120__1705(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g121__5122(.A (n_5), .B (n_2), .X (S));
  sky130_fd_sc_hd__nand2_1 g122__8246(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g123__7098(.A (B), .B (A), .X (n_5));
  sky130_fd_sc_hd__or2_0 g124__6131(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g125__1881(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g126(.A (Cin), .X (n_2));
endmodule

module full_adder_176(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_6;
  sky130_fd_sc_hd__nand2_4 g120__5115(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_2 g122__4733(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__or2_0 g124__9315(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g125__9945(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__buf_2 g126(.A (Cin), .X (n_2));
  sky130_fd_sc_hd__xor3_1 g2(.A (B), .B (A), .C (n_2), .X (S));
endmodule

module full_adder_175(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_3, n_4, n_6, n_16;
  sky130_fd_sc_hd__nand2_4 g117__2883(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_4 g119__1666(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__or2_0 g121__6417(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_2 g122__5477(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__xor2_1 g29(.A (n_16), .B (Cin), .X (S));
  sky130_fd_sc_hd__xor2_1 g30(.A (A), .B (B), .X (n_16));
endmodule

module full_adder_174(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__a21o_1 g117__2398(.A1 (Cin), .A2 (n_0), .B1 (n_1),
       .X (Cout));
  sky130_fd_sc_hd__o2bb2ai_2 g118__5107(.A1_N (n_3), .A2_N (Cin), .B1
       (n_3), .B2 (Cin), .Y (S));
  sky130_fd_sc_hd__inv_2 g119(.A (n_2), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g120__6260(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g121__4319(.A (A), .B (B), .X (n_0));
endmodule

module ripple_carry_adder_WIDTH10_1(A, B, Cin, S, Cout);
  input [9:0] A, B;
  input Cin;
  output [9:0] S;
  output Cout;
  wire [9:0] A, B;
  wire Cin;
  wire [9:0] S;
  wire Cout;
  wire [9:0] carry;
  wire UNCONNECTED_HIER_Z4;
  full_adder_48 F1A(.A (A[0]), .B (B[0]), .Cin (UNCONNECTED_HIER_Z4),
       .S (S[0]), .Cout (carry[0]));
  full_adder_182 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_181 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_180 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_179 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_178 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_177 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_176 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (carry[7]));
  full_adder_175 \full_adder_loop[8].FA (.A (A[8]), .B (B[8]), .Cin
       (carry[7]), .S (S[8]), .Cout (carry[8]));
  full_adder_174 \full_adder_loop[9].FA (.A (A[9]), .B (B[9]), .Cin
       (carry[8]), .S (S[9]), .Cout (Cout));
endmodule

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED0, n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__o21ai_2 g192__8428(.A1 (n_1), .A2 (n_3), .B1 (n_2),
       .Y (Cout));
  sky130_fd_sc_hd__xnor2_1 g193__5526(.A (n_1), .B (n_0), .Y (S));
  sky130_fd_sc_hd__nor2_2 g195__6783(.A (A), .B (B), .Y (n_3));
  sky130_fd_sc_hd__nand2_1 g196__3680(.A (B), .B (A), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g198(.A (Cin), .Y (n_1));
  sky130_fd_sc_hd__ha_1 g202__1617(.A (B), .B (A), .COUT
       (UNCONNECTED0), .SUM (n_0));
endmodule

module full_adder_224(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_13;
  sky130_fd_sc_hd__nand2_2 g123__2802(.A (n_7), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g124__1705(.A (n_13), .B (n_6), .X (S));
  sky130_fd_sc_hd__nand2_2 g125__5122(.A (Cin), .B (n_5), .Y (n_7));
  sky130_fd_sc_hd__xor2_1 g126__8246(.A (B), .B (A), .X (n_6));
  sky130_fd_sc_hd__nand2_1 g127__7098(.A (n_3), .B (n_2), .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g128__6131(.A (B), .B (A), .Y (n_4));
  sky130_fd_sc_hd__clkinv_1 g131(.A (A), .Y (n_3));
  sky130_fd_sc_hd__clkinv_1 g134(.A (B), .Y (n_2));
  sky130_fd_sc_hd__buf_2 fopt(.A (Cin), .X (n_13));
endmodule

module full_adder_223(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_3, n_5;
  sky130_fd_sc_hd__nand2_2 g120__1881(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_2 g122__7482(.A (Cin), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g125__6161(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__or2_1 g2__9315(.A (B), .B (A), .X (n_0));
  sky130_fd_sc_hd__xor3_4 g2(.A (B), .B (A), .C (Cin), .X (S));
endmodule

module full_adder_222(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED1, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g120__9945(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_2 g122__2883(.A (Cin), .B (n_4), .Y (n_5));
  sky130_fd_sc_hd__or2_0 g123__2346(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g124__1666(.A (B), .B (A), .Y (n_3));
  sky130_fd_sc_hd__fa_1 g130__7410(.A (B), .B (A), .CIN (Cin), .COUT
       (UNCONNECTED1), .SUM (S));
endmodule

module full_adder_221(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4;
  sky130_fd_sc_hd__nand2_4 g120__6417(.A (n_4), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor3_1 g121__5477(.A (Cin), .B (A), .C (B), .X (S));
  sky130_fd_sc_hd__nand2_2 g122__2398(.A (Cin), .B (n_3), .Y (n_4));
  sky130_fd_sc_hd__or2_1 g123__5107(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g124__6260(.A (B), .B (A), .Y (n_2));
endmodule

module full_adder_220(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_2, n_3, n_4;
  sky130_fd_sc_hd__nand2_8 g82__4319(.A (n_4), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor3_2 g83__8428(.A (Cin), .B (A), .C (B), .X (S));
  sky130_fd_sc_hd__nand2_4 g84__5526(.A (Cin), .B (n_3), .Y (n_4));
  sky130_fd_sc_hd__or2_1 g85__6783(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_4 g86__3680(.A (B), .B (A), .Y (n_2));
endmodule

module ripple_carry_adder_WIDTH6(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder F1A(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (carry[0]));
  full_adder_224 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_223 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_222 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_221 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_220 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module carry_select_adder_68810_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire [31:0] S0;
  wire [3:0] C0;
  wire [31:0] S1;
  wire [3:0] C1;
  wire [3:0] C_mid;
  wire UNCONNECTED_HIER_Z5, UNCONNECTED_HIER_Z6, UNCONNECTED_HIER_Z7,
       UNCONNECTED_HIER_Z8, UNCONNECTED_HIER_Z9, UNCONNECTED_HIER_Z10,
       n_18, n_19;
  wire n_22, n_24, n_25, n_35, n_36, n_59, n_60, n_62;
  wire n_64, n_65, n_66, n_68, n_69, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_84, n_85, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_100, n_101, n_102, n_103, n_104, n_105, n_110, n_111;
  wire n_112, n_113, n_114, n_117, n_119, n_120, n_121, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_133, n_135, n_136;
  wire n_137, n_138, n_239, n_260, n_261, n_262, n_263, n_264;
  wire n_265, n_266, n_267, n_272, n_273, n_274, n_275, n_276;
  wire n_277, n_278, n_279, n_280, n_281, n_282, n_283, n_289;
  wire n_338, n_339, n_342, n_345, n_356, n_357, n_358, n_360;
  wire n_361, n_366, n_369, n_372, n_388, n_396, n_415, n_439;
  wire n_441, n_446, n_455, n_461, n_462, n_464, n_466, n_467;
  wire n_469, n_472, n_485, n_486, n_487, n_494, n_523, n_524;
  wire n_552, n_553, n_558, n_559, n_564, n_570, n_571, n_574;
  wire n_576, n_578, n_600, n_602, n_603, n_605, n_606, n_607;
  wire n_644, n_645, n_647, n_648, n_649, n_650, n_651, n_657;
  wire n_658, n_659, n_660, n_661, n_665, n_666, n_667, n_669;
  wire n_670, n_671, n_672, n_674, n_675, n_681, n_682, n_683;
  wire n_684, n_685, n_686;
  ripple_carry_adder_WIDTH8 \CSA_BLOCKS[1].RCA_C0 (.A ({n_138, n_137,
       n_136, n_135, n_281, n_133, n_267, n_275}), .B ({n_130, n_129,
       n_128, n_127, n_126, n_125, n_261, n_278}), .Cin
       (UNCONNECTED_HIER_Z5), .S (S0[13:6]), .Cout (C0[1]));
  ripple_carry_adder_WIDTH8_3_228 \CSA_BLOCKS[1].RCA_C1 (.A ({n_138,
       n_137, n_136, n_135, n_280, n_133, n_266, n_274}), .B ({n_130,
       n_129, n_128, n_127, n_126, n_125, n_260, n_279}), .Cin
       (UNCONNECTED_HIER_Z6), .S (S1[13:6]), .Cout (C1[1]));
  ripple_carry_adder_WIDTH8_227 \CSA_BLOCKS[2].RCA_C0 (.A ({n_121,
       n_120, n_119, n_78, n_283, n_117, A[15:14]}), .B ({n_114, n_113,
       n_112, n_80, n_111, n_110, B[15:14]}), .Cin
       (UNCONNECTED_HIER_Z7), .S (S0[21:14]), .Cout (C0[2]));
  ripple_carry_adder_WIDTH8_3 \CSA_BLOCKS[2].RCA_C1 (.A ({n_121, n_120,
       n_119, n_78, n_282, n_117, A[15:14]}), .B ({n_114, n_113, n_112,
       n_80, n_111, n_110, B[15:14]}), .Cin (UNCONNECTED_HIER_Z8), .S
       (S1[21:14]), .Cout (C1[2]));
  ripple_carry_adder_WIDTH10 \CSA_BLOCKS[3].RCA_C0 (.A ({A[31], n_105,
       n_104, n_103, n_102, n_101, n_100, A[24], n_277, n_273}), .B
       ({B[31], n_95, n_94, n_93, n_92, n_91, n_90, B[24], n_265,
       n_262}), .Cin (UNCONNECTED_HIER_Z9), .S (S0[31:22]), .Cout
       (C0[3]));
  ripple_carry_adder_WIDTH10_1 \CSA_BLOCKS[3].RCA_C1 (.A ({A[31],
       n_105, n_104, n_103, n_102, n_101, n_100, A[24], n_276, n_272}),
       .B ({B[31], n_95, n_94, n_93, n_92, n_91, n_90, B[24], n_264,
       n_263}), .Cin (UNCONNECTED_HIER_Z10), .S (S1[31:22]), .Cout
       (C1[3]));
  ripple_carry_adder_WIDTH6 RCA_LSB(.A ({n_74, A[4], n_85, n_66, A[1],
       n_68}), .B ({n_73, B[4], n_81, n_76, B[1], n_62}), .Cin (n_84),
       .S (S[5:0]), .Cout (C_mid[0]));
  sky130_fd_sc_hd__inv_1 g6343(.A (n_71), .Y (n_85));
  sky130_fd_sc_hd__inv_1 g6298(.A (n_64), .Y (n_84));
  sky130_fd_sc_hd__inv_2 g6325(.A (n_77), .Y (n_78));
  sky130_fd_sc_hd__inv_2 g6360(.A (n_79), .Y (n_80));
  sky130_fd_sc_hd__inv_1 g6340(.A (n_60), .Y (n_81));
  sky130_fd_sc_hd__inv_2 g6322(.A (n_59), .Y (n_91));
  sky130_fd_sc_hd__inv_2 g6347(.A (n_72), .Y (n_135));
  sky130_fd_sc_hd__inv_1 g6300(.A (n_69), .Y (n_76));
  sky130_fd_sc_hd__inv_2 g6367(.A (n_65), .Y (n_101));
  sky130_fd_sc_hd__inv_2 g6328(.A (n_75), .Y (n_127));
  sky130_fd_sc_hd__inv_2 g6329(.A (B[10]), .Y (n_75));
  sky130_fd_sc_hd__clkbuf_1 g6342(.A (A[5]), .X (n_74));
  sky130_fd_sc_hd__clkbuf_1 g6338(.A (B[5]), .X (n_73));
  sky130_fd_sc_hd__inv_2 g6348(.A (A[10]), .Y (n_72));
  sky130_fd_sc_hd__clkinv_1 g6344(.A (A[3]), .Y (n_71));
  sky130_fd_sc_hd__clkbuf_1 g6365(.A (B[8]), .X (n_125));
  sky130_fd_sc_hd__clkbuf_1 g6364(.A (B[11]), .X (n_128));
  sky130_fd_sc_hd__clkbuf_1 g6353(.A (A[27]), .X (n_102));
  sky130_fd_sc_hd__clkbuf_1 g6369(.A (A[8]), .X (n_133));
  sky130_fd_sc_hd__clkbuf_1 g6305(.A (A[13]), .X (n_138));
  sky130_fd_sc_hd__clkbuf_1 g6358(.A (A[19]), .X (n_119));
  sky130_fd_sc_hd__clkbuf_1 g6311(.A (B[19]), .X (n_112));
  sky130_fd_sc_hd__clkbuf_1 g6320(.A (A[21]), .X (n_121));
  sky130_fd_sc_hd__buf_1 g6349(.A (A[25]), .X (n_100));
  sky130_fd_sc_hd__clkbuf_1 g6318(.A (A[16]), .X (n_117));
  sky130_fd_sc_hd__clkbuf_1 g6351(.A (A[28]), .X (n_103));
  sky130_fd_sc_hd__inv_2 g6361(.A (B[18]), .Y (n_79));
  sky130_fd_sc_hd__clkbuf_1 g6331(.A (B[27]), .X (n_92));
  sky130_fd_sc_hd__inv_2 g6326(.A (A[18]), .Y (n_77));
  sky130_fd_sc_hd__clkbuf_1 g6316(.A (A[11]), .X (n_136));
  sky130_fd_sc_hd__clkbuf_1 g6374(.A (B[28]), .X (n_93));
  sky130_fd_sc_hd__clkinv_1 g6301(.A (B[2]), .Y (n_69));
  sky130_fd_sc_hd__clkbuf_1 g6337(.A (A[0]), .X (n_68));
  sky130_fd_sc_hd__clkbuf_1 g6346(.A (A[2]), .X (n_66));
  sky130_fd_sc_hd__inv_2 g6368(.A (A[26]), .Y (n_65));
  sky130_fd_sc_hd__inv_2 g6299(.A (Cin), .Y (n_64));
  sky130_fd_sc_hd__clkbuf_1 g6302(.A (B[0]), .X (n_62));
  sky130_fd_sc_hd__clkinv_1 g6341(.A (B[3]), .Y (n_60));
  sky130_fd_sc_hd__inv_2 g6323(.A (B[26]), .Y (n_59));
  sky130_fd_sc_hd__clkbuf_1 g6306(.A (A[30]), .X (n_105));
  sky130_fd_sc_hd__clkbuf_1 g6317(.A (A[20]), .X (n_120));
  sky130_fd_sc_hd__clkbuf_1 g6373(.A (B[20]), .X (n_113));
  sky130_fd_sc_hd__buf_1 g6372(.A (B[25]), .X (n_90));
  sky130_fd_sc_hd__clkbuf_1 g6315(.A (B[21]), .X (n_114));
  sky130_fd_sc_hd__buf_1 g6354(.A (B[9]), .X (n_126));
  sky130_fd_sc_hd__clkbuf_1 g6356(.A (B[30]), .X (n_95));
  sky130_fd_sc_hd__clkbuf_1 g6363(.A (B[16]), .X (n_110));
  sky130_fd_sc_hd__buf_1 g6310(.A (B[17]), .X (n_111));
  sky130_fd_sc_hd__clkbuf_1 g6334(.A (A[29]), .X (n_104));
  sky130_fd_sc_hd__clkbuf_1 g6362(.A (B[13]), .X (n_130));
  sky130_fd_sc_hd__clkbuf_1 g6357(.A (B[29]), .X (n_94));
  sky130_fd_sc_hd__clkbuf_1 g6371(.A (B[12]), .X (n_129));
  sky130_fd_sc_hd__clkbuf_1 g6350(.A (A[12]), .X (n_137));
  sky130_fd_sc_hd__nand2_1 g14563__6161(.A (n_686), .B (n_24), .Y
       (n_36));
  sky130_fd_sc_hd__nand2_1 g14564__9315(.A (n_357), .B (n_25), .Y
       (n_35));
  sky130_fd_sc_hd__a22o_2 g14566__2883(.A1 (n_494), .A2 (S0[8]), .B1
       (n_486), .B2 (S1[8]), .X (S[8]));
  sky130_fd_sc_hd__a22o_2 g14567__2346(.A1 (n_494), .A2 (S0[9]), .B1
       (n_486), .B2 (S1[9]), .X (S[9]));
  sky130_fd_sc_hd__a22o_2 g14568__1666(.A1 (n_494), .A2 (S0[6]), .B1
       (n_486), .B2 (S1[6]), .X (S[6]));
  sky130_fd_sc_hd__a22o_2 g14571__5477(.A1 (n_494), .A2 (S0[12]), .B1
       (n_486), .B2 (S1[12]), .X (S[12]));
  sky130_fd_sc_hd__a22o_2 g14572__2398(.A1 (n_494), .A2 (S0[11]), .B1
       (n_486), .B2 (S1[11]), .X (S[11]));
  sky130_fd_sc_hd__a22o_2 g14573__5107(.A1 (n_494), .A2 (S0[10]), .B1
       (n_486), .B2 (S1[10]), .X (S[10]));
  sky130_fd_sc_hd__nor2b_1 g14580__1617(.A (n_486), .B_N (S0[24]), .Y
       (n_25));
  sky130_fd_sc_hd__nor2b_1 g14582__1705(.A (n_487), .B_N (S0[24]), .Y
       (n_24));
  sky130_fd_sc_hd__inv_1 g14586(.A (S0[30]), .Y (n_22));
  sky130_fd_sc_hd__clkinv_4 g14590(.A (C0[1]), .Y (n_19));
  sky130_fd_sc_hd__inv_2 g14591(.A (S0[22]), .Y (n_18));
  sky130_fd_sc_hd__clkinv_1 fopt14615(.A (C1[1]), .Y (n_239));
  sky130_fd_sc_hd__clkbuf_1 g14624(.A (B[7]), .X (n_260));
  sky130_fd_sc_hd__clkbuf_1 g6307_dup(.A (B[7]), .X (n_261));
  sky130_fd_sc_hd__clkbuf_1 g14625(.A (B[22]), .X (n_262));
  sky130_fd_sc_hd__clkbuf_1 g6330_dup(.A (B[22]), .X (n_263));
  sky130_fd_sc_hd__clkbuf_1 g14626(.A (B[23]), .X (n_264));
  sky130_fd_sc_hd__clkbuf_1 g6370_dup(.A (B[23]), .X (n_265));
  sky130_fd_sc_hd__clkbuf_1 g14627(.A (A[7]), .X (n_266));
  sky130_fd_sc_hd__clkbuf_1 g6309_dup(.A (A[7]), .X (n_267));
  sky130_fd_sc_hd__clkbuf_1 g14630(.A (A[22]), .X (n_272));
  sky130_fd_sc_hd__clkbuf_1 g6321_dup(.A (A[22]), .X (n_273));
  sky130_fd_sc_hd__clkbuf_1 g14631(.A (A[6]), .X (n_274));
  sky130_fd_sc_hd__clkbuf_1 g6319_dup(.A (A[6]), .X (n_275));
  sky130_fd_sc_hd__clkbuf_1 g14632(.A (A[23]), .X (n_276));
  sky130_fd_sc_hd__clkbuf_1 g6332_dup(.A (A[23]), .X (n_277));
  sky130_fd_sc_hd__clkbuf_1 g14633(.A (B[6]), .X (n_278));
  sky130_fd_sc_hd__clkbuf_1 g6352_dup(.A (B[6]), .X (n_279));
  sky130_fd_sc_hd__buf_1 g14634(.A (A[9]), .X (n_280));
  sky130_fd_sc_hd__buf_1 g6327_dup(.A (A[9]), .X (n_281));
  sky130_fd_sc_hd__buf_1 g14635(.A (A[17]), .X (n_282));
  sky130_fd_sc_hd__buf_1 g6335_dup(.A (A[17]), .X (n_283));
  sky130_fd_sc_hd__buf_2 fopt14641(.A (n_571), .X (n_289));
  sky130_fd_sc_hd__nand2_2 g14672(.A (n_338), .B (n_339), .Y (S[13]));
  sky130_fd_sc_hd__nand2b_1 g14673(.A_N (n_486), .B (S0[13]), .Y
       (n_338));
  sky130_fd_sc_hd__nand2_1 g14675(.A (S1[13]), .B (n_486), .Y (n_339));
  sky130_fd_sc_hd__nand2_1 g20(.A (S1[31]), .B (n_602), .Y (n_342));
  sky130_fd_sc_hd__nand3_4 g14677(.A (n_345), .B (n_35), .C (n_36), .Y
       (S[24]));
  sky130_fd_sc_hd__nand2_1 g14678(.A (n_606), .B (S1[24]), .Y (n_345));
  sky130_fd_sc_hd__nand2_1 g68(.A (n_372), .B (n_356), .Y (n_357));
  sky130_fd_sc_hd__buf_2 g69(.A (n_564), .X (n_356));
  sky130_fd_sc_hd__nand2_4 g14682(.A (n_360), .B (n_361), .Y (S[29]));
  sky130_fd_sc_hd__nand2_2 g14683(.A (n_358), .B (S0[29]), .Y (n_360));
  sky130_fd_sc_hd__nand2_1 g14686(.A (S1[29]), .B (n_606), .Y (n_361));
  sky130_fd_sc_hd__nand2_4 g21(.A (n_366), .B (n_369), .Y (Cout));
  sky130_fd_sc_hd__nand2_2 g14687(.A (C1[3]), .B (n_602), .Y (n_366));
  sky130_fd_sc_hd__nand2_2 g14688(.A (C0[3]), .B (n_358), .Y (n_369));
  sky130_fd_sc_hd__inv_2 fopt14690(.A (n_606), .Y (n_358));
  sky130_fd_sc_hd__nand2_4 g97(.A (n_19), .B (n_469), .Y (n_372));
  sky130_fd_sc_hd__inv_2 fopt14694(.A (n_606), .Y (n_388));
  sky130_fd_sc_hd__clkinv_1 g14701(.A (n_18), .Y (n_396));
  sky130_fd_sc_hd__nand3_2 g45(.A (n_372), .B (n_564), .C (n_485), .Y
       (n_415));
  sky130_fd_sc_hd__nand2_4 g14739(.A (n_651), .B (n_439), .Y (S[21]));
  sky130_fd_sc_hd__nand2_1 g14741(.A (n_658), .B (S1[21]), .Y (n_439));
  sky130_fd_sc_hd__inv_2 g19(.A (n_606), .Y (n_441));
  sky130_fd_sc_hd__nand2_2 g14746(.A (n_388), .B (S0[25]), .Y (n_446));
  sky130_fd_sc_hd__nand2_2 g7(.A (n_461), .B (S0[28]), .Y (n_455));
  sky130_fd_sc_hd__nand2_2 g14761(.A (n_461), .B (S0[26]), .Y (n_462));
  sky130_fd_sc_hd__inv_2 g14762(.A (n_602), .Y (n_461));
  sky130_fd_sc_hd__inv_2 g14763(.A (n_602), .Y (n_464));
  sky130_fd_sc_hd__clkinv_2 g14764(.A (C0[2]), .Y (n_466));
  sky130_fd_sc_hd__clkinv_4 g10(.A (C1[1]), .Y (n_467));
  sky130_fd_sc_hd__clkinv_2 g14765(.A (C0[2]), .Y (n_469));
  sky130_fd_sc_hd__nand2_4 g14767(.A (n_342), .B (n_472), .Y (S[31]));
  sky130_fd_sc_hd__nand2_2 g14768(.A (n_441), .B (S0[31]), .Y (n_472));
  sky130_fd_sc_hd__clkinv_4 fopt(.A (C_mid[0]), .Y (n_485));
  sky130_fd_sc_hd__inv_2 fopt3(.A (n_487), .Y (n_486));
  sky130_fd_sc_hd__inv_2 fopt7(.A (C_mid[0]), .Y (n_487));
  sky130_fd_sc_hd__inv_2 fopt9(.A (C_mid[0]), .Y (n_494));
  sky130_fd_sc_hd__nand2_2 g14802(.A (S0[23]), .B (n_388), .Y (n_523));
  sky130_fd_sc_hd__nand2_2 g14803(.A (S0[27]), .B (n_441), .Y (n_524));
  sky130_fd_sc_hd__mux2_4 g14804(.A0 (S1[7]), .A1 (S0[7]), .S (n_494),
       .X (S[7]));
  sky130_fd_sc_hd__nand2_4 g14805(.A (n_650), .B (n_657), .Y (S[20]));
  sky130_fd_sc_hd__nand2_4 g2(.A (n_649), .B (n_659), .Y (S[18]));
  sky130_fd_sc_hd__nand2_4 g14807(.A (n_648), .B (n_660), .Y (S[17]));
  sky130_fd_sc_hd__nand2_4 g14809(.A (n_647), .B (n_661), .Y (S[16]));
  sky130_fd_sc_hd__nand2_8 g14813(.A (n_552), .B (n_553), .Y (S[22]));
  sky130_fd_sc_hd__nand2_4 g18(.A (n_464), .B (n_396), .Y (n_552));
  sky130_fd_sc_hd__nand2_2 g14814(.A (n_606), .B (S1[22]), .Y (n_553));
  sky130_fd_sc_hd__nand2_4 g15(.A (n_559), .B (n_607), .Y (S[30]));
  sky130_fd_sc_hd__nand2_4 g14818(.A (n_464), .B (n_558), .Y (n_559));
  sky130_fd_sc_hd__inv_2 g14819(.A (n_22), .Y (n_558));
  sky130_fd_sc_hd__nand2_2 g14822(.A (n_570), .B (C0[1]), .Y (n_564));
  sky130_fd_sc_hd__inv_2 g14826(.A (C1[2]), .Y (n_570));
  sky130_fd_sc_hd__nand2_4 g14828(.A (n_467), .B (n_466), .Y (n_571));
  sky130_fd_sc_hd__nand2_4 g11(.A (n_574), .B (n_455), .Y (S[28]));
  sky130_fd_sc_hd__nand2_1 g12(.A (n_602), .B (S1[28]), .Y (n_574));
  sky130_fd_sc_hd__nand2_4 g14829(.A (n_576), .B (n_524), .Y (S[27]));
  sky130_fd_sc_hd__nand2_1 g14830(.A (n_602), .B (S1[27]), .Y (n_576));
  sky130_fd_sc_hd__nand2_4 g14831(.A (n_578), .B (n_462), .Y (S[26]));
  sky130_fd_sc_hd__nand2_1 g14832(.A (n_602), .B (S1[26]), .Y (n_578));
  sky130_fd_sc_hd__nand2_4 g16(.A (n_600), .B (n_446), .Y (S[25]));
  sky130_fd_sc_hd__nand2_1 g17(.A (n_602), .B (S1[25]), .Y (n_600));
  sky130_fd_sc_hd__nand2_4 g14851(.A (n_603), .B (n_523), .Y (S[23]));
  sky130_fd_sc_hd__nand2_1 g14852(.A (n_602), .B (S1[23]), .Y (n_603));
  sky130_fd_sc_hd__nand2_4 g14853(.A (n_415), .B (n_683), .Y (n_602));
  sky130_fd_sc_hd__nand2_1 g31(.A (n_606), .B (S1[30]), .Y (n_607));
  sky130_fd_sc_hd__nand2_4 g32(.A (n_605), .B (n_684), .Y (n_606));
  sky130_fd_sc_hd__nand3_2 g33(.A (n_372), .B (n_564), .C (n_485), .Y
       (n_605));
  sky130_fd_sc_hd__nand2b_4 g14889(.A_N (n_675), .B (S1[16]), .Y
       (n_647));
  sky130_fd_sc_hd__nand2_4 g14577__14891(.A (n_239), .B (C_mid[0]), .Y
       (n_644));
  sky130_fd_sc_hd__nand2_4 g14579__14892(.A (n_19), .B (n_485), .Y
       (n_645));
  sky130_fd_sc_hd__nand2b_4 g14893(.A_N (n_675), .B (S1[17]), .Y
       (n_648));
  sky130_fd_sc_hd__nand2b_4 g14894(.A_N (n_675), .B (S1[18]), .Y
       (n_649));
  sky130_fd_sc_hd__nand2b_4 g14895(.A_N (n_675), .B (S1[20]), .Y
       (n_650));
  sky130_fd_sc_hd__nand2_1 g14896(.A (S0[21]), .B (n_675), .Y (n_651));
  sky130_fd_sc_hd__nand2_1 g14901(.A (n_669), .B (S0[20]), .Y (n_657));
  sky130_fd_sc_hd__inv_1 g14902(.A (n_669), .Y (n_658));
  sky130_fd_sc_hd__nand2_1 g14903(.A (n_669), .B (S0[18]), .Y (n_659));
  sky130_fd_sc_hd__nand2_1 g14904(.A (n_669), .B (S0[17]), .Y (n_660));
  sky130_fd_sc_hd__nand2_1 g14905(.A (n_669), .B (S0[16]), .Y (n_661));
  sky130_fd_sc_hd__nand2_4 g14908(.A (n_665), .B (n_667), .Y (S[19]));
  sky130_fd_sc_hd__nand2_1 g14909(.A (n_675), .B (S0[19]), .Y (n_665));
  sky130_fd_sc_hd__nand2_1 g14910(.A (n_666), .B (S1[19]), .Y (n_667));
  sky130_fd_sc_hd__inv_1 g22(.A (n_675), .Y (n_666));
  sky130_fd_sc_hd__nand2_4 g14911(.A (n_670), .B (n_672), .Y (S[14]));
  sky130_fd_sc_hd__nand2_1 g14912(.A (n_669), .B (S0[14]), .Y (n_670));
  sky130_fd_sc_hd__nand2_4 g14913(.A (n_644), .B (n_645), .Y (n_669));
  sky130_fd_sc_hd__nand2_1 g14914(.A (n_671), .B (S1[14]), .Y (n_672));
  sky130_fd_sc_hd__inv_1 g14915(.A (n_669), .Y (n_671));
  sky130_fd_sc_hd__a2bb2o_4 g14916(.A1_N (n_674), .A2_N (n_669), .B1
       (S0[15]), .B2 (n_675), .X (S[15]));
  sky130_fd_sc_hd__inv_1 g14917(.A (S1[15]), .Y (n_674));
  sky130_fd_sc_hd__nand2_4 g14918(.A (n_644), .B (n_645), .Y (n_675));
  sky130_fd_sc_hd__nand3_2 g14920(.A (n_571), .B (n_682), .C
       (C_mid[0]), .Y (n_683));
  sky130_fd_sc_hd__nand2_4 g14921(.A (n_681), .B (C1[1]), .Y (n_682));
  sky130_fd_sc_hd__inv_2 g14922(.A (C1[2]), .Y (n_681));
  sky130_fd_sc_hd__nand3_2 g14923(.A (n_571), .B (n_682), .C
       (C_mid[0]), .Y (n_684));
  sky130_fd_sc_hd__nand2_1 g14575__14924(.A (n_289), .B (n_685), .Y
       (n_686));
  sky130_fd_sc_hd__buf_1 g1(.A (n_682), .X (n_685));
endmodule

