
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr  7 2025 17:15:28 -03 (Apr  7 2025 20:15:28 UTC)

// Verification Directory fv/carry_skip4_32bits 

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__o21ai_2 g95__2398(.A1 (n_0), .A2 (n_2), .B1 (n_1),
       .Y (Cout));
  sky130_fd_sc_hd__xnor2_1 g96__5107(.A (n_0), .B (n_3), .Y (S));
  sky130_fd_sc_hd__xor2_1 g97__6260(.A (B), .B (A), .X (n_3));
  sky130_fd_sc_hd__nor2_2 g98__4319(.A (A), .B (B), .Y (n_2));
  sky130_fd_sc_hd__nand2_1 g99__8428(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g101(.A (Cin), .Y (n_0));
endmodule

module full_adder_100(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED, n_0, n_1, n_3, n_4, n_5, n_6, n_7;
  wire n_8;
  sky130_fd_sc_hd__nand2_2 g60__5526(.A (n_8), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__nand2_2 g62__6783(.A (Cin), .B (n_6), .Y (n_8));
  sky130_fd_sc_hd__xor2_1 g63__3680(.A (n_0), .B (n_1), .X (n_7));
  sky130_fd_sc_hd__nand2_1 g64__1617(.A (n_4), .B (n_3), .Y (n_6));
  sky130_fd_sc_hd__nand2_1 g65__2802(.A (n_0), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__inv_2 g67(.A (n_4), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g68(.A (A), .Y (n_4));
  sky130_fd_sc_hd__inv_2 g70(.A (n_3), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g71(.A (B), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g73__1705(.A (Cin), .B (n_7), .COUT
       (UNCONNECTED), .SUM (S));
endmodule

module full_adder_99(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2_2 g57__5122(.A (n_3), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__8246(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__7098(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__xor2_1 g60__6131(.A (B), .B (A), .X (n_2));
  sky130_fd_sc_hd__nand2_1 g62__1881(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__or2_0 g2__5115(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_98(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g60__7482(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g61__4733(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g62__6161(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g63__9315(.A (n_0), .B (n_1), .X (n_4));
  sky130_fd_sc_hd__or2_0 g64__9945(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g65__2883(.A (n_0), .B (n_1), .Y (n_2));
  sky130_fd_sc_hd__clkbuf_1 g66(.A (A), .X (n_1));
  sky130_fd_sc_hd__clkbuf_1 g67(.A (B), .X (n_0));
endmodule

module skip4(A, B, Cin, S, Cout);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output Cout;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire Cout;
  wire [3:0] C;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9;
  full_adder FA1(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (C[0]));
  full_adder_100 FA2(.A (A[1]), .B (B[1]), .Cin (C[0]), .S (S[1]),
       .Cout (C[1]));
  full_adder_99 FA3(.A (A[2]), .B (B[2]), .Cin (C[1]), .S (S[2]), .Cout
       (C[2]));
  full_adder_98 FA4(.A (A[3]), .B (B[3]), .Cin (C[2]), .S (S[3]), .Cout
       (C[3]));
  sky130_fd_sc_hd__inv_2 g74(.A (C[3]), .Y (n_9));
  sky130_fd_sc_hd__clkbuf_1 g75(.A (A[2]), .X (n_8));
  sky130_fd_sc_hd__clkbuf_1 g77(.A (A[1]), .X (n_7));
  sky130_fd_sc_hd__clkbuf_1 g76(.A (B[1]), .X (n_6));
  sky130_fd_sc_hd__nand2_2 g120__2346(.A (n_9), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__nand4_1 g121__1666(.A (n_4), .B (n_1), .C (Cin), .D
       (n_0), .Y (n_5));
  sky130_fd_sc_hd__nor2_1 g122__7410(.A (n_2), .B (n_3), .Y (n_4));
  sky130_fd_sc_hd__xnor2_1 g123__6417(.A (n_7), .B (n_6), .Y (n_3));
  sky130_fd_sc_hd__xnor2_1 g124__5477(.A (A[0]), .B (B[0]), .Y (n_2));
  sky130_fd_sc_hd__xor2_1 g125__2398(.A (B[3]), .B (A[3]), .X (n_1));
  sky130_fd_sc_hd__xor2_1 g126__5107(.A (B[2]), .B (n_8), .X (n_0));
endmodule

module full_adder_97(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g57__6260(.A (n_6), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__4319(.A (n_5), .B (n_0), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__8428(.A (Cin), .B (n_4), .Y (n_6));
  sky130_fd_sc_hd__xor2_1 g60__5526(.A (n_1), .B (n_2), .X (n_5));
  sky130_fd_sc_hd__or2_1 g61__6783(.A (A), .B (B), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g62__3680(.A (n_1), .B (n_2), .Y (n_3));
  sky130_fd_sc_hd__buf_1 g63(.A (A), .X (n_2));
  sky130_fd_sc_hd__buf_1 g64(.A (B), .X (n_1));
  sky130_fd_sc_hd__clkbuf_1 fopt(.A (Cin), .X (n_0));
endmodule

module full_adder_96(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g57__1617(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__2802(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__1705(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__5122(.A (n_0), .B (n_1), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__8246(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__7098(.A (n_0), .B (n_1), .Y (n_2));
  sky130_fd_sc_hd__buf_1 g63(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g64(.A (B), .X (n_0));
endmodule

module full_adder_95(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g57__6131(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__1881(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5115(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__7482(.A (n_0), .B (n_1), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__4733(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__6161(.A (n_0), .B (n_1), .Y (n_2));
  sky130_fd_sc_hd__buf_1 g63(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g64(.A (B), .X (n_0));
endmodule

module full_adder_94(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4;
  sky130_fd_sc_hd__nand2b_1 g57__9315(.A_N (n_2), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__9945(.A (n_3), .B (n_0), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__2883(.A (Cin), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__ha_1 g60__2346(.A (B), .B (A), .COUT (n_2), .SUM
       (n_3));
  sky130_fd_sc_hd__or2_0 g61__1666(.A (A), .B (B), .X (n_1));
  sky130_fd_sc_hd__clkbuf_1 fopt(.A (Cin), .X (n_0));
endmodule

module skip4_107(A, B, Cin, S, Cout);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output Cout;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire Cout;
  wire [3:0] C;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12;
  full_adder_97 FA1(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (C[0]));
  full_adder_96 FA2(.A (A[1]), .B (B[1]), .Cin (C[0]), .S (S[1]), .Cout
       (C[1]));
  full_adder_95 FA3(.A (A[2]), .B (B[2]), .Cin (C[1]), .S (S[2]), .Cout
       (C[2]));
  full_adder_94 FA4(.A (A[3]), .B (B[3]), .Cin (C[2]), .S (S[3]), .Cout
       (C[3]));
  sky130_fd_sc_hd__inv_1 g74(.A (C[3]), .Y (n_12));
  sky130_fd_sc_hd__clkbuf_1 g75(.A (A[2]), .X (n_11));
  sky130_fd_sc_hd__clkbuf_1 g77(.A (A[1]), .X (n_10));
  sky130_fd_sc_hd__clkbuf_1 g80(.A (A[0]), .X (n_9));
  sky130_fd_sc_hd__clkbuf_1 g76(.A (B[2]), .X (n_8));
  sky130_fd_sc_hd__clkbuf_1 g79(.A (B[0]), .X (n_7));
  sky130_fd_sc_hd__clkbuf_1 g78(.A (B[1]), .X (n_6));
  sky130_fd_sc_hd__nand2_2 g113__7410(.A (n_12), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__nand4_1 g114__6417(.A (Cin), .B (n_4), .C (n_2), .D
       (n_3), .Y (n_5));
  sky130_fd_sc_hd__nor2_1 g115__5477(.A (n_1), .B (n_0), .Y (n_4));
  sky130_fd_sc_hd__xor2_1 g116__2398(.A (B[3]), .B (A[3]), .X (n_3));
  sky130_fd_sc_hd__xor2_1 g117__5107(.A (n_7), .B (n_9), .X (n_2));
  sky130_fd_sc_hd__xnor2_1 g118__6260(.A (n_10), .B (n_6), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g119__4319(.A (n_11), .B (n_8), .Y (n_0));
endmodule

module full_adder_93(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_2 g57__8428(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__5526(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__6783(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__3680(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__1617(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_92(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_2 g57__2802(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__1705(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5122(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__8246(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__7098(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_91(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g57__6131(.A (n_5), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__1881(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5115(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__7482(.A (n_0), .B (n_1), .X (n_4));
  sky130_fd_sc_hd__or2_0 g61__4733(.A (A), .B (B), .X (n_3));
  sky130_fd_sc_hd__nand2_1 g62__6161(.A (n_0), .B (n_1), .Y (n_2));
  sky130_fd_sc_hd__buf_1 g63(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g64(.A (B), .X (n_0));
endmodule

module full_adder_90(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  sky130_fd_sc_hd__nand2b_1 g57__9315(.A_N (n_0), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__9945(.A (n_1), .B (Cin), .X (S));
  sky130_fd_sc_hd__o21ai_1 g59__2883(.A1 (A), .A2 (B), .B1 (Cin), .Y
       (n_2));
  sky130_fd_sc_hd__ha_1 g60__2346(.A (B), .B (A), .COUT (n_0), .SUM
       (n_1));
endmodule

module skip4_106(A, B, Cin, S, Cout);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output Cout;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire Cout;
  wire [3:0] C;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  full_adder_93 FA1(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (C[0]));
  full_adder_92 FA2(.A (A[1]), .B (B[1]), .Cin (C[0]), .S (S[1]), .Cout
       (C[1]));
  full_adder_91 FA3(.A (A[2]), .B (B[2]), .Cin (C[1]), .S (S[2]), .Cout
       (C[2]));
  full_adder_90 FA4(.A (A[3]), .B (B[3]), .Cin (C[2]), .S (S[3]), .Cout
       (C[3]));
  sky130_fd_sc_hd__nand2_2 g113__1666(.A (n_0), .B (n_6), .Y (Cout));
  sky130_fd_sc_hd__nand4_1 g114__7410(.A (Cin), .B (n_5), .C (n_3), .D
       (n_4), .Y (n_6));
  sky130_fd_sc_hd__nor2_1 g115__6417(.A (n_2), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g116__5477(.A (B[3]), .B (A[3]), .X (n_4));
  sky130_fd_sc_hd__xor2_1 g117__2398(.A (B[0]), .B (A[0]), .X (n_3));
  sky130_fd_sc_hd__xnor2_1 g118__5107(.A (A[1]), .B (B[1]), .Y (n_2));
  sky130_fd_sc_hd__xnor2_1 g119__6260(.A (A[2]), .B (B[2]), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g120(.A (C[3]), .Y (n_0));
endmodule

module full_adder_89(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_1 g57__4319(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__8428(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5526(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__6783(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__3680(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_88(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED0, n_1, n_2, n_3, n_4;
  sky130_fd_sc_hd__nand2b_2 g57__1617(.A_N (n_2), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g59__2802(.A (Cin), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__ha_1 g60__1705(.A (B), .B (A), .COUT (n_2), .SUM
       (n_3));
  sky130_fd_sc_hd__or2_0 g61__5122(.A (A), .B (B), .X (n_1));
  sky130_fd_sc_hd__ha_1 g63__8246(.A (n_3), .B (Cin), .COUT
       (UNCONNECTED0), .SUM (S));
endmodule

module full_adder_87(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_2 g57__7098(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__6131(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__1881(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__5115(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__7482(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_86(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  sky130_fd_sc_hd__nand2b_1 g57__4733(.A_N (n_0), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__6161(.A (n_1), .B (Cin), .X (S));
  sky130_fd_sc_hd__o21ai_1 g59__9315(.A1 (A), .A2 (B), .B1 (Cin), .Y
       (n_2));
  sky130_fd_sc_hd__ha_1 g60__9945(.A (B), .B (A), .COUT (n_0), .SUM
       (n_1));
endmodule

module skip4_105(A, B, Cin, S, Cout);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output Cout;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire Cout;
  wire [3:0] C;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  full_adder_89 FA1(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (C[0]));
  full_adder_88 FA2(.A (A[1]), .B (B[1]), .Cin (C[0]), .S (S[1]), .Cout
       (C[1]));
  full_adder_87 FA3(.A (A[2]), .B (B[2]), .Cin (C[1]), .S (S[2]), .Cout
       (C[2]));
  full_adder_86 FA4(.A (A[3]), .B (B[3]), .Cin (C[2]), .S (S[3]), .Cout
       (C[3]));
  sky130_fd_sc_hd__nand2_2 g113__2883(.A (n_0), .B (n_6), .Y (Cout));
  sky130_fd_sc_hd__nand4_1 g114__2346(.A (Cin), .B (n_5), .C (n_3), .D
       (n_4), .Y (n_6));
  sky130_fd_sc_hd__nor2_1 g115__1666(.A (n_2), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g116__7410(.A (B[3]), .B (A[3]), .X (n_4));
  sky130_fd_sc_hd__xor2_1 g117__6417(.A (B[0]), .B (A[0]), .X (n_3));
  sky130_fd_sc_hd__xnor2_1 g118__5477(.A (A[1]), .B (B[1]), .Y (n_2));
  sky130_fd_sc_hd__xnor2_1 g119__2398(.A (A[2]), .B (B[2]), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g120(.A (C[3]), .Y (n_0));
endmodule

module full_adder_85(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_1 g57__5107(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__6260(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__4319(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__8428(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__5526(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_84(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED1, n_1, n_2, n_3, n_4;
  sky130_fd_sc_hd__nand2b_2 g57__6783(.A_N (n_2), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g59__3680(.A (Cin), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__ha_1 g60__1617(.A (B), .B (A), .COUT (n_2), .SUM
       (n_3));
  sky130_fd_sc_hd__or2_0 g61__2802(.A (A), .B (B), .X (n_1));
  sky130_fd_sc_hd__ha_1 g63__1705(.A (n_3), .B (Cin), .COUT
       (UNCONNECTED1), .SUM (S));
endmodule

module full_adder_83(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_2 g57__5122(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__8246(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__7098(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__6131(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__1881(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_82(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  sky130_fd_sc_hd__nand2b_1 g57__5115(.A_N (n_0), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__7482(.A (n_1), .B (Cin), .X (S));
  sky130_fd_sc_hd__o21ai_2 g59__4733(.A1 (A), .A2 (B), .B1 (Cin), .Y
       (n_2));
  sky130_fd_sc_hd__ha_1 g60__6161(.A (B), .B (A), .COUT (n_0), .SUM
       (n_1));
endmodule

module skip4_104(A, B, Cin, S, Cout);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output Cout;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire Cout;
  wire [3:0] C;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  full_adder_85 FA1(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (C[0]));
  full_adder_84 FA2(.A (A[1]), .B (B[1]), .Cin (C[0]), .S (S[1]), .Cout
       (C[1]));
  full_adder_83 FA3(.A (A[2]), .B (B[2]), .Cin (C[1]), .S (S[2]), .Cout
       (C[2]));
  full_adder_82 FA4(.A (A[3]), .B (B[3]), .Cin (C[2]), .S (S[3]), .Cout
       (C[3]));
  sky130_fd_sc_hd__nand2_2 g123__9315(.A (n_0), .B (n_6), .Y (Cout));
  sky130_fd_sc_hd__nand4_1 g124__9945(.A (Cin), .B (n_5), .C (n_3), .D
       (n_4), .Y (n_6));
  sky130_fd_sc_hd__nor2_1 g125__2883(.A (n_2), .B (n_1), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g126__2346(.A (B[3]), .B (A[3]), .X (n_4));
  sky130_fd_sc_hd__xor2_1 g127__1666(.A (B[0]), .B (A[0]), .X (n_3));
  sky130_fd_sc_hd__xnor2_1 g128__7410(.A (A[1]), .B (B[1]), .Y (n_2));
  sky130_fd_sc_hd__xnor2_1 g129__6417(.A (A[2]), .B (B[2]), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g130(.A (C[3]), .Y (n_0));
endmodule

module full_adder_81(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_1 g57__5477(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__2398(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5107(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__6260(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__4319(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_80(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_1 g57__8428(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__5526(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__6783(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__ha_1 g60__3680(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__or2_0 g61__1617(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_79(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED2, n_1, n_2, n_3, n_4;
  sky130_fd_sc_hd__nand2b_1 g57__2802(.A_N (n_2), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g59__1705(.A (Cin), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__ha_1 g60__5122(.A (B), .B (A), .COUT (n_2), .SUM
       (n_3));
  sky130_fd_sc_hd__or2_0 g61__8246(.A (A), .B (B), .X (n_1));
  sky130_fd_sc_hd__ha_1 g63__7098(.A (n_3), .B (Cin), .COUT
       (UNCONNECTED2), .SUM (S));
endmodule

module full_adder_78(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2b_1 g57__6131(.A_N (n_3), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g59__1881(.A (Cin), .B (n_2), .Y (n_5));
  sky130_fd_sc_hd__ha_1 g60__5115(.A (B), .B (A), .COUT (n_3), .SUM
       (n_4));
  sky130_fd_sc_hd__or2_0 g61__7482(.A (A), .B (B), .X (n_2));
  sky130_fd_sc_hd__buf_2 fopt(.A (Cin), .X (n_0));
  sky130_fd_sc_hd__xor2_1 g65__4733(.A (n_4), .B (n_0), .X (S));
endmodule

module skip4_103(A, B, Cin, S, Cout);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output Cout;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire Cout;
  wire [3:0] C;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  full_adder_81 FA1(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (C[0]));
  full_adder_80 FA2(.A (A[1]), .B (B[1]), .Cin (C[0]), .S (S[1]), .Cout
       (C[1]));
  full_adder_79 FA3(.A (A[2]), .B (B[2]), .Cin (C[1]), .S (S[2]), .Cout
       (C[2]));
  full_adder_78 FA4(.A (A[3]), .B (B[3]), .Cin (C[2]), .S (S[3]), .Cout
       (C[3]));
  sky130_fd_sc_hd__inv_2 g79(.A (C[3]), .Y (n_6));
  sky130_fd_sc_hd__nand2_2 g123__6161(.A (n_6), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__nand4_1 g124__9315(.A (Cin), .B (n_4), .C (n_2), .D
       (n_3), .Y (n_5));
  sky130_fd_sc_hd__nor2_1 g125__9945(.A (n_1), .B (n_0), .Y (n_4));
  sky130_fd_sc_hd__xor2_1 g126__2883(.A (B[3]), .B (A[3]), .X (n_3));
  sky130_fd_sc_hd__xor2_1 g127__2346(.A (B[0]), .B (A[0]), .X (n_2));
  sky130_fd_sc_hd__xnor2_1 g128__1666(.A (A[1]), .B (B[1]), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g129__7410(.A (A[2]), .B (B[2]), .Y (n_0));
endmodule

module full_adder_77(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2_2 g57__6417(.A (n_3), .B (n_0), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__5477(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_2 g59__2398(.A (Cin), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__xor2_1 g60__5107(.A (B), .B (A), .X (n_2));
  sky130_fd_sc_hd__or2_1 g61__6260(.A (A), .B (B), .X (n_1));
  sky130_fd_sc_hd__nand2_1 g62__4319(.A (B), .B (A), .Y (n_0));
endmodule

module full_adder_76(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  sky130_fd_sc_hd__nand2_1 g57__8428(.A (n_2), .B (n_0), .Y (Cout));
  sky130_fd_sc_hd__xor3_1 g58__5526(.A (B), .B (A), .C (Cin), .X (S));
  sky130_fd_sc_hd__nand2_2 g59__6783(.A (Cin), .B (n_1), .Y (n_2));
  sky130_fd_sc_hd__or2_0 g60__3680(.A (A), .B (B), .X (n_1));
  sky130_fd_sc_hd__nand2_1 g61__1617(.A (B), .B (A), .Y (n_0));
endmodule

module full_adder_75(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2;
  sky130_fd_sc_hd__nand2_1 g57__2802(.A (n_2), .B (n_0), .Y (Cout));
  sky130_fd_sc_hd__xor3_1 g58__1705(.A (B), .B (A), .C (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5122(.A (Cin), .B (n_1), .Y (n_2));
  sky130_fd_sc_hd__or2_0 g60__8246(.A (A), .B (B), .X (n_1));
  sky130_fd_sc_hd__nand2_1 g61__7098(.A (B), .B (A), .Y (n_0));
endmodule

module full_adder_74(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED3, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2_1 g57__6131(.A (n_3), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g59__1881(.A (Cin), .B (n_2), .Y (n_3));
  sky130_fd_sc_hd__or2_0 g60__5115(.A (A), .B (B), .X (n_2));
  sky130_fd_sc_hd__nand2_1 g61__7482(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__fa_1 g63__4733(.A (B), .B (A), .CIN (Cin), .COUT
       (UNCONNECTED3), .SUM (S));
endmodule

module skip4_102(A, B, Cin, S, Cout);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output Cout;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire Cout;
  wire [3:0] C;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  full_adder_77 FA1(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (C[0]));
  full_adder_76 FA2(.A (A[1]), .B (B[1]), .Cin (C[0]), .S (S[1]), .Cout
       (C[1]));
  full_adder_75 FA3(.A (A[2]), .B (B[2]), .Cin (C[1]), .S (S[2]), .Cout
       (C[2]));
  full_adder_74 FA4(.A (A[3]), .B (B[3]), .Cin (C[2]), .S (S[3]), .Cout
       (C[3]));
  sky130_fd_sc_hd__clkinv_1 g79(.A (C[3]), .Y (n_6));
  sky130_fd_sc_hd__nand2_2 g123__6161(.A (n_6), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g124__9315(.A (Cin), .B (n_4), .Y (n_5));
  sky130_fd_sc_hd__nor4_1 g125__9945(.A (n_2), .B (n_3), .C (n_1), .D
       (n_0), .Y (n_4));
  sky130_fd_sc_hd__xnor2_1 g126__2883(.A (A[3]), .B (B[3]), .Y (n_3));
  sky130_fd_sc_hd__xnor2_1 g127__2346(.A (A[0]), .B (B[0]), .Y (n_2));
  sky130_fd_sc_hd__xnor2_1 g128__1666(.A (A[1]), .B (B[1]), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g129__7410(.A (A[2]), .B (B[2]), .Y (n_0));
endmodule

module full_adder_73(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED4, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2_1 g57__6417(.A (n_3), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g59__5477(.A (Cin), .B (n_2), .Y (n_3));
  sky130_fd_sc_hd__or2_1 g60__2398(.A (A), .B (B), .X (n_2));
  sky130_fd_sc_hd__nand2_1 g61__5107(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__fa_2 g63__6260(.A (B), .B (A), .CIN (Cin), .COUT
       (UNCONNECTED4), .SUM (S));
endmodule

module full_adder_72(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_1 g57__4319(.A (n_5), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__a22o_1 g58__8428(.A1 (Cin), .A2 (n_4), .B1 (n_0),
       .B2 (n_3), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5526(.A (Cin), .B (n_2), .Y (n_5));
  sky130_fd_sc_hd__inv_2 g60(.A (n_3), .Y (n_4));
  sky130_fd_sc_hd__xor2_1 g61__6783(.A (B), .B (A), .X (n_3));
  sky130_fd_sc_hd__or2_0 g62__3680(.A (A), .B (B), .X (n_2));
  sky130_fd_sc_hd__nand2_1 g63__1617(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__inv_1 g64(.A (Cin), .Y (n_0));
endmodule

module full_adder_71(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2_1 g57__2802(.A (n_3), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__a2bb2o_2 g58__1705(.A1_N (n_0), .A2_N (Cin), .B1
       (n_0), .B2 (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5122(.A (Cin), .B (n_2), .Y (n_3));
  sky130_fd_sc_hd__or2_0 g62__8246(.A (A), .B (B), .X (n_2));
  sky130_fd_sc_hd__nand2_1 g63__7098(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g2__6131(.A (B), .B (A), .Y (n_0));
endmodule

module full_adder_70(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2_1 g57__1881(.A (n_3), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__a2bb2o_4 g58__5115(.A1_N (n_0), .A2_N (Cin), .B1
       (n_0), .B2 (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__7482(.A (Cin), .B (n_2), .Y (n_3));
  sky130_fd_sc_hd__or2_0 g62__4733(.A (A), .B (B), .X (n_2));
  sky130_fd_sc_hd__nand2_1 g63__6161(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g2__9315(.A (B), .B (A), .Y (n_0));
endmodule

module skip4_101(A, B, Cin, S, Cout);
  input [3:0] A, B;
  input Cin;
  output [3:0] S;
  output Cout;
  wire [3:0] A, B;
  wire Cin;
  wire [3:0] S;
  wire Cout;
  wire [3:0] C;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6;
  full_adder_73 FA1(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (C[0]));
  full_adder_72 FA2(.A (A[1]), .B (B[1]), .Cin (C[0]), .S (S[1]), .Cout
       (C[1]));
  full_adder_71 FA3(.A (A[2]), .B (B[2]), .Cin (C[1]), .S (S[2]), .Cout
       (C[2]));
  full_adder_70 FA4(.A (A[3]), .B (B[3]), .Cin (C[2]), .S (S[3]), .Cout
       (C[3]));
  sky130_fd_sc_hd__clkinv_1 g79(.A (C[3]), .Y (n_6));
  sky130_fd_sc_hd__nand2_4 g123__9945(.A (n_6), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g124__2883(.A (Cin), .B (n_4), .Y (n_5));
  sky130_fd_sc_hd__nor4_1 g125__2346(.A (n_2), .B (n_3), .C (n_1), .D
       (n_0), .Y (n_4));
  sky130_fd_sc_hd__xnor2_1 g126__1666(.A (A[3]), .B (B[3]), .Y (n_3));
  sky130_fd_sc_hd__xnor2_1 g127__7410(.A (A[0]), .B (B[0]), .Y (n_2));
  sky130_fd_sc_hd__xnor2_1 g128__6417(.A (A[1]), .B (B[1]), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g129__5477(.A (A[2]), .B (B[2]), .Y (n_0));
endmodule

module carry_skip4_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire [7:0] C;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67;
  skip4 CSKIP1(.A ({n_67, n_59, n_42, n_61}), .B ({n_66, n_62, n_58,
       n_47}), .Cin (n_65), .S (S[3:0]), .Cout (C[0]));
  skip4_107 \skip_loop[1].CSKIP2 (.A ({n_9, n_6, n_2, n_0}), .B ({n_5,
       n_4, n_1, n_31}), .Cin (C[0]), .S (S[7:4]), .Cout (C[1]));
  skip4_106 \skip_loop[2].CSKIP2 (.A ({n_23, n_19, n_15, n_12}), .B
       ({n_11, n_29, n_7, n_20}), .Cin (C[1]), .S (S[11:8]), .Cout
       (C[2]));
  skip4_105 \skip_loop[3].CSKIP2 (.A ({n_40, n_38, n_34, n_28}), .B
       ({n_17, n_32, n_13, n_26}), .Cin (C[2]), .S (S[15:12]), .Cout
       (C[3]));
  skip4_104 \skip_loop[4].CSKIP2 (.A ({n_63, n_53, n_64, n_43}), .B
       ({n_49, n_55, n_21, n_18}), .Cin (C[3]), .S (S[19:16]), .Cout
       (C[4]));
  skip4_103 \skip_loop[5].CSKIP2 (.A ({n_24, n_14, n_27, n_3}), .B
       ({n_36, n_33, n_30, n_44}), .Cin (C[4]), .S (S[23:20]), .Cout
       (C[5]));
  skip4_102 \skip_loop[6].CSKIP2 (.A ({n_48, n_37, n_54, n_16}), .B
       ({n_41, n_46, n_51, n_39}), .Cin (C[5]), .S (S[27:24]), .Cout
       (C[6]));
  skip4_101 \skip_loop[7].CSKIP2 (.A ({n_57, n_35, n_52, n_8}), .B
       ({n_25, n_45, n_56, n_50}), .Cin (C[6]), .S (S[31:28]), .Cout
       (Cout));
  sky130_fd_sc_hd__inv_2 g11(.A (n_10), .Y (n_67));
  sky130_fd_sc_hd__inv_2 g38(.A (n_22), .Y (n_66));
  sky130_fd_sc_hd__clkinv_1 g62(.A (n_60), .Y (n_65));
  sky130_fd_sc_hd__clkbuf_1 g32(.A (A[17]), .X (n_64));
  sky130_fd_sc_hd__buf_1 g50(.A (A[19]), .X (n_63));
  sky130_fd_sc_hd__clkbuf_1 g66(.A (B[2]), .X (n_62));
  sky130_fd_sc_hd__buf_6 g59(.A (A[0]), .X (n_61));
  sky130_fd_sc_hd__inv_4 g63(.A (Cin), .Y (n_60));
  sky130_fd_sc_hd__clkbuf_1 g51(.A (A[2]), .X (n_59));
  sky130_fd_sc_hd__clkbuf_1 g18(.A (B[1]), .X (n_58));
  sky130_fd_sc_hd__buf_1 g17(.A (A[31]), .X (n_57));
  sky130_fd_sc_hd__clkbuf_1 g46(.A (B[29]), .X (n_56));
  sky130_fd_sc_hd__clkbuf_1 g53(.A (B[18]), .X (n_55));
  sky130_fd_sc_hd__clkbuf_1 g41(.A (A[25]), .X (n_54));
  sky130_fd_sc_hd__clkbuf_1 g33(.A (A[18]), .X (n_53));
  sky130_fd_sc_hd__clkbuf_1 g27(.A (A[29]), .X (n_52));
  sky130_fd_sc_hd__clkbuf_1 g60(.A (B[25]), .X (n_51));
  sky130_fd_sc_hd__buf_1 g16(.A (B[28]), .X (n_50));
  sky130_fd_sc_hd__buf_1 g24(.A (B[19]), .X (n_49));
  sky130_fd_sc_hd__clkbuf_1 g61(.A (A[27]), .X (n_48));
  sky130_fd_sc_hd__buf_6 g15(.A (B[0]), .X (n_47));
  sky130_fd_sc_hd__clkbuf_1 g47(.A (B[26]), .X (n_46));
  sky130_fd_sc_hd__buf_1 g56(.A (B[30]), .X (n_45));
  sky130_fd_sc_hd__clkbuf_1 g21(.A (B[20]), .X (n_44));
  sky130_fd_sc_hd__clkbuf_1 g29(.A (A[16]), .X (n_43));
  sky130_fd_sc_hd__clkbuf_1 g30(.A (A[1]), .X (n_42));
  sky130_fd_sc_hd__buf_1 g26(.A (B[27]), .X (n_41));
  sky130_fd_sc_hd__clkbuf_1 g42(.A (A[15]), .X (n_40));
  sky130_fd_sc_hd__clkbuf_1 g58(.A (B[24]), .X (n_39));
  sky130_fd_sc_hd__clkbuf_1 g34(.A (A[14]), .X (n_38));
  sky130_fd_sc_hd__clkbuf_1 g23(.A (A[26]), .X (n_37));
  sky130_fd_sc_hd__clkbuf_1 g40(.A (B[23]), .X (n_36));
  sky130_fd_sc_hd__buf_1 g52(.A (A[30]), .X (n_35));
  sky130_fd_sc_hd__clkbuf_1 g45(.A (A[13]), .X (n_34));
  sky130_fd_sc_hd__clkbuf_1 g7(.A (B[22]), .X (n_33));
  sky130_fd_sc_hd__clkbuf_1 g4(.A (B[14]), .X (n_32));
  sky130_fd_sc_hd__clkbuf_1 g57(.A (B[4]), .X (n_31));
  sky130_fd_sc_hd__clkbuf_1 g54(.A (B[21]), .X (n_30));
  sky130_fd_sc_hd__clkbuf_1 g19(.A (B[10]), .X (n_29));
  sky130_fd_sc_hd__clkbuf_1 g55(.A (A[12]), .X (n_28));
  sky130_fd_sc_hd__clkbuf_1 g3(.A (A[21]), .X (n_27));
  sky130_fd_sc_hd__clkbuf_1 g1(.A (B[12]), .X (n_26));
  sky130_fd_sc_hd__buf_1 g31(.A (B[31]), .X (n_25));
  sky130_fd_sc_hd__clkbuf_1 g2(.A (A[23]), .X (n_24));
  sky130_fd_sc_hd__clkbuf_1 g14(.A (A[11]), .X (n_23));
  sky130_fd_sc_hd__clkinv_2 g39(.A (B[3]), .Y (n_22));
  sky130_fd_sc_hd__clkbuf_1 g8(.A (B[17]), .X (n_21));
  sky130_fd_sc_hd__clkbuf_1 g64(.A (B[8]), .X (n_20));
  sky130_fd_sc_hd__clkbuf_1 g13(.A (A[10]), .X (n_19));
  sky130_fd_sc_hd__clkbuf_1 g25(.A (B[16]), .X (n_18));
  sky130_fd_sc_hd__clkbuf_1 g9(.A (B[15]), .X (n_17));
  sky130_fd_sc_hd__clkbuf_1 g22(.A (A[24]), .X (n_16));
  sky130_fd_sc_hd__clkbuf_1 g37(.A (A[9]), .X (n_15));
  sky130_fd_sc_hd__clkbuf_1 g48(.A (A[22]), .X (n_14));
  sky130_fd_sc_hd__clkbuf_1 g20(.A (B[13]), .X (n_13));
  sky130_fd_sc_hd__clkbuf_1 g44(.A (A[8]), .X (n_12));
  sky130_fd_sc_hd__clkbuf_1 g35(.A (B[11]), .X (n_11));
  sky130_fd_sc_hd__inv_2 g12(.A (A[3]), .Y (n_10));
  sky130_fd_sc_hd__clkbuf_1 g36(.A (A[7]), .X (n_9));
  sky130_fd_sc_hd__clkbuf_1 g28(.A (A[28]), .X (n_8));
  sky130_fd_sc_hd__clkbuf_1 g68(.A (B[9]), .X (n_7));
  sky130_fd_sc_hd__clkbuf_1 g49(.A (A[6]), .X (n_6));
  sky130_fd_sc_hd__clkbuf_1 g67(.A (B[7]), .X (n_5));
  sky130_fd_sc_hd__clkbuf_1 g65(.A (B[6]), .X (n_4));
  sky130_fd_sc_hd__clkbuf_1 g43(.A (A[20]), .X (n_3));
  sky130_fd_sc_hd__clkbuf_1 g5(.A (A[5]), .X (n_2));
  sky130_fd_sc_hd__clkbuf_1 g6(.A (B[5]), .X (n_1));
  sky130_fd_sc_hd__clkbuf_1 g10(.A (A[4]), .X (n_0));
endmodule

