
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr  7 2025 14:32:59 -03 (Apr  7 2025 17:32:59 UTC)

// Verification Directory fv/ripple_carry_adder_8bits 

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_2, n_3, n_4, n_5, n_6;
  sky130_fd_sc_hd__nand2_2 g121__2398(.A (n_3), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g129(.A (Cin), .Y (n_6));
  sky130_fd_sc_hd__inv_2 g131(.A (A), .Y (n_5));
  sky130_fd_sc_hd__inv_2 g133(.A (B), .Y (n_4));
  sky130_fd_sc_hd__a21o_1 g2__5107(.A1 (n_5), .A2 (n_4), .B1 (n_6), .X
       (n_3));
  sky130_fd_sc_hd__or2_1 g134__6260(.A (n_4), .B (n_5), .X (n_2));
  sky130_fd_sc_hd__xnor2_1 g135__4319(.A (n_6), .B (n_0), .Y (S));
  sky130_fd_sc_hd__xor2_1 g136__8428(.A (n_4), .B (n_5), .X (n_0));
endmodule

module full_adder_21(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  sky130_fd_sc_hd__nand2_1 g60__5526(.A (n_7), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g61__6783(.A (Cin), .B (n_6), .X (S));
  sky130_fd_sc_hd__nand2_2 g62__3680(.A (Cin), .B (n_5), .Y (n_7));
  sky130_fd_sc_hd__xor2_1 g63__1617(.A (n_0), .B (n_1), .X (n_6));
  sky130_fd_sc_hd__nand2_1 g64__2802(.A (n_3), .B (n_2), .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g65__1705(.A (n_0), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__inv_1 g67(.A (n_3), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g68(.A (A), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g70(.A (n_2), .Y (n_0));
  sky130_fd_sc_hd__clkinv_1 g71(.A (B), .Y (n_2));
endmodule

module full_adder_20(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g57__5122(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__8246(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__7098(.A (Cin), .B (n_0), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__6131(.A (n_1), .B (n_2), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g62__1881(.A (n_1), .B (A), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g64(.A (A), .X (n_2));
  sky130_fd_sc_hd__buf_1 g66(.A (B), .X (n_1));
  sky130_fd_sc_hd__or2_0 g2__5115(.A (B), .B (A), .X (n_0));
endmodule

module full_adder_19(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED, n_0, n_1, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g57__7482(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_2 g59__4733(.A (Cin), .B (n_4), .Y (n_5));
  sky130_fd_sc_hd__or2_0 g60__6161(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g61__9315(.A (n_0), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__buf_1 g63(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g65(.A (B), .X (n_0));
  sky130_fd_sc_hd__fa_1 g67__9945(.A (n_0), .B (n_1), .CIN (Cin), .COUT
       (UNCONNECTED), .SUM (S));
endmodule

module full_adder_18(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire UNCONNECTED0, n_0, n_1, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2_2 g57__2883(.A (n_5), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__nand2_1 g59__2346(.A (Cin), .B (n_4), .Y (n_5));
  sky130_fd_sc_hd__or2_0 g60__1666(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g61__7410(.A (n_0), .B (n_1), .Y (n_3));
  sky130_fd_sc_hd__clkbuf_1 g63(.A (A), .X (n_1));
  sky130_fd_sc_hd__buf_1 g65(.A (B), .X (n_0));
  sky130_fd_sc_hd__fa_1 g67__6417(.A (n_0), .B (n_1), .CIN (Cin), .COUT
       (UNCONNECTED0), .SUM (S));
endmodule

module full_adder_17(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_1 g57__5477(.A_N (n_2), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor3_1 g58__2398(.A (n_0), .B (n_1), .C (Cin), .X
       (S));
  sky130_fd_sc_hd__o21ai_2 g59__5107(.A1 (A), .A2 (B), .B1 (Cin), .Y
       (n_3));
  sky130_fd_sc_hd__and2_1 g60__6260(.A (B), .B (A), .X (n_2));
  sky130_fd_sc_hd__buf_1 g61(.A (A), .X (n_1));
  sky130_fd_sc_hd__clkbuf_1 g62(.A (B), .X (n_0));
endmodule

module full_adder_16(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_3, n_4, n_5, n_6, n_7, n_8;
  sky130_fd_sc_hd__nand2b_2 g57__4319(.A_N (n_8), .B (n_0), .Y (Cout));
  sky130_fd_sc_hd__and2_1 g60__8428(.A (B), .B (A), .X (n_8));
  sky130_fd_sc_hd__buf_1 g61(.A (A), .X (n_7));
  sky130_fd_sc_hd__clkbuf_1 g62(.A (B), .X (n_6));
  sky130_fd_sc_hd__clkbuf_1 fopt(.A (Cin), .X (n_5));
  sky130_fd_sc_hd__inv_2 g10(.A (n_3), .Y (S));
  sky130_fd_sc_hd__xnor2_1 g8__5526(.A (n_4), .B (n_5), .Y (n_3));
  sky130_fd_sc_hd__xor2_1 g9__6783(.A (n_6), .B (n_7), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g2__3680(.A (n_1), .B (Cin), .Y (n_0));
  sky130_fd_sc_hd__or2_0 g3__1617(.A (A), .B (B), .X (n_1));
endmodule

module full_adder_15(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__maj3_2 g57__2802(.A (n_1), .B (Cin), .C (n_0), .X
       (Cout));
  sky130_fd_sc_hd__mux2_2 g58__1705(.A0 (Cin), .A1 (n_2), .S (n_3), .X
       (S));
  sky130_fd_sc_hd__xor2_1 g59__5122(.A (B), .B (A), .X (n_3));
  sky130_fd_sc_hd__inv_1 g60(.A (Cin), .Y (n_2));
  sky130_fd_sc_hd__clkbuf_1 g61(.A (A), .X (n_1));
  sky130_fd_sc_hd__clkbuf_1 g62(.A (B), .X (n_0));
endmodule

module ripple_carry_adder_8bits(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20;
  full_adder F1A(.A (n_6), .B (n_13), .Cin (n_19), .S (S[0]), .Cout
       (carry[0]));
  full_adder_21 \full_adder_loop[1].FA (.A (n_0), .B (n_14), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_20 \full_adder_loop[2].FA (.A (n_16), .B (n_17), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_19 \full_adder_loop[3].FA (.A (n_18), .B (n_20), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_18 \full_adder_loop[4].FA (.A (n_15), .B (n_8), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_17 \full_adder_loop[5].FA (.A (n_1), .B (n_9), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_16 \full_adder_loop[6].FA (.A (n_4), .B (n_3), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_15 \full_adder_loop[7].FA (.A (n_10), .B (n_7), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
  sky130_fd_sc_hd__inv_1 g8(.A (n_5), .Y (n_20));
  sky130_fd_sc_hd__inv_1 g18(.A (n_2), .Y (n_19));
  sky130_fd_sc_hd__inv_1 g1(.A (n_12), .Y (n_18));
  sky130_fd_sc_hd__inv_2 g11(.A (n_11), .Y (n_17));
  sky130_fd_sc_hd__clkbuf_1 g14(.A (A[2]), .X (n_16));
  sky130_fd_sc_hd__clkbuf_1 g7(.A (A[4]), .X (n_15));
  sky130_fd_sc_hd__clkbuf_1 g15(.A (B[1]), .X (n_14));
  sky130_fd_sc_hd__clkbuf_1 g17(.A (B[0]), .X (n_13));
  sky130_fd_sc_hd__inv_2 g2(.A (A[3]), .Y (n_12));
  sky130_fd_sc_hd__clkinv_1 g12(.A (B[2]), .Y (n_11));
  sky130_fd_sc_hd__clkbuf_1 g13(.A (A[7]), .X (n_10));
  sky130_fd_sc_hd__clkbuf_1 g20(.A (B[5]), .X (n_9));
  sky130_fd_sc_hd__clkbuf_1 g16(.A (B[4]), .X (n_8));
  sky130_fd_sc_hd__clkbuf_1 g3(.A (B[7]), .X (n_7));
  sky130_fd_sc_hd__clkbuf_1 g4(.A (A[0]), .X (n_6));
  sky130_fd_sc_hd__clkinv_1 g9(.A (B[3]), .Y (n_5));
  sky130_fd_sc_hd__clkbuf_1 g21(.A (A[6]), .X (n_4));
  sky130_fd_sc_hd__clkbuf_1 g6(.A (B[6]), .X (n_3));
  sky130_fd_sc_hd__inv_2 g19(.A (Cin), .Y (n_2));
  sky130_fd_sc_hd__clkbuf_1 g10(.A (A[5]), .X (n_1));
  sky130_fd_sc_hd__clkbuf_1 g5(.A (A[1]), .X (n_0));
endmodule

