
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr  7 2025 18:23:37 -03 (Apr  7 2025 21:23:37 UTC)

// Verification Directory fv/carry_select_adder_56678_32bits 

module full_adder_32_230(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_12, n_13;
  or g10 (n_12, wc, B);
  not gc (wc, A);
  or g11 (n_13, A, wc0);
  not gc0 (wc0, B);
  nand g12 (S, n_12, n_13);
  and g13 (Cout, A, B);
endmodule

module full_adder_224(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_16, n_25, n_30, n_56, n_57, n_58, n_59;
  nand g69 (Cout, n_16, n_25);
  or g70 (n_56, wc1, n_13);
  not gc1 (wc1, Cin);
  or g71 (n_57, Cin, wc2);
  not gc2 (wc2, n_13);
  nand g72 (S, n_56, n_57);
  nand g73 (n_25, B, n_30);
  nand g74 (n_16, A, Cin);
  or g75 (n_30, A, Cin);
  or g76 (n_58, wc3, B);
  not gc3 (wc3, A);
  or g77 (n_59, A, wc4);
  not gc4 (wc4, B);
  nand g78 (n_13, n_58, n_59);
endmodule

module full_adder_223(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc5, n_13);
  not gc5 (wc5, Cin);
  or g67 (n_52, Cin, wc6);
  not gc6 (wc6, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc7, B);
  not gc7 (wc7, A);
  or g72 (n_54, A, wc8);
  not gc8 (wc8, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_222(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc9, n_13);
  not gc9 (wc9, Cin);
  or g67 (n_52, Cin, wc10);
  not gc10 (wc10, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc11, B);
  not gc11 (wc11, A);
  or g72 (n_54, A, wc12);
  not gc12 (wc12, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_221(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc13, n_13);
  not gc13 (wc13, Cin);
  or g67 (n_52, Cin, wc14);
  not gc14 (wc14, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc15, B);
  not gc15 (wc15, A);
  or g72 (n_54, A, wc16);
  not gc16 (wc16, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_202(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc17, n_13);
  not gc17 (wc17, Cin);
  or g67 (n_52, Cin, wc18);
  not gc18 (wc18, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc19, B);
  not gc19 (wc19, A);
  or g72 (n_54, A, wc20);
  not gc20 (wc20, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module ripple_carry_adder_WIDTH6(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder_32_230 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]),
       .Cout (carry[0]));
  full_adder_224 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_223 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_222 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_221 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_202 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_38_231(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_14;
  nand g20 (n_14, A, B);
  or g21 (Cout, A, B);
  nand g22 (S, n_14, Cout);
endmodule

module full_adder_206(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_16, n_24, n_28, n_54, n_55, n_56, n_57;
  nand g65 (Cout, n_16, n_24);
  or g66 (n_54, wc21, n_13);
  not gc21 (wc21, Cin);
  or g67 (n_55, Cin, wc22);
  not gc22 (wc22, n_13);
  nand g68 (S, n_54, n_55);
  nand g69 (n_24, B, n_28);
  nand g70 (n_16, A, Cin);
  or g71 (n_28, Cin, A);
  or g72 (n_56, wc23, B);
  not gc23 (wc23, A);
  or g73 (n_57, A, wc24);
  not gc24 (wc24, B);
  nand g74 (n_13, n_56, n_57);
endmodule

module full_adder_205(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc25, n_13);
  not gc25 (wc25, Cin);
  or g67 (n_52, Cin, wc26);
  not gc26 (wc26, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc27, B);
  not gc27 (wc27, A);
  or g72 (n_54, A, wc28);
  not gc28 (wc28, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_204(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc29, n_13);
  not gc29 (wc29, Cin);
  or g67 (n_52, Cin, wc30);
  not gc30 (wc30, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc31, B);
  not gc31 (wc31, A);
  or g72 (n_54, A, wc32);
  not gc32 (wc32, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_203(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc33, n_13);
  not gc33 (wc33, Cin);
  or g67 (n_52, Cin, wc34);
  not gc34 (wc34, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc35, B);
  not gc35 (wc35, A);
  or g72 (n_54, A, wc36);
  not gc36 (wc36, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module ripple_carry_adder_WIDTH6_3_234(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder_38_231 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]),
       .Cout (carry[0]));
  full_adder_206 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_205 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_204 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_203 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_202 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_32(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_12, n_13;
  or g10 (n_12, wc37, B);
  not gc37 (wc37, A);
  or g11 (n_13, A, wc38);
  not gc38 (wc38, B);
  nand g12 (S, n_12, n_13);
  and g13 (Cout, A, B);
endmodule

module full_adder_201(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_16, n_25, n_30, n_56, n_57, n_58, n_59;
  nand g69 (Cout, n_16, n_25);
  or g70 (n_56, wc39, n_13);
  not gc39 (wc39, Cin);
  or g71 (n_57, Cin, wc40);
  not gc40 (wc40, n_13);
  nand g72 (S, n_56, n_57);
  nand g73 (n_25, B, n_30);
  nand g74 (n_16, A, Cin);
  or g75 (n_30, A, Cin);
  or g76 (n_58, wc41, B);
  not gc41 (wc41, A);
  or g77 (n_59, A, wc42);
  not gc42 (wc42, B);
  nand g78 (n_13, n_58, n_59);
endmodule

module full_adder_200(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc43, n_13);
  not gc43 (wc43, Cin);
  or g64 (n_49, Cin, wc44);
  not gc44 (wc44, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc45, B);
  not gc45 (wc45, A);
  or g69 (n_51, A, wc46);
  not gc46 (wc46, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module full_adder_199(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc47, n_13);
  not gc47 (wc47, Cin);
  or g64 (n_49, Cin, wc48);
  not gc48 (wc48, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc49, B);
  not gc49 (wc49, A);
  or g69 (n_51, A, wc50);
  not gc50 (wc50, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module full_adder_198(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc51, n_13);
  not gc51 (wc51, Cin);
  or g64 (n_49, Cin, wc52);
  not gc52 (wc52, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc53, B);
  not gc53 (wc53, A);
  or g69 (n_51, A, wc54);
  not gc54 (wc54, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module full_adder_192(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc55, n_13);
  not gc55 (wc55, Cin);
  or g64 (n_49, Cin, wc56);
  not gc56 (wc56, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc57, B);
  not gc57 (wc57, A);
  or g69 (n_51, A, wc58);
  not gc58 (wc58, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module ripple_carry_adder_WIDTH6_233(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder_32 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]), .Cout
       (carry[0]));
  full_adder_201 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_200 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_199 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_198 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_192 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_38(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_14;
  nand g20 (n_14, A, B);
  or g21 (Cout, A, B);
  nand g22 (S, n_14, Cout);
endmodule

module full_adder_196(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_16, n_24, n_28, n_54, n_55, n_56, n_57;
  nand g65 (Cout, n_16, n_24);
  or g66 (n_54, wc59, n_13);
  not gc59 (wc59, Cin);
  or g67 (n_55, Cin, wc60);
  not gc60 (wc60, n_13);
  nand g68 (S, n_54, n_55);
  nand g69 (n_24, B, n_28);
  nand g70 (n_16, A, Cin);
  or g71 (n_28, Cin, A);
  or g72 (n_56, wc61, B);
  not gc61 (wc61, A);
  or g73 (n_57, A, wc62);
  not gc62 (wc62, B);
  nand g74 (n_13, n_56, n_57);
endmodule

module full_adder_195(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc63, n_13);
  not gc63 (wc63, Cin);
  or g67 (n_52, Cin, wc64);
  not gc64 (wc64, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc65, B);
  not gc65 (wc65, A);
  or g72 (n_54, A, wc66);
  not gc66 (wc66, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_194(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc67, n_13);
  not gc67 (wc67, Cin);
  or g64 (n_49, Cin, wc68);
  not gc68 (wc68, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc69, B);
  not gc69 (wc69, A);
  or g69 (n_51, A, wc70);
  not gc70 (wc70, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module full_adder_193(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc71, n_13);
  not gc71 (wc71, Cin);
  or g64 (n_49, Cin, wc72);
  not gc72 (wc72, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc73, B);
  not gc73 (wc73, A);
  or g69 (n_51, A, wc74);
  not gc74 (wc74, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module ripple_carry_adder_WIDTH6_3(A, B, Cin, S, Cout);
  input [5:0] A, B;
  input Cin;
  output [5:0] S;
  output Cout;
  wire [5:0] A, B;
  wire Cin;
  wire [5:0] S;
  wire Cout;
  wire [5:0] carry;
  full_adder_38 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]), .Cout
       (carry[0]));
  full_adder_196 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_195 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_194 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_193 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_192 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (Cout));
endmodule

module full_adder_11(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_12, n_13;
  or g10 (n_12, wc75, B);
  not gc75 (wc75, A);
  or g11 (n_13, A, wc76);
  not gc76 (wc76, B);
  nand g12 (S, n_12, n_13);
  and g13 (Cout, A, B);
endmodule

module full_adder_219(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_20, n_25, n_26, n_28, n_29, n_30, n_31;
  or g31 (n_20, A, B);
  nand g38 (Cout, n_25, n_26);
  or g39 (n_28, wc77, n_13);
  not gc77 (wc77, Cin);
  or g40 (n_29, Cin, wc78);
  not gc78 (wc78, n_13);
  nand g41 (S, n_28, n_29);
  nand g42 (n_25, n_20, Cin);
  nand g43 (n_26, A, B);
  or g44 (n_30, wc79, B);
  not gc79 (wc79, A);
  or g45 (n_31, A, wc80);
  not gc80 (wc80, B);
  nand g46 (n_13, n_30, n_31);
endmodule

module full_adder_218(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc81, n_13);
  not gc81 (wc81, Cin);
  or g28 (n_27, Cin, wc82);
  not gc82 (wc82, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc83, B);
  not gc83 (wc83, A);
  or g33 (n_29, A, wc84);
  not gc84 (wc84, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_217(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc85, n_13);
  not gc85 (wc85, Cin);
  or g28 (n_27, Cin, wc86);
  not gc86 (wc86, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc87, B);
  not gc87 (wc87, A);
  or g33 (n_29, A, wc88);
  not gc88 (wc88, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_216(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc89, n_13);
  not gc89 (wc89, Cin);
  or g28 (n_27, Cin, wc90);
  not gc90 (wc90, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc91, B);
  not gc91 (wc91, A);
  or g33 (n_29, A, wc92);
  not gc92 (wc92, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_215(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc93, n_13);
  not gc93 (wc93, Cin);
  or g28 (n_27, Cin, wc94);
  not gc94 (wc94, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc95, B);
  not gc95 (wc95, A);
  or g33 (n_29, A, wc96);
  not gc96 (wc96, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_214(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc97, n_13);
  not gc97 (wc97, Cin);
  or g28 (n_27, Cin, wc98);
  not gc98 (wc98, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc99, B);
  not gc99 (wc99, A);
  or g33 (n_29, A, wc100);
  not gc100 (wc100, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module ripple_carry_adder_WIDTH7(A, B, Cin, S, Cout);
  input [6:0] A, B;
  input Cin;
  output [6:0] S;
  output Cout;
  wire [6:0] A, B;
  wire Cin;
  wire [6:0] S;
  wire Cout;
  wire [6:0] carry;
  full_adder_11 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]), .Cout
       (carry[0]));
  full_adder_219 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_218 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_217 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_216 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_215 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_214 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (Cout));
endmodule

module full_adder_51(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_14;
  nand g20 (n_14, A, B);
  or g21 (Cout, A, B);
  nand g22 (S, n_14, Cout);
endmodule

module full_adder_191(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_16, n_24, n_28, n_54, n_55, n_56, n_57;
  nand g65 (Cout, n_16, n_24);
  or g66 (n_54, wc101, n_13);
  not gc101 (wc101, Cin);
  or g67 (n_55, Cin, wc102);
  not gc102 (wc102, n_13);
  nand g68 (S, n_54, n_55);
  nand g69 (n_24, B, n_28);
  nand g70 (n_16, A, Cin);
  or g71 (n_28, Cin, A);
  or g72 (n_56, wc103, B);
  not gc103 (wc103, A);
  or g73 (n_57, A, wc104);
  not gc104 (wc104, B);
  nand g74 (n_13, n_56, n_57);
endmodule

module full_adder_190(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc105, n_13);
  not gc105 (wc105, Cin);
  or g64 (n_49, Cin, wc106);
  not gc106 (wc106, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc107, B);
  not gc107 (wc107, A);
  or g69 (n_51, A, wc108);
  not gc108 (wc108, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module full_adder_189(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc109, n_13);
  not gc109 (wc109, Cin);
  or g64 (n_49, Cin, wc110);
  not gc110 (wc110, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc111, B);
  not gc111 (wc111, A);
  or g69 (n_51, A, wc112);
  not gc112 (wc112, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module full_adder_188(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_48, n_49, n_50, n_51, n_52, n_53;
  or g55 (n_48, B, A);
  nand g63 (Cout, n_23, n_49);
  or g64 (n_50, wc113, n_13);
  not gc113 (wc113, Cin);
  or g65 (n_51, Cin, wc114);
  not gc114 (wc114, n_13);
  nand g66 (S, n_50, n_51);
  nand g67 (n_49, n_48, Cin);
  nand g68 (n_23, A, B);
  or g69 (n_52, wc115, B);
  not gc115 (wc115, A);
  or g70 (n_53, A, wc116);
  not gc116 (wc116, B);
  nand g71 (n_13, n_52, n_53);
endmodule

module full_adder_187(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_15, n_16, n_23, n_24, n_25, n_26, n_27;
  wire n_28;
  or g36 (Cout, wc117, n_24);
  not gc117 (wc117, n_16);
  or g37 (n_25, wc118, n_13);
  not gc118 (wc118, Cin);
  or g38 (n_26, Cin, wc119);
  not gc119 (wc119, n_13);
  nand g39 (S, n_25, n_26);
  nand g40 (n_24, n_23, n_15);
  or g41 (n_27, wc120, B);
  not gc120 (wc120, A);
  or g42 (n_28, A, wc121);
  not gc121 (wc121, B);
  nand g43 (n_13, n_27, n_28);
  nand g44 (n_15, B, Cin);
  nand g45 (n_16, A, Cin);
  nand g46 (n_23, A, B);
endmodule

module full_adder_186(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_48, n_49, n_50, n_51;
  or g55 (n_46, B, A);
  nand g62 (Cout, n_23, n_47);
  or g63 (n_48, wc122, n_13);
  not gc122 (wc122, Cin);
  or g64 (n_49, Cin, wc123);
  not gc123 (wc123, n_13);
  nand g65 (S, n_48, n_49);
  nand g66 (n_47, n_46, Cin);
  nand g67 (n_23, A, B);
  or g68 (n_50, wc124, B);
  not gc124 (wc124, A);
  or g69 (n_51, A, wc125);
  not gc125 (wc125, B);
  nand g70 (n_13, n_50, n_51);
endmodule

module ripple_carry_adder_WIDTH7_1(A, B, Cin, S, Cout);
  input [6:0] A, B;
  input Cin;
  output [6:0] S;
  output Cout;
  wire [6:0] A, B;
  wire Cin;
  wire [6:0] S;
  wire Cout;
  wire [6:0] carry;
  full_adder_51 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]), .Cout
       (carry[0]));
  full_adder_191 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_190 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_189 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_188 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_187 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_186 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (Cout));
endmodule

module full_adder_213(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_20, n_25, n_26, n_28, n_29, n_30, n_31;
  or g23 (n_20, A, B);
  nand g30 (Cout, n_25, n_26);
  or g31 (n_28, wc126, n_13);
  not gc126 (wc126, Cin);
  or g32 (n_29, Cin, wc127);
  not gc127 (wc127, n_13);
  nand g33 (S, n_28, n_29);
  nand g34 (n_25, n_20, Cin);
  nand g35 (n_26, A, B);
  or g36 (n_30, wc128, B);
  not gc128 (wc128, A);
  or g37 (n_31, A, wc129);
  not gc129 (wc129, B);
  nand g38 (n_13, n_30, n_31);
endmodule

module full_adder_212(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc130, n_13);
  not gc130 (wc130, Cin);
  or g28 (n_27, Cin, wc131);
  not gc131 (wc131, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc132, B);
  not gc132 (wc132, A);
  or g33 (n_29, A, wc133);
  not gc133 (wc133, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_211(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc134, n_13);
  not gc134 (wc134, Cin);
  or g28 (n_27, Cin, wc135);
  not gc135 (wc135, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc136, B);
  not gc136 (wc136, A);
  or g33 (n_29, A, wc137);
  not gc137 (wc137, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_210(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc138, n_13);
  not gc138 (wc138, Cin);
  or g28 (n_27, Cin, wc139);
  not gc139 (wc139, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc140, B);
  not gc140 (wc140, A);
  or g33 (n_29, A, wc141);
  not gc141 (wc141, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_209(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc142, n_13);
  not gc142 (wc142, Cin);
  or g28 (n_27, Cin, wc143);
  not gc143 (wc143, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc144, B);
  not gc144 (wc144, A);
  or g33 (n_29, A, wc145);
  not gc145 (wc145, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_208(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc146, n_13);
  not gc146 (wc146, Cin);
  or g28 (n_27, Cin, wc147);
  not gc147 (wc147, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc148, B);
  not gc148 (wc148, A);
  or g33 (n_29, A, wc149);
  not gc149 (wc149, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_179(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc150, n_13);
  not gc150 (wc150, Cin);
  or g28 (n_27, Cin, wc151);
  not gc151 (wc151, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc152, B);
  not gc152 (wc152, A);
  or g33 (n_29, A, wc153);
  not gc153 (wc153, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module ripple_carry_adder_WIDTH8(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder_11 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]), .Cout
       (carry[0]));
  full_adder_213 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_212 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_211 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_210 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_209 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_208 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_179 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_185(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc154, n_13);
  not gc154 (wc154, Cin);
  or g28 (n_27, Cin, wc155);
  not gc155 (wc155, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc156, B);
  not gc156 (wc156, A);
  or g33 (n_29, A, wc157);
  not gc157 (wc157, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_184(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc158, n_13);
  not gc158 (wc158, Cin);
  or g28 (n_27, Cin, wc159);
  not gc159 (wc159, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc160, B);
  not gc160 (wc160, A);
  or g33 (n_29, A, wc161);
  not gc161 (wc161, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_183(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc162, n_13);
  not gc162 (wc162, Cin);
  or g28 (n_27, Cin, wc163);
  not gc163 (wc163, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc164, B);
  not gc164 (wc164, A);
  or g33 (n_29, A, wc165);
  not gc165 (wc165, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_182(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc166, n_13);
  not gc166 (wc166, Cin);
  or g28 (n_27, Cin, wc167);
  not gc167 (wc167, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc168, B);
  not gc168 (wc168, A);
  or g33 (n_29, A, wc169);
  not gc169 (wc169, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_181(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc170, n_13);
  not gc170 (wc170, Cin);
  or g28 (n_27, Cin, wc171);
  not gc171 (wc171, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc172, B);
  not gc172 (wc172, A);
  or g33 (n_29, A, wc173);
  not gc173 (wc173, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module full_adder_180(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_19, n_24, n_25, n_26, n_27, n_28, n_29;
  or g21 (n_19, A, B);
  nand g26 (Cout, n_24, n_25);
  or g27 (n_26, wc174, n_13);
  not gc174 (wc174, Cin);
  or g28 (n_27, Cin, wc175);
  not gc175 (wc175, n_13);
  nand g29 (S, n_26, n_27);
  nand g30 (n_24, n_19, Cin);
  nand g31 (n_25, A, B);
  or g32 (n_28, wc176, B);
  not gc176 (wc176, A);
  or g33 (n_29, A, wc177);
  not gc177 (wc177, B);
  nand g34 (n_13, n_28, n_29);
endmodule

module ripple_carry_adder_WIDTH8_1(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder_51 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]), .Cout
       (carry[0]));
  full_adder_185 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_184 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_183 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_182 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_181 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_180 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_179 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_16, n_25, n_30, n_56, n_57, n_58, n_59;
  nand g69 (Cout, n_16, n_25);
  or g70 (n_56, wc178, n_13);
  not gc178 (wc178, Cin);
  or g71 (n_57, Cin, wc179);
  not gc179 (wc179, n_13);
  nand g72 (S, n_56, n_57);
  nand g73 (n_25, B, n_30);
  nand g74 (n_16, A, Cin);
  or g75 (n_30, A, Cin);
  or g76 (n_58, wc180, B);
  not gc180 (wc180, A);
  or g77 (n_59, A, wc181);
  not gc181 (wc181, B);
  nand g78 (n_13, n_58, n_59);
endmodule

module full_adder_228(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc182, n_13);
  not gc182 (wc182, Cin);
  or g67 (n_52, Cin, wc183);
  not gc183 (wc183, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc184, B);
  not gc184 (wc184, A);
  or g72 (n_54, A, wc185);
  not gc185 (wc185, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_227(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc186, n_13);
  not gc186 (wc186, Cin);
  or g67 (n_52, Cin, wc187);
  not gc187 (wc187, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc188, B);
  not gc188 (wc188, A);
  or g72 (n_54, A, wc189);
  not gc189 (wc189, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_226(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc190, n_13);
  not gc190 (wc190, Cin);
  or g67 (n_52, Cin, wc191);
  not gc191 (wc191, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc192, B);
  not gc192 (wc192, A);
  or g72 (n_54, A, wc193);
  not gc193 (wc193, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module full_adder_225(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_13, n_23, n_46, n_47, n_51, n_52, n_53, n_54;
  or g55 (n_46, B, A);
  nand g65 (Cout, n_23, n_47);
  or g66 (n_51, wc194, n_13);
  not gc194 (wc194, Cin);
  or g67 (n_52, Cin, wc195);
  not gc195 (wc195, n_13);
  nand g68 (S, n_51, n_52);
  nand g69 (n_47, n_46, Cin);
  nand g70 (n_23, A, B);
  or g71 (n_53, wc196, B);
  not gc196 (wc196, A);
  or g72 (n_54, A, wc197);
  not gc197 (wc197, B);
  nand g73 (n_13, n_53, n_54);
endmodule

module ripple_carry_adder_WIDTH5(A, B, Cin, S, Cout);
  input [4:0] A, B;
  input Cin;
  output [4:0] S;
  output Cout;
  wire [4:0] A, B;
  wire Cin;
  wire [4:0] S;
  wire Cout;
  wire [4:0] carry;
  full_adder F1A(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (carry[0]));
  full_adder_228 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_227 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_226 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_225 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (Cout));
endmodule

module carry_select_adder_56678_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire [31:0] S0;
  wire [4:0] C0;
  wire [31:0] S1;
  wire [4:0] C1;
  wire [4:0] C_mid;
  wire n_110, n_117, n_125, n_147, n_148, n_153, n_154, n_165;
  wire n_166, n_171, n_172, n_177, n_178, n_183, n_184, n_189;
  wire n_190, n_195, n_196, n_201, n_202, n_207, n_208, n_213;
  wire n_214, n_219, n_220, n_225, n_226, n_231, n_232, n_237;
  wire n_238, n_243, n_244, n_249, n_250, n_255, n_256, n_261;
  wire n_262, n_267, n_268, n_273, n_274, n_279, n_280, n_285;
  wire n_286, n_291, n_292, n_297, n_298, n_303, n_304, n_309;
  wire n_310, n_315, n_316, n_321, n_322, n_327, n_328, n_3306;
  wire n_3308, n_3314, n_3315, n_3529, n_3530, n_3554, n_3555;
  ripple_carry_adder_WIDTH6 \CSA_BLOCKS[1].RCA_C0 (.A (A[10:5]), .B
       (B[10:5]), .Cin (1'b0), .S (S0[10:5]), .Cout (C0[1]));
  ripple_carry_adder_WIDTH6_3_234 \CSA_BLOCKS[1].RCA_C1 (.A (A[10:5]),
       .B (B[10:5]), .Cin (1'b1), .S (S1[10:5]), .Cout (C1[1]));
  ripple_carry_adder_WIDTH6_233 \CSA_BLOCKS[2].RCA_C0 (.A (A[16:11]),
       .B (B[16:11]), .Cin (1'b0), .S (S0[16:11]), .Cout (C0[2]));
  ripple_carry_adder_WIDTH6_3 \CSA_BLOCKS[2].RCA_C1 (.A (A[16:11]), .B
       (B[16:11]), .Cin (1'b1), .S (S1[16:11]), .Cout (C1[2]));
  ripple_carry_adder_WIDTH7 \CSA_BLOCKS[3].RCA_C0 (.A (A[23:17]), .B
       (B[23:17]), .Cin (1'b0), .S (S0[23:17]), .Cout (C0[3]));
  ripple_carry_adder_WIDTH7_1 \CSA_BLOCKS[3].RCA_C1 (.A (A[23:17]), .B
       (B[23:17]), .Cin (1'b1), .S (S1[23:17]), .Cout (C1[3]));
  ripple_carry_adder_WIDTH8 \CSA_BLOCKS[4].RCA_C0 (.A (A[31:24]), .B
       (B[31:24]), .Cin (1'b0), .S (S0[31:24]), .Cout (C0[4]));
  ripple_carry_adder_WIDTH8_1 \CSA_BLOCKS[4].RCA_C1 (.A (A[31:24]), .B
       (B[31:24]), .Cin (1'b1), .S (S1[31:24]), .Cout (C1[4]));
  ripple_carry_adder_WIDTH5 RCA_LSB(.A (A[4:0]), .B (B[4:0]), .Cin
       (Cin), .S (S[4:0]), .Cout (C_mid[0]));
  nand g2598 (n_125, n_3314, n_3315);
  nand g2789 (n_3529, C1[3], C0[2]);
  nand g2814 (n_3554, C1[3], C1[2]);
  nand g5932 (S[17], n_255, n_256);
  nand g5933 (S[30], n_171, n_172);
  nand g5934 (S[29], n_177, n_178);
  nand g5935 (S[28], n_183, n_184);
  nand g5936 (S[27], n_189, n_190);
  nand g5937 (S[26], n_195, n_196);
  nand g5938 (S[25], n_201, n_202);
  nand g5939 (S[24], n_207, n_208);
  nand g5940 (Cout, n_213, n_214);
  nand g5941 (S[23], n_219, n_220);
  nand g5942 (S[22], n_225, n_226);
  nand g5943 (S[21], n_231, n_232);
  nand g5944 (S[20], n_237, n_238);
  nand g5945 (S[19], n_243, n_244);
  nand g5946 (S[18], n_249, n_250);
  nand g5947 (S[31], n_165, n_166);
  nand g5948 (n_232, n_117, S1[21]);
  nand g5949 (n_184, n_125, S1[28]);
  or g5950 (n_231, n_117, wc198);
  not gc198 (wc198, S0[21]);
  or g5951 (n_183, n_125, wc199);
  not gc199 (wc199, S0[28]);
  nand g5952 (n_226, n_117, S1[22]);
  or g5953 (n_225, n_117, wc200);
  not gc200 (wc200, S0[22]);
  nand g5954 (n_166, n_125, S1[31]);
  nand g5955 (n_220, n_117, S1[23]);
  or g5956 (n_219, n_117, wc201);
  not gc201 (wc201, S0[23]);
  nand g5957 (n_178, n_125, S1[29]);
  nand g5958 (n_214, n_125, C1[4]);
  or g5959 (n_213, n_125, wc202);
  not gc202 (wc202, C0[4]);
  or g5960 (n_177, n_125, wc203);
  not gc203 (wc203, S0[29]);
  nand g5961 (n_208, n_125, S1[24]);
  or g5962 (n_207, n_125, wc204);
  not gc204 (wc204, S0[24]);
  or g5963 (n_165, n_125, wc205);
  not gc205 (wc205, S0[31]);
  nand g5964 (n_202, n_125, S1[25]);
  or g5965 (n_201, n_125, wc206);
  not gc206 (wc206, S0[25]);
  nand g5966 (n_172, n_125, S1[30]);
  nand g5967 (n_196, n_125, S1[26]);
  or g5968 (n_195, n_125, wc207);
  not gc207 (wc207, S0[26]);
  nand g5969 (n_256, n_117, S1[17]);
  or g5970 (n_255, n_117, wc208);
  not gc208 (wc208, S0[17]);
  or g5971 (n_171, n_125, wc209);
  not gc209 (wc209, S0[30]);
  nand g5972 (n_250, n_117, S1[18]);
  or g5973 (n_249, n_117, wc210);
  not gc210 (wc210, S0[18]);
  nand g5974 (n_190, n_125, S1[27]);
  nand g5975 (n_244, n_117, S1[19]);
  or g5976 (n_243, n_117, wc211);
  not gc211 (wc211, S0[19]);
  or g5977 (n_189, n_125, wc212);
  not gc212 (wc212, S0[27]);
  nand g5978 (n_238, n_117, S1[20]);
  or g5979 (n_237, n_117, wc213);
  not gc213 (wc213, S0[20]);
  nand g5980 (n_117, n_153, n_154);
  nand g5981 (S[11], n_327, n_328);
  nand g5982 (S[16], n_297, n_298);
  nand g5983 (S[13], n_315, n_316);
  nand g5984 (S[14], n_309, n_310);
  nand g5985 (S[15], n_303, n_304);
  nand g5986 (S[12], n_321, n_322);
  or g5987 (n_309, n_110, wc214);
  not gc214 (wc214, S0[14]);
  nand g5988 (n_3315, n_3555, n_110);
  nand g5989 (n_310, n_110, S1[14]);
  nand g5990 (n_298, n_110, S1[16]);
  or g5991 (n_315, n_110, wc215);
  not gc215 (wc215, S0[13]);
  nand g5992 (n_316, n_110, S1[13]);
  nand g5993 (n_154, n_110, C1[2]);
  or g5994 (n_321, n_110, wc216);
  not gc216 (wc216, S0[12]);
  nand g5995 (n_322, n_110, S1[12]);
  or g5996 (n_153, n_110, wc217);
  not gc217 (wc217, C0[2]);
  or g5997 (n_327, n_110, wc218);
  not gc218 (wc218, S0[11]);
  nand g5998 (n_328, n_110, S1[11]);
  or g5999 (n_3314, n_110, wc219);
  not gc219 (wc219, n_3530);
  or g6000 (n_303, n_110, wc220);
  not gc220 (wc220, S0[15]);
  nand g6001 (n_304, n_110, S1[15]);
  or g6002 (n_297, n_110, wc221);
  not gc221 (wc221, S0[16]);
  nand g6003 (S[7], n_279, n_280);
  nand g6004 (S[10], n_261, n_262);
  nand g6005 (S[6], n_285, n_286);
  nand g6006 (S[8], n_273, n_274);
  nand g6007 (n_3530, n_3529, n_3306);
  nand g6008 (n_110, n_147, n_148);
  nand g6009 (S[9], n_267, n_268);
  nand g6010 (S[5], n_291, n_292);
  nand g6011 (n_3555, n_3554, n_3308);
  nand g6012 (n_280, C_mid[0], S1[7]);
  or g6013 (n_279, C_mid[0], wc222);
  not gc222 (wc222, S0[7]);
  nand g6014 (n_274, C_mid[0], S1[8]);
  or g6015 (n_273, C_mid[0], wc223);
  not gc223 (wc223, S0[8]);
  nand g6016 (n_268, C_mid[0], S1[9]);
  or g6017 (n_267, C_mid[0], wc224);
  not gc224 (wc224, S0[9]);
  nand g6018 (n_262, C_mid[0], S1[10]);
  or g6019 (n_261, C_mid[0], wc225);
  not gc225 (wc225, S0[10]);
  or g6020 (n_148, C_mid[0], wc226);
  not gc226 (wc226, C0[1]);
  nand g6021 (n_286, C_mid[0], S1[6]);
  nand g6022 (n_147, C_mid[0], C1[1]);
  or g6023 (n_291, C_mid[0], wc227);
  not gc227 (wc227, S0[5]);
  nand g6024 (n_292, C_mid[0], S1[5]);
  or g6025 (n_3308, C1[2], wc228);
  not gc228 (wc228, C0[3]);
  or g6026 (n_3306, C0[2], wc229);
  not gc229 (wc229, C0[3]);
  or g6027 (n_285, C_mid[0], wc230);
  not gc230 (wc230, S0[6]);
endmodule

