
// Generated by Cadence Genus(TM) Synthesis Solution 23.12-s086_1
// Generated on: Apr  9 2025 12:45:13 -03 (Apr  9 2025 15:45:13 UTC)

// Verification Directory fv/carry_select_adder_8888_32bits 

module full_adder_24_228(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nor2_1 g29__2398(.A (n_2), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g31(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g33(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xor2_1 g2__5107(.A (n_2), .B (n_1), .X (S));
endmodule

module full_adder_219(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__o21ai_1 g95__6260(.A1 (n_2), .A2 (n_0), .B1 (n_1),
       .Y (Cout));
  sky130_fd_sc_hd__xnor2_1 g96__4319(.A (n_0), .B (n_3), .Y (S));
  sky130_fd_sc_hd__xor2_1 g97__8428(.A (B), .B (A), .X (n_3));
  sky130_fd_sc_hd__nor2_1 g98__5526(.A (A), .B (B), .Y (n_2));
  sky130_fd_sc_hd__nand2_1 g99__6783(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__inv_2 g100(.A (Cin), .Y (n_0));
endmodule

module full_adder_218(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4;
  sky130_fd_sc_hd__nand2b_1 g57__3680(.A_N (n_3), .B (n_4), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__1617(.A (n_0), .B (Cin), .X (S));
  sky130_fd_sc_hd__o21ai_0 g59__2802(.A1 (A), .A2 (B), .B1 (Cin), .Y
       (n_4));
  sky130_fd_sc_hd__nor2_1 g61__1705(.A (n_1), .B (n_2), .Y (n_3));
  sky130_fd_sc_hd__clkinv_1 g63(.A (A), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g65(.A (B), .Y (n_1));
  sky130_fd_sc_hd__xor2_1 g2__5122(.A (n_1), .B (n_2), .X (n_0));
endmodule

module full_adder_217(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__8246(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_216(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__7098(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_215(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__6131(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_214(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__1881(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_213(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__5115(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module ripple_carry_adder_WIDTH8_5_231(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder_24_228 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]),
       .Cout (carry[0]));
  full_adder_219 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_218 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_217 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_216 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_215 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_214 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_213 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_32_230(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nand2_1 g31__7482(.A (n_1), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g33(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g35(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g2__4733(.A (n_1), .B (n_2), .Y (S));
endmodule

module full_adder_212(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2b_1 g57__6161(.A_N (n_3), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__9315(.A (Cin), .B (n_0), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__9945(.A (Cin), .B (n_4), .Y (n_5));
  sky130_fd_sc_hd__nand2_1 g61__2883(.A (n_2), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__nor2_1 g62__2346(.A (n_1), .B (n_2), .Y (n_3));
  sky130_fd_sc_hd__inv_2 g64(.A (A), .Y (n_2));
  sky130_fd_sc_hd__inv_2 g66(.A (B), .Y (n_1));
  sky130_fd_sc_hd__xor2_1 g2__1666(.A (n_1), .B (n_2), .X (n_0));
endmodule

module full_adder_211(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3, n_4, n_5;
  sky130_fd_sc_hd__nand2b_1 g57__7410(.A_N (n_2), .B (n_5), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__6417(.A (n_4), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5477(.A (Cin), .B (n_3), .Y (n_5));
  sky130_fd_sc_hd__xor2_1 g60__2398(.A (B), .B (A), .X (n_4));
  sky130_fd_sc_hd__nand2_1 g61__5107(.A (n_1), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__nor2_1 g62__6260(.A (n_0), .B (n_1), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g63(.A (A), .Y (n_1));
  sky130_fd_sc_hd__clkinv_1 g64(.A (B), .Y (n_0));
endmodule

module full_adder_210(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__4319(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_209(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__8428(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_208(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__5526(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_207(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__6783(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_206(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__3680(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module ripple_carry_adder_WIDTH8_6_233(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder_32_230 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]),
       .Cout (carry[0]));
  full_adder_212 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_211 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_210 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_209 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_208 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_207 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_206 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_24(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nor2_1 g29__1617(.A (n_2), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g31(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g33(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xor2_1 g2__2802(.A (n_2), .B (n_1), .X (S));
endmodule

module full_adder_205(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g65__1705(.A (Cin), .B (A), .CIN (B), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_204(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__5122(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_203(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__8246(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_202(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__7098(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_201(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__6131(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_200(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__1881(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_199(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__5115(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module ripple_carry_adder_WIDTH8_5_232(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder_24 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]), .Cout
       (carry[0]));
  full_adder_205 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_204 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_203 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_202 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_201 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_200 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_199 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_32(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2;
  sky130_fd_sc_hd__nand2_1 g38__7482(.A (n_1), .B (n_2), .Y (Cout));
  sky130_fd_sc_hd__clkinv_1 g40(.A (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g42(.A (A), .Y (n_1));
  sky130_fd_sc_hd__xnor2_1 g2__4733(.A (n_1), .B (n_2), .Y (S));
endmodule

module full_adder_198(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__6161(.A (A), .B (Cin), .CIN (B), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_197(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__9315(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_196(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__9945(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_195(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__2883(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_194(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__2346(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_193(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__1666(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_192(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__7410(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module ripple_carry_adder_WIDTH8_6_234(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder_32 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]), .Cout
       (carry[0]));
  full_adder_198 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_197 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_196 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_195 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_194 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_193 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_192 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_24_227(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__ha_1 g28__6417(.A (B), .B (A), .COUT (Cout), .SUM
       (S));
endmodule

module full_adder_191(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g65__5477(.A (Cin), .B (A), .CIN (B), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_190(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__2398(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_189(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__5107(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_188(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__6260(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_187(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__4319(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_186(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__8428(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_185(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__5526(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module ripple_carry_adder_WIDTH8_5(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder_24_227 F1A(.A (A[0]), .B (B[0]), .Cin (1'b0), .S (S[0]),
       .Cout (carry[0]));
  full_adder_191 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_190 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_189 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_188 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_187 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_186 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_185 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder_32_229(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__xnor2_1 g37__6783(.A (A), .B (B), .Y (S));
  sky130_fd_sc_hd__or2_1 g38__3680(.A (A), .B (B), .X (Cout));
endmodule

module full_adder_184(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__1617(.A (A), .B (Cin), .CIN (B), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_183(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__2802(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_182(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__1705(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_181(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__5122(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_180(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__8246(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_179(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__7098(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_178(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__6131(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module ripple_carry_adder_WIDTH8_6(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder_32_229 F1A(.A (A[0]), .B (B[0]), .Cin (1'b1), .S (S[0]),
       .Cout (carry[0]));
  full_adder_184 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_183 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_182 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_181 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_180 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_179 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_178 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module full_adder(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__o21ai_1 g65__1881(.A1 (n_1), .A2 (n_2), .B1 (n_0),
       .Y (Cout));
  sky130_fd_sc_hd__xnor2_1 g66__5115(.A (n_1), .B (n_3), .Y (S));
  sky130_fd_sc_hd__xor2_1 g68__7482(.A (B), .B (A), .X (n_3));
  sky130_fd_sc_hd__nor2_1 g69__4733(.A (A), .B (B), .Y (n_2));
  sky130_fd_sc_hd__clkinv_1 g71(.A (Cin), .Y (n_1));
  sky130_fd_sc_hd__nand2_1 g2__6161(.A (B), .B (A), .Y (n_0));
endmodule

module full_adder_226(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2_1 g60__9315(.A (n_3), .B (n_1), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g61__9945(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g62__2883(.A (Cin), .B (n_0), .Y (n_3));
  sky130_fd_sc_hd__xor2_1 g63__2346(.A (B), .B (A), .X (n_2));
  sky130_fd_sc_hd__nand2_1 g65__1666(.A (B), .B (A), .Y (n_1));
  sky130_fd_sc_hd__or2_1 g2__7410(.A (A), .B (B), .X (n_0));
endmodule

module full_adder_225(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_1, n_2, n_3, n_4;
  sky130_fd_sc_hd__xor2_1 g58__6417(.A (n_3), .B (Cin), .X (S));
  sky130_fd_sc_hd__nand2_1 g59__5477(.A (Cin), .B (n_1), .Y (n_4));
  sky130_fd_sc_hd__ha_1 g61__2398(.A (B), .B (A), .COUT (n_2), .SUM
       (n_3));
  sky130_fd_sc_hd__or2_0 g62__5107(.A (B), .B (A), .X (n_1));
  sky130_fd_sc_hd__nand2b_1 g2__6260(.A_N (n_2), .B (n_4), .Y (Cout));
endmodule

module full_adder_224(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  wire n_0, n_1, n_2, n_3;
  sky130_fd_sc_hd__nand2b_1 g57__4319(.A_N (n_1), .B (n_3), .Y (Cout));
  sky130_fd_sc_hd__xor2_1 g58__8428(.A (n_2), .B (Cin), .X (S));
  sky130_fd_sc_hd__o21ai_1 g59__5526(.A1 (A), .A2 (n_0), .B1 (Cin), .Y
       (n_3));
  sky130_fd_sc_hd__ha_1 g60__6783(.A (B), .B (A), .COUT (n_1), .SUM
       (n_2));
  sky130_fd_sc_hd__clkbuf_1 g61(.A (B), .X (n_0));
endmodule

module full_adder_223(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__3680(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_222(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__1617(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_221(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__2802(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module full_adder_220(A, B, Cin, S, Cout);
  input A, B, Cin;
  output S, Cout;
  wire A, B, Cin;
  wire S, Cout;
  sky130_fd_sc_hd__fa_1 g57__1705(.A (A), .B (B), .CIN (Cin), .COUT
       (Cout), .SUM (S));
endmodule

module ripple_carry_adder_WIDTH8(A, B, Cin, S, Cout);
  input [7:0] A, B;
  input Cin;
  output [7:0] S;
  output Cout;
  wire [7:0] A, B;
  wire Cin;
  wire [7:0] S;
  wire Cout;
  wire [7:0] carry;
  full_adder F1A(.A (A[0]), .B (B[0]), .Cin (Cin), .S (S[0]), .Cout
       (carry[0]));
  full_adder_226 \full_adder_loop[1].FA (.A (A[1]), .B (B[1]), .Cin
       (carry[0]), .S (S[1]), .Cout (carry[1]));
  full_adder_225 \full_adder_loop[2].FA (.A (A[2]), .B (B[2]), .Cin
       (carry[1]), .S (S[2]), .Cout (carry[2]));
  full_adder_224 \full_adder_loop[3].FA (.A (A[3]), .B (B[3]), .Cin
       (carry[2]), .S (S[3]), .Cout (carry[3]));
  full_adder_223 \full_adder_loop[4].FA (.A (A[4]), .B (B[4]), .Cin
       (carry[3]), .S (S[4]), .Cout (carry[4]));
  full_adder_222 \full_adder_loop[5].FA (.A (A[5]), .B (B[5]), .Cin
       (carry[4]), .S (S[5]), .Cout (carry[5]));
  full_adder_221 \full_adder_loop[6].FA (.A (A[6]), .B (B[6]), .Cin
       (carry[5]), .S (S[6]), .Cout (carry[6]));
  full_adder_220 \full_adder_loop[7].FA (.A (A[7]), .B (B[7]), .Cin
       (carry[6]), .S (S[7]), .Cout (Cout));
endmodule

module carry_select_adder_8888_32bits(A, B, Cin, S, Cout);
  input [31:0] A, B;
  input Cin;
  output [31:0] S;
  output Cout;
  wire [31:0] A, B;
  wire Cin;
  wire [31:0] S;
  wire Cout;
  wire [31:0] S0;
  wire [3:0] C0;
  wire [31:0] S1;
  wire [3:0] C1;
  wire [3:0] C_mid;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90;
  ripple_carry_adder_WIDTH8_5_231 \CSA_BLOCKS[1].RCA_C0 (.A ({n_90,
       n_89, n_88, n_87, n_86, n_35, n_34, n_85}), .B ({n_84, n_83,
       n_82, n_81, n_80, n_79, n_41, n_78}), .Cin (1'b0), .S
       (S0[15:8]), .Cout (C0[1]));
  ripple_carry_adder_WIDTH8_6_233 \CSA_BLOCKS[1].RCA_C1 (.A ({n_90,
       n_89, n_88, n_87, n_86, n_29, n_33, n_85}), .B ({n_84, n_83,
       n_82, n_81, n_80, n_79, n_42, n_78}), .Cin (1'b1), .S
       (S1[15:8]), .Cout (C1[1]));
  ripple_carry_adder_WIDTH8_5_232 \CSA_BLOCKS[2].RCA_C0 (.A ({n_76,
       n_75, n_74, n_73, n_72, n_71, n_70, n_69}), .B ({n_68, n_67,
       n_66, n_65, n_64, n_63, n_62, n_61}), .Cin (1'b0), .S
       (S0[23:16]), .Cout (C0[2]));
  ripple_carry_adder_WIDTH8_6_234 \CSA_BLOCKS[2].RCA_C1 (.A ({n_76,
       n_75, n_74, n_73, n_72, n_71, n_70, n_69}), .B ({n_68, n_67,
       n_66, n_65, n_64, n_63, n_62, n_61}), .Cin (1'b1), .S
       (S1[23:16]), .Cout (C1[2]));
  ripple_carry_adder_WIDTH8_5 \CSA_BLOCKS[3].RCA_C0 (.A ({n_59, n_58,
       n_57, n_56, n_55, n_54, n_53, n_52}), .B ({n_51, n_50, n_49,
       n_48, n_47, n_46, n_45, n_44}), .Cin (1'b0), .S (S0[31:24]),
       .Cout (C0[3]));
  ripple_carry_adder_WIDTH8_6 \CSA_BLOCKS[3].RCA_C1 (.A ({n_59, n_58,
       n_57, n_56, n_55, n_54, n_53, n_52}), .B ({n_51, n_50, n_49,
       n_48, n_47, n_46, n_45, n_44}), .Cin (1'b1), .S (S1[31:24]),
       .Cout (C1[3]));
  ripple_carry_adder_WIDTH8 RCA_LSB(.A ({n_17, n_10, n_13, n_15, n_12,
       n_43, n_30, n_31}), .B ({n_25, n_18, n_14, n_22, n_19, n_37,
       n_36, n_38}), .Cin (n_39), .S (S[7:0]), .Cout (C_mid[0]));
  sky130_fd_sc_hd__inv_1 g295(.A (n_5), .Y (n_43));
  sky130_fd_sc_hd__inv_2 g330(.A (n_40), .Y (n_42));
  sky130_fd_sc_hd__inv_2 g329(.A (n_40), .Y (n_41));
  sky130_fd_sc_hd__inv_1 g293(.A (n_16), .Y (n_39));
  sky130_fd_sc_hd__inv_2 g254(.A (n_26), .Y (n_38));
  sky130_fd_sc_hd__inv_2 g256(.A (n_27), .Y (n_37));
  sky130_fd_sc_hd__inv_2 g263(.A (n_21), .Y (n_36));
  sky130_fd_sc_hd__inv_2 g333(.A (n_24), .Y (n_85));
  sky130_fd_sc_hd__inv_2 g266(.A (n_6), .Y (n_62));
  sky130_fd_sc_hd__inv_2 g320(.A (n_8), .Y (n_61));
  sky130_fd_sc_hd__inv_2 g316(.A (n_7), .Y (n_79));
  sky130_fd_sc_hd__inv_2 g335(.A (n_20), .Y (n_69));
  sky130_fd_sc_hd__inv_2 g304(.A (n_23), .Y (n_78));
  sky130_fd_sc_hd__inv_2 g309(.A (n_9), .Y (n_70));
  sky130_fd_sc_hd__inv_2 g324(.A (n_28), .Y (n_35));
  sky130_fd_sc_hd__inv_2 g314(.A (n_32), .Y (n_34));
  sky130_fd_sc_hd__inv_2 g313(.A (n_32), .Y (n_33));
  sky130_fd_sc_hd__inv_2 g258(.A (n_4), .Y (n_31));
  sky130_fd_sc_hd__inv_2 g291(.A (n_11), .Y (n_30));
  sky130_fd_sc_hd__inv_2 g323(.A (n_28), .Y (n_29));
  sky130_fd_sc_hd__clkinv_1 g257(.A (B[2]), .Y (n_27));
  sky130_fd_sc_hd__clkinv_1 g255(.A (B[0]), .Y (n_26));
  sky130_fd_sc_hd__clkbuf_1 g298(.A (B[7]), .X (n_25));
  sky130_fd_sc_hd__clkinv_1 g334(.A (A[8]), .Y (n_24));
  sky130_fd_sc_hd__clkinv_1 g305(.A (B[8]), .Y (n_23));
  sky130_fd_sc_hd__clkbuf_1 g290(.A (B[4]), .X (n_22));
  sky130_fd_sc_hd__clkinv_1 g264(.A (B[1]), .Y (n_21));
  sky130_fd_sc_hd__clkinv_1 g336(.A (A[16]), .Y (n_20));
  sky130_fd_sc_hd__clkbuf_1 g261(.A (B[3]), .X (n_19));
  sky130_fd_sc_hd__clkbuf_1 g297(.A (B[6]), .X (n_18));
  sky130_fd_sc_hd__clkbuf_1 g262(.A (A[7]), .X (n_17));
  sky130_fd_sc_hd__clkinv_1 g294(.A (Cin), .Y (n_16));
  sky130_fd_sc_hd__buf_1 g287(.A (A[23]), .X (n_76));
  sky130_fd_sc_hd__clkbuf_1 g282(.A (B[26]), .X (n_46));
  sky130_fd_sc_hd__clkbuf_1 g337(.A (B[13]), .X (n_82));
  sky130_fd_sc_hd__buf_1 g280(.A (A[11]), .X (n_86));
  sky130_fd_sc_hd__clkbuf_1 g289(.A (B[25]), .X (n_45));
  sky130_fd_sc_hd__buf_1 g302(.A (A[18]), .X (n_71));
  sky130_fd_sc_hd__buf_1 g303(.A (A[19]), .X (n_72));
  sky130_fd_sc_hd__clkbuf_1 g311(.A (A[24]), .X (n_52));
  sky130_fd_sc_hd__clkbuf_1 g276(.A (B[11]), .X (n_80));
  sky130_fd_sc_hd__buf_1 g326(.A (A[13]), .X (n_88));
  sky130_fd_sc_hd__buf_1 g288(.A (A[22]), .X (n_75));
  sky130_fd_sc_hd__clkbuf_1 g307(.A (B[19]), .X (n_64));
  sky130_fd_sc_hd__buf_1 g285(.A (A[30]), .X (n_58));
  sky130_fd_sc_hd__clkbuf_1 g319(.A (B[31]), .X (n_51));
  sky130_fd_sc_hd__clkbuf_1 g281(.A (B[21]), .X (n_66));
  sky130_fd_sc_hd__clkbuf_1 g283(.A (B[27]), .X (n_47));
  sky130_fd_sc_hd__clkbuf_1 g268(.A (B[14]), .X (n_83));
  sky130_fd_sc_hd__buf_1 g284(.A (A[27]), .X (n_55));
  sky130_fd_sc_hd__clkbuf_1 g301(.A (B[12]), .X (n_81));
  sky130_fd_sc_hd__clkbuf_1 g318(.A (B[24]), .X (n_44));
  sky130_fd_sc_hd__clkbuf_1 g299(.A (A[4]), .X (n_15));
  sky130_fd_sc_hd__clkbuf_1 g253(.A (B[5]), .X (n_14));
  sky130_fd_sc_hd__clkbuf_1 g265(.A (A[5]), .X (n_13));
  sky130_fd_sc_hd__clkbuf_1 g260(.A (A[3]), .X (n_12));
  sky130_fd_sc_hd__clkinv_1 g292(.A (A[1]), .Y (n_11));
  sky130_fd_sc_hd__clkbuf_1 g300(.A (A[6]), .X (n_10));
  sky130_fd_sc_hd__clkinv_1 g310(.A (A[17]), .Y (n_9));
  sky130_fd_sc_hd__clkinv_1 g321(.A (B[16]), .Y (n_8));
  sky130_fd_sc_hd__clkinv_1 g317(.A (B[10]), .Y (n_7));
  sky130_fd_sc_hd__clkinv_1 g267(.A (B[17]), .Y (n_6));
  sky130_fd_sc_hd__clkinv_1 g296(.A (A[2]), .Y (n_5));
  sky130_fd_sc_hd__clkinv_1 g259(.A (A[0]), .Y (n_4));
  sky130_fd_sc_hd__clkbuf_1 g274(.A (B[30]), .X (n_50));
  sky130_fd_sc_hd__clkbuf_1 g270(.A (B[20]), .X (n_65));
  sky130_fd_sc_hd__buf_1 g332(.A (A[29]), .X (n_57));
  sky130_fd_sc_hd__buf_1 g279(.A (A[15]), .X (n_90));
  sky130_fd_sc_hd__buf_1 g306(.A (A[14]), .X (n_89));
  sky130_fd_sc_hd__clkbuf_1 g322(.A (B[22]), .X (n_67));
  sky130_fd_sc_hd__clkinv_2 g315(.A (A[9]), .Y (n_32));
  sky130_fd_sc_hd__clkbuf_1 g312(.A (B[23]), .X (n_68));
  sky130_fd_sc_hd__buf_1 g278(.A (A[26]), .X (n_54));
  sky130_fd_sc_hd__clkbuf_1 g273(.A (B[29]), .X (n_49));
  sky130_fd_sc_hd__clkinv_2 g325(.A (A[10]), .Y (n_28));
  sky130_fd_sc_hd__buf_1 g271(.A (A[12]), .X (n_87));
  sky130_fd_sc_hd__buf_1 g277(.A (A[31]), .X (n_59));
  sky130_fd_sc_hd__buf_1 g272(.A (A[28]), .X (n_56));
  sky130_fd_sc_hd__buf_1 g308(.A (A[21]), .X (n_74));
  sky130_fd_sc_hd__clkbuf_1 g269(.A (B[28]), .X (n_48));
  sky130_fd_sc_hd__clkbuf_1 g275(.A (B[18]), .X (n_63));
  sky130_fd_sc_hd__clkbuf_1 g327(.A (A[25]), .X (n_53));
  sky130_fd_sc_hd__buf_1 g328(.A (A[20]), .X (n_73));
  sky130_fd_sc_hd__clkinv_2 g331(.A (B[9]), .Y (n_40));
  sky130_fd_sc_hd__clkbuf_1 g286(.A (B[15]), .X (n_84));
  sky130_fd_sc_hd__mux2_2 g501__5122(.A0 (S1[27]), .A1 (S0[27]), .S
       (n_3), .X (S[27]));
  sky130_fd_sc_hd__mux2_2 g502__8246(.A0 (S1[30]), .A1 (S0[30]), .S
       (n_3), .X (S[30]));
  sky130_fd_sc_hd__mux2_2 g503__7098(.A0 (S1[31]), .A1 (S0[31]), .S
       (n_3), .X (S[31]));
  sky130_fd_sc_hd__mux2_2 g504__6131(.A0 (C1[3]), .A1 (C0[3]), .S
       (n_3), .X (Cout));
  sky130_fd_sc_hd__mux2_2 g505__1881(.A0 (S1[25]), .A1 (S0[25]), .S
       (n_3), .X (S[25]));
  sky130_fd_sc_hd__mux2_2 g506__5115(.A0 (S1[29]), .A1 (S0[29]), .S
       (n_3), .X (S[29]));
  sky130_fd_sc_hd__mux2_2 g507__7482(.A0 (S1[26]), .A1 (S0[26]), .S
       (n_3), .X (S[26]));
  sky130_fd_sc_hd__mux2_2 g508__4733(.A0 (S1[24]), .A1 (S0[24]), .S
       (n_3), .X (S[24]));
  sky130_fd_sc_hd__mux2_2 g509__6161(.A0 (S1[28]), .A1 (S0[28]), .S
       (n_3), .X (S[28]));
  sky130_fd_sc_hd__mux2_2 g510__9315(.A0 (S1[19]), .A1 (S0[19]), .S
       (n_2), .X (S[19]));
  sky130_fd_sc_hd__mux2_2 g511__9945(.A0 (S1[20]), .A1 (S0[20]), .S
       (n_2), .X (S[20]));
  sky130_fd_sc_hd__mux2_2 g512__2883(.A0 (S1[18]), .A1 (S0[18]), .S
       (n_2), .X (S[18]));
  sky130_fd_sc_hd__mux2i_2 g513__2346(.A0 (C1[2]), .A1 (C0[2]), .S
       (n_2), .Y (n_3));
  sky130_fd_sc_hd__mux2_2 g514__1666(.A0 (S1[23]), .A1 (S0[23]), .S
       (n_2), .X (S[23]));
  sky130_fd_sc_hd__mux2_2 g515__7410(.A0 (S1[16]), .A1 (S0[16]), .S
       (n_2), .X (S[16]));
  sky130_fd_sc_hd__mux2_2 g516__6417(.A0 (S1[17]), .A1 (S0[17]), .S
       (n_2), .X (S[17]));
  sky130_fd_sc_hd__mux2_2 g517__5477(.A0 (S1[22]), .A1 (S0[22]), .S
       (n_2), .X (S[22]));
  sky130_fd_sc_hd__mux2_2 g518__2398(.A0 (S1[21]), .A1 (S0[21]), .S
       (n_2), .X (S[21]));
  sky130_fd_sc_hd__mux2_2 g519__5107(.A0 (S0[15]), .A1 (S1[15]), .S
       (C_mid[0]), .X (S[15]));
  sky130_fd_sc_hd__mux2_2 g520__6260(.A0 (S0[8]), .A1 (S1[8]), .S
       (C_mid[0]), .X (S[8]));
  sky130_fd_sc_hd__mux2_2 g521__4319(.A0 (S0[14]), .A1 (S1[14]), .S
       (C_mid[0]), .X (S[14]));
  sky130_fd_sc_hd__mux2i_4 g522__8428(.A0 (n_0), .A1 (n_1), .S
       (C_mid[0]), .Y (n_2));
  sky130_fd_sc_hd__mux2_2 g523__5526(.A0 (S0[11]), .A1 (S1[11]), .S
       (C_mid[0]), .X (S[11]));
  sky130_fd_sc_hd__mux2_2 g524__6783(.A0 (S0[12]), .A1 (S1[12]), .S
       (C_mid[0]), .X (S[12]));
  sky130_fd_sc_hd__mux2_2 g525__3680(.A0 (S0[13]), .A1 (S1[13]), .S
       (C_mid[0]), .X (S[13]));
  sky130_fd_sc_hd__mux2_2 g526__1617(.A0 (S0[10]), .A1 (S1[10]), .S
       (C_mid[0]), .X (S[10]));
  sky130_fd_sc_hd__mux2_2 g527__2802(.A0 (S0[9]), .A1 (S1[9]), .S
       (C_mid[0]), .X (S[9]));
  sky130_fd_sc_hd__buf_1 drc_bufs(.A (C1[1]), .X (n_1));
  sky130_fd_sc_hd__buf_1 drc_bufs528(.A (C0[1]), .X (n_0));
endmodule

